
spring:
  application:
    name: demo-book-service # 微服务的名称
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos服务地址
        watch:
          enabled: true # 开启服务变更监听
server:
  port: 3457 # 预定服务端口