[
	{
		"code": "IN",
		"ZH_CN": "印度",
		"ZH_TW": "印度",
		"EN": "India",
		"KO": "인도",
		"AR": "الهند",
		"IT": "India",
		"ES": "India",
		"DE": "Indien",
		"NB_NO": "India",
		"FR": "Inde",
		"areaCode": "+91"
	},
	{
		"code": "AX",
		"ZH_CN": "奥兰",
		"ZH_TW": "奧蘭",
		"EN": "Åland Islands",
		"KO": "올란드 제도",
		"IT": "Aland",
		"ES": "Aland",
		"DE": "Aland",
		"NB_NO": "Åland",
		"FR": "Aland",
		"areaCode": "+358"
	},
	{
		"code": "BL",
		"ZH_CN": "圣巴泰勒米",
		"ZH_TW": "聖巴多祿繆",
		"EN": "Saint Barthélemy",
		"KO": "생바르텔르미",
		"IT": "Saint-Barthélemy",
		"ES": "San Bartolomé",
		"DE": "Saint-Barthélemy",
		"NB_NO": "Saint Martin",
		"FR": "Saint-Barthélemy",
		"areaCode": "+590"
	},
	{
		"code": "CW",
		"ZH_CN": "古拉索岛",
		"ZH_TW": "古拉索島",
		"EN": "Curaçao",
		"KO": "퀴라소",
		"IT": "Curaçao",
		"ES": "Curazao",
		"DE": "Curaçao",
		"NB_NO": "Guração",
		"FR": "Curaçao",
		"areaCode": "+599"
	},
	{
		"code": "ME",
		"ZH_CN": "蒙特内哥罗",
		"ZH_TW": "蒙特內哥羅",
		"EN": "Montenegro",
		"KO": "몬테네그로",
		"IT": "Montenegro",
		"ES": "Montenegro",
		"DE": "Montenegro",
		"NB_NO": "Montenegro",
		"FR": "Monténégro",
		"areaCode": "+382"
	},
	{
		"code": "MF",
		"ZH_CN": "圣马丁",
		"ZH_TW": "聖馬丁島",
		"EN": "Saint Martin",
		"KO": "세인트마틴 섬",
		"IT": "Sint Maarten",
		"ES": "San Martín",
		"DE": "St. Martin",
		"NB_NO": "Saint Martin",
		"FR": "Saint-Martin (France)",
		"areaCode": "+590"
	},
	{
		"code": "SS",
		"ZH_CN": "南苏丹",
		"ZH_TW": "南蘇丹",
		"EN": "South Sudan",
		"KO": "남수단",
		"IT": "Sudan del Sud",
		"ES": "Sudán del Sur",
		"DE": "Südsudan",
		"NB_NO": "Sør-Sudan",
		"FR": "Soudan du Sud",
		"areaCode": "+211"
	},
	{
		"code": "SX",
		"ZH_CN": "荷属圣马丁",
		"ZH_TW": "荷屬聖馬丁",
		"EN": "Sint Maarten",
		"KO": "신트마르턴",
		"IT": "Sint Maarten",
		"ES": "Sint Maarten",
		"DE": "Sint Maarten",
		"NB_NO": "Saint Martin",
		"FR": "Saint-Martin (Pays-Bas)",
		"areaCode": "+1721"
	},
	{
		"code": "TL",
		"ZH_CN": "东帝汶",
		"ZH_TW": "東帝汶",
		"EN": "Timor-Leste",
		"KO": "동티모르",
		"IT": "Timor Est",
		"ES": "Timor Oriental",
		"DE": "Osttimor",
		"NB_NO": "Øst-Timor",
		"FR": "Timor oriental",
		"areaCode": "+670"
	},
	{
		"code": "UM",
		"ZH_CN": "美国边远岛屿",
		"ZH_TW": "美國邊遠島嶼",
		"EN": "United States Minor outlying Islands",
		"KO": "미국령 군소 제도",
		"IT": "Isole Minori Esterne degli Stati Uniti d'America",
		"ES": "Islas Ultramarinas Menores de Estados Unidos",
		"DE": "United States Minor Outlying Islands",
		"NB_NO": "",
		"FR": "Îles mineures éloignées des États-Unis",
		"areaCode": "+1"
	},
	{
		"code": "XK",
		"ZH_CN": "科索沃",
		"ZH_TW": "科索沃",
		"EN": "Kosovo",
		"KO": "코소보",
		"IT": "Kosovo",
		"ES": "Kosovo",
		"DE": "Kosovo",
		"NB_NO": "Kosovo",
		"FR": "Kosovo",
		"areaCode": "+383"
	},
	{
		"code": "TH",
		"ZH_CN": "泰国",
		"ZH_TW": "泰國",
		"EN": "Thailand",
		"KO": "태국",
		"AR": "تايلاند",
		"IT": "Tailandia",
		"ES": "Tailandia",
		"DE": "Thailand",
		"NB_NO": "Thailand",
		"FR": "Thaïlande",
		"areaCode": "+66"
	},
	{
		"code": "CN",
		"ZH_CN": "中国",
		"ZH_TW": "中國",
		"EN": "China",
		"KO": "중국",
		"AR": "الصين",
		"IT": "Cina",
		"ES": "China",
		"DE": "China",
		"NB_NO": "Kina",
		"FR": "Chine",
		"areaCode": "+86"
	},
	{
		"code": "VN",
		"ZH_CN": "越南",
		"ZH_TW": "越南",
		"EN": "Vietnam",
		"KO": "베트남",
		"AR": "فييت نام",
		"IT": "Vietnam",
		"ES": "Vietnam",
		"DE": "Vietnam",
		"NB_NO": "Vietnam",
		"FR": "Vietnam",
		"areaCode": "+84"
	},
	{
		"code": "PH",
		"ZH_CN": "菲律宾",
		"ZH_TW": "菲律賓",
		"EN": "Philippines",
		"KO": "필리핀 제도",
		"AR": "الفلبين",
		"IT": "Filippine",
		"ES": "Filipinas",
		"DE": "Philippine",
		"NB_NO": "Filippinene",
		"FR": "Philippines",
		"areaCode": "+63"
	},
	{
		"code": "MY",
		"ZH_CN": "马来西亚",
		"ZH_TW": "馬來西亞",
		"EN": "Malaysia",
		"KO": "말레이시아",
		"AR": "ماليزيا",
		"IT": "Malaysia",
		"ES": "Malasia",
		"DE": "Malaysia",
		"NB_NO": "Malaysia",
		"FR": "Malaisie",
		"areaCode": "+60"
	},
	{
		"code": "ID",
		"ZH_CN": "印度尼西亚",
		"ZH_TW": "印度尼西亞",
		"EN": "Indonesia",
		"KO": "인도네시아 공화국",
		"AR": "أندونيسيا",
		"IT": "Indonesia",
		"ES": "Indonesia",
		"DE": "Indonesien",
		"NB_NO": "Indonesia",
		"FR": "Indonésie",
		"areaCode": "+62"
	},
	{
		"code": "TW",
		"ZH_CN": "中国台湾",
		"ZH_TW": "中國臺灣",
		"EN": "Taiwan, China",
		"KO": "대만",
		"AR": "تايوان",
		"IT": "Taiwan, Cina",
		"ES": "Taiwán, China",
		"DE": "Taiwan, China",
		"NB_NO": "Taiwan",
		"FR": "Taïwan, Chine",
		"areaCode": "+886"
	},
	{
		"code": "SG",
		"ZH_CN": "新加坡",
		"ZH_TW": "新加坡",
		"EN": "Singapore",
		"KO": "싱가포르",
		"AR": "سنغافورة",
		"IT": "Singapore",
		"ES": "Singapur",
		"DE": "Singapur",
		"NB_NO": "Singapore",
		"FR": "Singapour",
		"areaCode": "+65"
	},
	{
		"code": "HK",
		"ZH_CN": "中国香港",
		"ZH_TW": "中國香港",
		"EN": "Hong Kong, China",
		"KO": "홍콩",
		"AR": "هونج كونج",
		"IT": "Hong Kong, Cina",
		"ES": "Hong Kong, China",
		"DE": "Hongkong, China",
		"NB_NO": "Hongkong S.A.R. Kina",
		"FR": "Hong Kong, Chine",
		"areaCode": "+852"
	},
	{
		"code": "AF",
		"ZH_CN": "阿富汗",
		"ZH_TW": "阿富汗",
		"EN": "Afghanistan",
		"KO": "아프가니스탄",
		"AR": "أفغانستان",
		"IT": "Afghanistan",
		"ES": "Afganistán",
		"DE": "Afghanistan",
		"NB_NO": "Afghanistan",
		"FR": "Afghanistan",
		"areaCode": "+93"
	},
	{
		"code": "DZ",
		"ZH_CN": "阿尔及利亚",
		"ZH_TW": "阿爾及利亞",
		"EN": "Algeria",
		"KO": "알제리",
		"AR": "الجزائر",
		"IT": "Algeria",
		"ES": "Argelia",
		"DE": "Algerien",
		"NB_NO": "Algerie",
		"FR": "Algérie",
		"areaCode": "+213"
	},
	{
		"code": "AD",
		"ZH_CN": "安道尔",
		"ZH_TW": "安道爾",
		"EN": "Andorra",
		"KO": "안도라",
		"AR": "أندورا",
		"IT": "Andorra",
		"ES": "Andorra",
		"DE": "Andorra",
		"NB_NO": "Andorra",
		"FR": "Andorre",
		"areaCode": "+376"
	},
	{
		"code": "AI",
		"ZH_CN": "安圭拉",
		"ZH_TW": "安圭拉",
		"EN": "Anguilla",
		"KO": "앵 귈라",
		"AR": "أنغيلا",
		"IT": "Anguilla, Isola",
		"ES": "Anguila",
		"DE": "Anguilla",
		"NB_NO": "Anguilla",
		"FR": "Anguilla",
		"areaCode": "+1264"
	},
	{
		"code": "AG",
		"ZH_CN": "安提瓜和巴布达",
		"ZH_TW": "安提瓜和巴布達",
		"EN": "Antigua and Barbuda",
		"KO": "안티구아와 바부 다",
		"AR": "أنتيغوا وبربودا",
		"IT": "Antigua e Barbuda",
		"ES": "Antigua y Barbuda",
		"DE": "Antigua und Barbuda",
		"NB_NO": "Antigua og Barbuda",
		"FR": "Antigua-et-Barbuda",
		"areaCode": "+1268"
	},
	{
		"code": "AM",
		"ZH_CN": "亚美尼亚",
		"ZH_TW": "亞美尼亞",
		"EN": "Armenia",
		"KO": "아르메니아",
		"AR": "أرمينيا",
		"IT": "Armenia",
		"ES": "Armenia",
		"DE": "Armenien",
		"NB_NO": "Armenia",
		"FR": "Arménie",
		"areaCode": "+374"
	},
	{
		"code": "AU",
		"ZH_CN": "澳大利亚",
		"ZH_TW": "澳大利亞",
		"EN": "Australia",
		"KO": "호주",
		"AR": "أستراليا",
		"IT": "Australia",
		"ES": "Australia",
		"DE": "Australien",
		"NB_NO": "Australia",
		"FR": "Australie",
		"areaCode": "+61"
	},
	{
		"code": "AZ",
		"ZH_CN": "阿塞拜疆",
		"ZH_TW": "阿塞拜疆",
		"EN": "Azerbaijan",
		"KO": "아제르바이잔",
		"AR": "أذربيجان",
		"IT": "Azerbaigian",
		"ES": "Azerbaiyán",
		"DE": "Aserbaidschan",
		"NB_NO": "Aserbajdsjan",
		"FR": "Azerbaïdjan",
		"areaCode": "+994"
	},
	{
		"code": "BD",
		"ZH_CN": "孟加拉国",
		"ZH_TW": "孟加拉國",
		"EN": "Bangladesh",
		"KO": "방글라데시",
		"AR": "بنغلاديش",
		"IT": "Bangladesh",
		"ES": "Bangladés",
		"DE": "Bangladesch",
		"NB_NO": "Bangladesh",
		"FR": "Bangladesh",
		"areaCode": "+880"
	},
	{
		"code": "BY",
		"ZH_CN": "白俄罗斯",
		"ZH_TW": "白俄羅斯",
		"EN": "Belarus",
		"KO": "벨라루스",
		"AR": "روسيا البيضاء",
		"IT": "Bielorussia",
		"ES": "Bielorrusia",
		"DE": "Weißrussland (Belarus)",
		"NB_NO": "Hviterussland",
		"FR": "Bélarus",
		"areaCode": "+375"
	},
	{
		"code": "BZ",
		"ZH_CN": "伯利兹",
		"ZH_TW": "伯利茲",
		"EN": "Belize",
		"KO": "벨리즈",
		"AR": "بليز",
		"IT": "Belize",
		"ES": "Belice",
		"DE": "Belize",
		"NB_NO": "Belize",
		"FR": "Belize",
		"areaCode": "+501"
	},
	{
		"code": "BM",
		"ZH_CN": "百慕大",
		"ZH_TW": "百慕大",
		"EN": "Bermuda",
		"KO": "버뮤다",
		"AR": "برمودا",
		"IT": "Bermuda",
		"ES": "Bermudas",
		"DE": "Bermudas",
		"NB_NO": "Bermuda",
		"FR": "Bermudes",
		"areaCode": "+1441"
	},
	{
		"code": "BO",
		"ZH_CN": "玻利维亚",
		"ZH_TW": "玻利維亞",
		"EN": "Bolivia",
		"KO": "볼리비아",
		"AR": "بوليفيا",
		"IT": "Bolivia",
		"ES": "Bolivia",
		"DE": "Bolivien",
		"NB_NO": "Bolivia",
		"FR": "Bolivie",
		"areaCode": "+591"
	},
	{
		"code": "BW",
		"ZH_CN": "博茨瓦纳",
		"ZH_TW": "博茨瓦納",
		"EN": "Botswana",
		"KO": "보츠와나",
		"AR": "بوتسوانا",
		"IT": "Botswana",
		"ES": "Botsuana",
		"DE": "Botswana",
		"NB_NO": "Botswana",
		"FR": "Botswana",
		"areaCode": "+267"
	},
	{
		"code": "BR",
		"ZH_CN": "巴西",
		"ZH_TW": "巴西",
		"EN": "Brazil",
		"KO": "브라질",
		"AR": "البرازيل",
		"IT": "Brasile",
		"ES": "Brasil",
		"DE": "Brasilien",
		"NB_NO": "Brasil",
		"FR": "Brésil",
		"areaCode": "+55"
	},
	{
		"code": "VG",
		"ZH_CN": "英属维尔京群岛",
		"ZH_TW": "英屬維爾京群島",
		"EN": "Virgin Islands, British",
		"KO": "영국령 버진 아일랜드",
		"AR": "جزر فيرجن البريطانية",
		"IT": "Vergini Britanniche, Isole",
		"ES": "Islas Vírgenes Británicas",
		"DE": "Jungferninseln, Britische",
		"NB_NO": "Jomfruøyene (British)",
		"FR": "Îles Vierges britanniques",
		"areaCode": "+1284"
	},
	{
		"code": "BG",
		"ZH_CN": "保加利亚",
		"ZH_TW": "保加利亞",
		"EN": "Bulgaria",
		"KO": "불가리아",
		"AR": "بلغاريا",
		"IT": "Bulgaria",
		"ES": "Bulgaria",
		"DE": "Bulgarien",
		"NB_NO": "Bulgaria",
		"FR": "Bulgarie",
		"areaCode": "+359"
	},
	{
		"code": "MM",
		"ZH_CN": "缅甸",
		"ZH_TW": "緬甸",
		"EN": "Myanmar",
		"KO": "미얀마",
		"AR": "ميانمار",
		"IT": "Myanmar",
		"ES": "Myanmar (Birmania)",
		"DE": "Myanmar",
		"NB_NO": "Myanmar",
		"FR": "Myanmar",
		"areaCode": "+95"
	},
	{
		"code": "KH",
		"ZH_CN": "柬埔寨",
		"ZH_TW": "柬埔寨",
		"EN": "Cambodia",
		"KO": "캄보디아",
		"AR": "كمبوديا",
		"IT": "Cambogia",
		"ES": "Camboya",
		"DE": "Kambodscha",
		"NB_NO": "Kambodsja",
		"FR": "Cambodge",
		"areaCode": "+855"
	},
	{
		"code": "CA",
		"ZH_CN": "加拿大",
		"ZH_TW": "加拿大",
		"EN": "Canada",
		"KO": "캐나다",
		"AR": "كندا",
		"IT": "Canada",
		"ES": "Canadá",
		"DE": "Kanada",
		"NB_NO": "Canada",
		"FR": "Canada",
		"areaCode": "+1"
	},
	{
		"code": "KY",
		"ZH_CN": "开曼群岛",
		"ZH_TW": "開曼群島",
		"EN": "Cayman Islands",
		"KO": "케이맨 제도",
		"AR": "جزر كايمان",
		"IT": "Cayman, Isole",
		"ES": "Islas Caimán",
		"DE": "Kaimaninseln",
		"NB_NO": "",
		"FR": "Caïmans (Îles)",
		"areaCode": "+1345"
	},
	{
		"code": "TD",
		"ZH_CN": "乍得",
		"ZH_TW": "乍得",
		"EN": "Chad",
		"KO": "차드",
		"AR": "تشاد",
		"IT": "Ciad",
		"ES": "Chad",
		"DE": "Tschad",
		"NB_NO": "Tsjad",
		"FR": "Tchad",
		"areaCode": "+235"
	},
	{
		"code": "CC",
		"ZH_CN": "科科斯（基林）群岛",
		"ZH_TW": "科科斯（基林）群島",
		"EN": "Cocos (Keeling) Islands",
		"KO": "코코스 제도",
		"AR": "جزر كوكوس (كيلينغ)",
		"IT": "Cocos (Keeling), Isole",
		"ES": "Islas Cocos (Keeling)",
		"DE": "Kokosinseln (Keelinginseln)",
		"NB_NO": "Kokosøyene",
		"FR": "Cocos (Îles)",
		"areaCode": "+61"
	},
	{
		"code": "KM",
		"ZH_CN": "科摩罗",
		"ZH_TW": "科摩羅",
		"EN": "Comoros",
		"KO": "코모로",
		"AR": "جزر القمر",
		"IT": "Comore",
		"ES": "Comoras",
		"DE": "Komoren",
		"NB_NO": "Komorene",
		"FR": "Comores",
		"areaCode": "+269"
	},
	{
		"code": "CG",
		"ZH_CN": "刚果（布）",
		"ZH_TW": "剛果（布）",
		"EN": "Congo (Republic of the)",
		"KO": "콩고 공화국",
		"AR": "جمهورية الكونغو",
		"IT": "Congo, Repubblica del",
		"ES": "República del Congo",
		"DE": "Republik Kongo",
		"NB_NO": "Kongo-Brazzaville",
		"FR": "République du Congo",
		"areaCode": "+242"
	},
	{
		"code": "CR",
		"ZH_CN": "哥斯达黎加",
		"ZH_TW": "哥斯達黎加",
		"EN": "Costa Rica",
		"KO": "코스타리카",
		"AR": "كوستا ريكا",
		"IT": "Costa Rica",
		"ES": "Costa Rica",
		"DE": "Costa Rica",
		"NB_NO": "Costa Rica",
		"FR": "Costa Rica",
		"areaCode": "+506"
	},
	{
		"code": "HR",
		"ZH_CN": "克罗地亚",
		"ZH_TW": "克羅地亞",
		"EN": "Croatia",
		"KO": "크로아티아",
		"AR": "كرواتيا",
		"IT": "Croazia",
		"ES": "Croacia",
		"DE": "Kroatien",
		"NB_NO": "Kroatia",
		"FR": "Croatie",
		"areaCode": "+385"
	},
	{
		"code": "CY",
		"ZH_CN": "塞浦路斯",
		"ZH_TW": "塞浦路斯",
		"EN": "Cyprus",
		"KO": "키프로스",
		"AR": "قبرص",
		"IT": "Cipro",
		"ES": "Chipre",
		"DE": "Zypern",
		"NB_NO": "Kypros",
		"FR": "Chypre",
		"areaCode": "+357"
	},
	{
		"code": "DK",
		"ZH_CN": "丹麦",
		"ZH_TW": "丹麥",
		"EN": "Denmark",
		"KO": "덴마크",
		"AR": "الدنمارك",
		"IT": "Danimarca",
		"ES": "Dinamarca",
		"DE": "Dänemark",
		"NB_NO": "Danmark",
		"FR": "Danemark",
		"areaCode": "+45"
	},
	{
		"code": "DM",
		"ZH_CN": "多米尼克",
		"ZH_TW": "多米尼克",
		"EN": "Dominica",
		"KO": "도미니카",
		"AR": "دومينيكا",
		"IT": "Dominica",
		"ES": "Dominica",
		"DE": "Dominica",
		"NB_NO": "Dominica",
		"FR": "Dominique",
		"areaCode": "+1767"
	},
	{
		"code": "EC",
		"ZH_CN": "厄瓜多尔",
		"ZH_TW": "厄瓜多爾",
		"EN": "Ecuador",
		"KO": "에콰도르",
		"AR": "الإكوادور",
		"IT": "Ecuador",
		"ES": "Ecuador",
		"DE": "Ecuador",
		"NB_NO": "Ecuador",
		"FR": "Équateur",
		"areaCode": "+593"
	},
	{
		"code": "SV",
		"ZH_CN": "萨尔瓦多",
		"ZH_TW": "薩爾瓦多",
		"EN": "El Salvador",
		"KO": "엘살바도르",
		"AR": "السلفادور",
		"IT": "El Salvador",
		"ES": "El Salvador",
		"DE": "El Salvador",
		"NB_NO": "El Salvador",
		"FR": "Salvador",
		"areaCode": "+503"
	},
	{
		"code": "ER",
		"ZH_CN": "厄立特里亚",
		"ZH_TW": "厄立特裏亞",
		"EN": "Eritrea",
		"KO": "에리트레아",
		"AR": "إريتريا",
		"IT": "Eritrea",
		"ES": "Eritrea",
		"DE": "Eritrea",
		"NB_NO": "Eritrea",
		"FR": "Érythrée",
		"areaCode": "+291"
	},
	{
		"code": "ET",
		"ZH_CN": "埃塞俄比亚",
		"ZH_TW": "埃塞俄比亞",
		"EN": "Ethiopia",
		"KO": "에티오피아",
		"AR": "أثيوبيا",
		"IT": "Etiopia",
		"ES": "Etiopía",
		"DE": "Äthiopien",
		"NB_NO": "Etiopia",
		"FR": "Éthiopie",
		"areaCode": "+251"
	},
	{
		"code": "FK",
		"ZH_CN": "福克兰群岛（马尔维纳斯）",
		"ZH_TW": "福克蘭群島（馬爾維納斯）",
		"EN": "Falkland Islands",
		"KO": "포클랜드 제도",
		"AR": "جزر فوكلاند",
		"IT": "Falkland, Isole",
		"ES": "Islas Malvinas",
		"DE": "Falklandinseln",
		"NB_NO": "Falklandsøyene",
		"FR": "Malouines (Îles)",
		"areaCode": "+500"
	},
	{
		"code": "FJ",
		"ZH_CN": "斐济",
		"ZH_TW": "斐濟",
		"EN": "Fiji",
		"KO": "피지",
		"AR": "فيجي",
		"IT": "Fiji",
		"ES": "Fiyi",
		"DE": "Fidschi",
		"NB_NO": "Fiji",
		"FR": "Fidji",
		"areaCode": "+679"
	},
	{
		"code": "FR",
		"ZH_CN": "法国",
		"ZH_TW": "法國",
		"EN": "France",
		"KO": "프랑스",
		"AR": "فرنسا",
		"IT": "Francia",
		"ES": "Francia",
		"DE": "Frankreich",
		"NB_NO": "Frankrike",
		"FR": "France",
		"areaCode": "+33"
	},
	{
		"code": "PF",
		"ZH_CN": "法属波利尼西亚",
		"ZH_TW": "法屬波利尼西亞",
		"EN": "French Polynesia",
		"KO": "프랑스 령 폴리네시아의",
		"AR": "بولينيزيا الفرنسية",
		"IT": "Polinesia francese",
		"ES": "Polinesia Francesa",
		"DE": "Französisch-Polynesien",
		"NB_NO": "Fransk Polynesia",
		"FR": "Polynésie française",
		"areaCode": "+689"
	},
	{
		"code": "GA",
		"ZH_CN": "加蓬",
		"ZH_TW": "加蓬",
		"EN": "Gabon",
		"KO": "가봉",
		"AR": "الغابون",
		"IT": "Gabon",
		"ES": "Gabón",
		"DE": "Gabun",
		"NB_NO": "Gabon",
		"FR": "Gabon",
		"areaCode": "+241"
	},
	{
		"code": "DE",
		"ZH_CN": "德国",
		"ZH_TW": "德國",
		"EN": "Germany",
		"KO": "독일",
		"AR": "ألمانيا",
		"IT": "Germania",
		"ES": "Alemania",
		"DE": "Deutschland",
		"NB_NO": "Tyskland",
		"FR": "Allemagne",
		"areaCode": "+49"
	},
	{
		"code": "GI",
		"ZH_CN": "直布罗陀",
		"ZH_TW": "直布羅陀",
		"EN": "Gibraltar",
		"KO": "지브롤터",
		"AR": "جبل طارق",
		"IT": "Gibilterra",
		"ES": "Gibraltar",
		"DE": "Gibraltar",
		"NB_NO": "Gibraltar",
		"FR": "Gibraltar",
		"areaCode": "+350"
	},
	{
		"code": "GL",
		"ZH_CN": "格陵兰",
		"ZH_TW": "格陵蘭",
		"EN": "Greenland",
		"KO": "그린란드",
		"AR": "الأرض الخضراء",
		"IT": "Groenlandia",
		"ES": "Groenlandia",
		"DE": "Grönland",
		"NB_NO": "Grønland",
		"FR": "Groenland",
		"areaCode": "+299"
	},
	{
		"code": "GP",
		"ZH_CN": "瓜德罗普",
		"ZH_TW": "瓜德羅普",
		"EN": "Guadeloupe",
		"KO": "과델루프",
		"AR": "جوادلوب",
		"IT": "Guadalupa",
		"ES": "Guadalupe",
		"DE": "Guadeloupe",
		"NB_NO": "Guadeloupe",
		"FR": "Guadeloupe",
		"areaCode": "+590"
	},
	{
		"code": "GT",
		"ZH_CN": "危地马拉",
		"ZH_TW": "危地馬拉",
		"EN": "Guatemala",
		"KO": "과테말라",
		"AR": "غواتيمالا",
		"IT": "Guatemala",
		"ES": "Guatemala",
		"DE": "Guatemala",
		"NB_NO": "Guatemala",
		"FR": "Guatemala",
		"areaCode": "+502"
	},
	{
		"code": "GN",
		"ZH_CN": "几内亚",
		"ZH_TW": "幾內亞",
		"EN": "Guinea",
		"KO": "기니",
		"AR": "غينيا",
		"IT": "Guinea",
		"ES": "Guinea",
		"DE": "Guinea",
		"NB_NO": "Guinea",
		"FR": "Guinée",
		"areaCode": "+224"
	},
	{
		"code": "GY",
		"ZH_CN": "圭亚那",
		"ZH_TW": "圭亞那",
		"EN": "Guyana",
		"KO": "가이아나",
		"AR": "غيانا",
		"IT": "Guyana",
		"ES": "Guyana",
		"DE": "Guyana",
		"NB_NO": "Guyana",
		"FR": "Guyana",
		"areaCode": "+592"
	},
	{
		"code": "HM",
		"ZH_CN": "赫德岛和麦克唐纳岛",
		"ZH_TW": "赫德島和麥克唐納島",
		"EN": "Heard Island and McDonald Islands",
		"KO": "허드 섬과 맥도널드 제도",
		"AR": "قلب الجزيرة وجزر ماكدونالز",
		"IT": "Heard e McDonald, Isole",
		"ES": "Islas Heard y McDonald",
		"DE": "Heard und McDonaldinseln",
		"NB_NO": "Norfolkøya",
		"FR": "Îles Heard et McDonald",
		"areaCode": "+672"
	},
	{
		"code": "HN",
		"ZH_CN": "洪都拉斯",
		"ZH_TW": "洪都拉斯",
		"EN": "Honduras",
		"KO": "온두라스",
		"AR": "هندوراس",
		"IT": "Honduras",
		"ES": "Honduras",
		"DE": "Honduras",
		"NB_NO": "Honduras",
		"FR": "Honduras",
		"areaCode": "+504"
	},
	{
		"code": "HU",
		"ZH_CN": "匈牙利",
		"ZH_TW": "匈牙利",
		"EN": "Hungary",
		"KO": "헝가리",
		"AR": "اليونان",
		"IT": "Ungheria",
		"ES": "Hungría",
		"DE": "Ungarn",
		"NB_NO": "Ungarn",
		"FR": "Hongrie",
		"areaCode": "+36"
	},
	{
		"code": "IR",
		"ZH_CN": "伊朗",
		"ZH_TW": "伊朗",
		"EN": "Iran",
		"KO": "이란",
		"AR": "إيران",
		"IT": "Iran",
		"ES": "Irán",
		"DE": "Iran",
		"NB_NO": "Iran",
		"FR": "Iran",
		"areaCode": "+98"
	},
	{
		"code": "IE",
		"ZH_CN": "爱尔兰",
		"ZH_TW": "愛爾蘭",
		"EN": "Ireland",
		"KO": "아일랜드",
		"AR": "أيرلندا",
		"IT": "Irlanda",
		"ES": "Irlanda",
		"DE": "Irland",
		"NB_NO": "Irland",
		"FR": "Irlande",
		"areaCode": "+353"
	},
	{
		"code": "IT",
		"ZH_CN": "意大利",
		"ZH_TW": "意大利",
		"EN": "Italy",
		"KO": "이탈리아",
		"AR": "إيطاليا",
		"IT": "Italia",
		"ES": "Italia",
		"DE": "Italien",
		"NB_NO": "Italia",
		"FR": "Italie",
		"areaCode": "+39"
	},
	{
		"code": "JP",
		"ZH_CN": "日本",
		"ZH_TW": "日本",
		"EN": "Japan",
		"KO": "일본",
		"AR": "اليابان",
		"IT": "Giappone",
		"ES": "Japón",
		"DE": "Japan",
		"NB_NO": "Japan",
		"FR": "Japon",
		"areaCode": "+81"
	},
	{
		"code": "JO",
		"ZH_CN": "约旦",
		"ZH_TW": "約旦",
		"EN": "Jordan",
		"KO": "요르단",
		"AR": "الأردن",
		"IT": "Giordania",
		"ES": "Jordania",
		"DE": "Jordanien",
		"NB_NO": "Jordan",
		"FR": "Jordanie",
		"areaCode": "+962"
	},
	{
		"code": "KE",
		"ZH_CN": "肯尼亚",
		"ZH_TW": "肯尼亞",
		"EN": "Kenya",
		"KO": "케냐",
		"AR": "كينيا",
		"IT": "Kenya",
		"ES": "Kenia",
		"DE": "Kenia",
		"NB_NO": "Kenya",
		"FR": "Kenya",
		"areaCode": "+254"
	},
	{
		"code": "KP",
		"ZH_CN": "朝鲜",
		"ZH_TW": "朝鮮",
		"EN": "Korea (Democratic People's Republic of)",
		"KO": "북한",
		"AR": "كوريا الشمالية",
		"IT": "Corea del Nord",
		"ES": "Corea del Norte",
		"DE": "Nordkorea",
		"NB_NO": "Nord-Korea",
		"FR": "Corée du Nord",
		"areaCode": "+850"
	},
	{
		"code": "KW",
		"ZH_CN": "科威特",
		"ZH_TW": "科威特",
		"EN": "Kuwait",
		"KO": "쿠웨이트",
		"AR": "الكويت",
		"IT": "Kuwait",
		"ES": "Kuwait",
		"DE": "Kuwait",
		"NB_NO": "Kuwait",
		"FR": "Koweït",
		"areaCode": "+965"
	},
	{
		"code": "LA",
		"ZH_CN": "老挝",
		"ZH_TW": "老撾",
		"EN": "Laos",
		"KO": "라오스",
		"AR": "لاوس",
		"IT": "Laos",
		"ES": "Laos",
		"DE": "Laos",
		"NB_NO": "Laos",
		"FR": "Laos",
		"areaCode": "+856"
	},
	{
		"code": "LB",
		"ZH_CN": "黎巴嫩",
		"ZH_TW": "黎巴嫩",
		"EN": "Lebanon",
		"KO": "레바논",
		"AR": "لبنان",
		"IT": "Libano",
		"ES": "Líbano",
		"DE": "Libanon",
		"NB_NO": "Libanon",
		"FR": "Liban",
		"areaCode": "+961"
	},
	{
		"code": "LR",
		"ZH_CN": "利比里亚",
		"ZH_TW": "利比裏亞",
		"EN": "Liberia",
		"KO": "라이베리아",
		"AR": "ليبيريا",
		"IT": "Liberia",
		"ES": "Liberia",
		"DE": "Liberia",
		"NB_NO": "Liberia",
		"FR": "Libéria",
		"areaCode": "+231"
	},
	{
		"code": "LI",
		"ZH_CN": "列支敦士登",
		"ZH_TW": "列支敦士登",
		"EN": "Liechtenstein",
		"KO": "리히텐슈타인",
		"AR": "ليختنشتاين",
		"IT": "Liechtenstein",
		"ES": "Liechtenstein",
		"DE": "Liechtenstein",
		"NB_NO": "Liechtenstein",
		"FR": "Liechtenstein",
		"areaCode": "+423"
	},
	{
		"code": "LU",
		"ZH_CN": "卢森堡",
		"ZH_TW": "盧森堡",
		"EN": "Luxembourg",
		"KO": "룩셈부르크",
		"AR": "لوكسمبورغ",
		"IT": "Lussemburgo",
		"ES": "Luxemburgo",
		"DE": "Luxemburg",
		"NB_NO": "Luxembourg",
		"FR": "Luxembourg",
		"areaCode": "+352"
	},
	{
		"code": "MK",
		"ZH_CN": "前南马其顿",
		"ZH_TW": "前南馬其頓",
		"EN": "North Macedonia",
		"KO": "마케도니아",
		"AR": "مقدونيا",
		"IT": "Macedonia del Nord",
		"ES": "Macedonia del Norte",
		"DE": "Nordmazedonien",
		"NB_NO": "Makedonia",
		"FR": "Macédoine du Nord",
		"areaCode": "+389"
	},
	{
		"code": "MW",
		"ZH_CN": "马拉维",
		"ZH_TW": "馬拉維",
		"EN": "Malawi",
		"KO": "말라위",
		"AR": "مالاوي",
		"IT": "Malawi",
		"ES": "Malaui",
		"DE": "Malawi",
		"NB_NO": "Malawi",
		"FR": "Malawi",
		"areaCode": "+265"
	},
	{
		"code": "MV",
		"ZH_CN": "马尔代夫",
		"ZH_TW": "馬爾代夫",
		"EN": "Maldives",
		"KO": "몰디브",
		"AR": "جزر المالديف",
		"IT": "Maldive",
		"ES": "Maldivas",
		"DE": "Malediven",
		"NB_NO": "Maldivene",
		"FR": "Maldives",
		"areaCode": "+960"
	},
	{
		"code": "MT",
		"ZH_CN": "马耳他",
		"ZH_TW": "馬耳他",
		"EN": "Malta",
		"KO": "몰타",
		"AR": "مالطا",
		"IT": "Malta",
		"ES": "Malta",
		"DE": "Malta",
		"NB_NO": "Malta",
		"FR": "Malte",
		"areaCode": "+356"
	},
	{
		"code": "MH",
		"ZH_CN": "马绍尔群岛",
		"ZH_TW": "馬紹爾群島",
		"EN": "Marshall Islands",
		"KO": "마샬 군도",
		"AR": "جزر مارشال",
		"IT": "Marshall, Isole",
		"ES": "Islas Marshall",
		"DE": "Marshallinseln",
		"NB_NO": "Marshalløyene",
		"FR": "Marshall (Îles)",
		"areaCode": "+692"
	},
	{
		"code": "MR",
		"ZH_CN": "毛里塔尼亚",
		"ZH_TW": "毛裏塔尼亞",
		"EN": "Mauritania",
		"KO": "모리타니",
		"AR": "موريتانيا",
		"IT": "Mauritania",
		"ES": "Mauritania",
		"DE": "Mauretanien",
		"NB_NO": "Mauritania",
		"FR": "Mauritanie",
		"areaCode": "+222"
	},
	{
		"code": "YT",
		"ZH_CN": "马约特",
		"ZH_TW": "馬約特",
		"EN": "Mayotte",
		"KO": "마요테",
		"AR": "مايوت",
		"IT": "Maiotta",
		"ES": "Mayotte",
		"DE": "Mayotte",
		"NB_NO": "Mayotte",
		"FR": "Mayotte",
		"areaCode": "+262"
	},
	{
		"code": "FM",
		"ZH_CN": "密克罗尼西亚",
		"ZH_TW": "密克羅尼西亞",
		"EN": "Micronesia",
		"KO": "미크로네시아",
		"AR": "ميكرونيزيا",
		"IT": "Micronesia",
		"ES": "Micronesia",
		"DE": "Mikronesien",
		"NB_NO": "Mikronesiaføderasjonen",
		"FR": "Micronésie",
		"areaCode": "+691"
	},
	{
		"code": "MC",
		"ZH_CN": "摩纳哥",
		"ZH_TW": "摩納哥",
		"EN": "Monaco",
		"KO": "모나코",
		"AR": "موناكو",
		"IT": "Monaco, Principato di",
		"ES": "Mónaco",
		"DE": "Monaco",
		"NB_NO": "Monaco",
		"FR": "Monaco (Principauté de)",
		"areaCode": "+377"
	},
	{
		"code": "MS",
		"ZH_CN": "蒙特塞拉特",
		"ZH_TW": "蒙特塞拉特",
		"EN": "Montserrat",
		"KO": "몽세라트",
		"AR": "مونتسيرات",
		"IT": "Montserrat",
		"ES": "Montserrat",
		"DE": "Montserrat",
		"NB_NO": "Montserrat",
		"FR": "Montserrat",
		"areaCode": "+1664"
	},
	{
		"code": "MZ",
		"ZH_CN": "莫桑比克",
		"ZH_TW": "莫桑比克",
		"EN": "Mozambique",
		"KO": "모잠비크",
		"AR": "موزمبيق",
		"IT": "Mozambico",
		"ES": "Mozambique",
		"DE": "Mosambik",
		"NB_NO": "Mosambik",
		"FR": "Mozambique",
		"areaCode": "+258"
	},
	{
		"code": "NR",
		"ZH_CN": "瑙鲁",
		"ZH_TW": "瑙魯",
		"EN": "Nauru",
		"KO": "나우루",
		"AR": "ناورو",
		"IT": "Nauru",
		"ES": "Nauru",
		"DE": "Nauru",
		"NB_NO": "Nauru",
		"FR": "Nauru",
		"areaCode": "+674"
	},
	{
		"code": "NL",
		"ZH_CN": "荷兰",
		"ZH_TW": "荷蘭",
		"EN": "Netherlands",
		"KO": "네덜란드",
		"AR": "هولندا",
		"IT": "Paesi Bassi",
		"ES": "Países Bajos",
		"DE": "Niederlande",
		"NB_NO": "Nederland",
		"FR": "Pays-Bas",
		"areaCode": "+31"
	},
	{
		"code": "NC",
		"ZH_CN": "新喀里多尼亚",
		"ZH_TW": "新喀裏多尼亞",
		"EN": "New Caledonia",
		"KO": "뉴 칼레도니아",
		"AR": "كاليدونيا الجديدة",
		"IT": "Nuova Caledonia",
		"ES": "Nueva Caledonia",
		"DE": "Neukaledonien",
		"NB_NO": "Ny-Caledonia",
		"FR": "Nouvelle-Calédonie",
		"areaCode": "+687"
	},
	{
		"code": "NI",
		"ZH_CN": "尼加拉瓜",
		"ZH_TW": "尼加拉瓜",
		"EN": "Nicaragua",
		"KO": "니카라과",
		"AR": "NICARAGUA",
		"IT": "Nicaragua",
		"ES": "Nicaragua",
		"DE": "Nicaragua",
		"NB_NO": "Nicaragua",
		"FR": "Nicaragua",
		"areaCode": "+505"
	},
	{
		"code": "NG",
		"ZH_CN": "尼日利亚",
		"ZH_TW": "尼日利亞",
		"EN": "Nigeria",
		"KO": "나이지리아",
		"AR": "نيجيريا",
		"IT": "Nigeria",
		"ES": "Nigeria",
		"DE": "Nigeria",
		"NB_NO": "Nigeria",
		"FR": "Nigéria",
		"areaCode": "+234"
	},
	{
		"code": "NF",
		"ZH_CN": "诺福克岛",
		"ZH_TW": "諾福克島",
		"EN": "Norfolk Island",
		"KO": "노퍽 섬",
		"AR": "جزيرة نورفولك",
		"IT": "Norfolk, Isola",
		"ES": "Isla Norfolk",
		"DE": "Norfolkinsel",
		"NB_NO": "Norfolkøya",
		"FR": "Norfolk (Île)",
		"areaCode": "+672"
	},
	{
		"code": "NO",
		"ZH_CN": "挪威",
		"ZH_TW": "挪威",
		"EN": "Norway",
		"KO": "노르웨이",
		"AR": "النرويج",
		"IT": "Norvegia",
		"ES": "Noruega",
		"DE": "Norwegen",
		"NB_NO": "Norge",
		"FR": "Norvège",
		"areaCode": "+47"
	},
	{
		"code": "PK",
		"ZH_CN": "巴基斯坦",
		"ZH_TW": "巴基斯坦",
		"EN": "Pakistan",
		"KO": "파키스탄",
		"AR": "باكستان",
		"IT": "Pakistan",
		"ES": "Pakistán",
		"DE": "Pakistan",
		"NB_NO": "Pakistan",
		"FR": "Pakistan",
		"areaCode": "+92"
	},
	{
		"code": "PA",
		"ZH_CN": "巴拿马",
		"ZH_TW": "巴拿馬",
		"EN": "Panama",
		"KO": "파나마",
		"AR": "بناما",
		"IT": "Panama",
		"ES": "Panamá",
		"DE": "Panama",
		"NB_NO": "Panama",
		"FR": "Panama",
		"areaCode": "+507"
	},
	{
		"code": "PY",
		"ZH_CN": "巴拉圭",
		"ZH_TW": "巴拉圭",
		"EN": "Paraguay",
		"KO": "파라과이",
		"AR": "باراغواي",
		"IT": "Paraguay",
		"ES": "Paraguay",
		"DE": "Paraguay",
		"NB_NO": "Paraguay",
		"FR": "Paraguay",
		"areaCode": "+595"
	},
	{
		"code": "PL",
		"ZH_CN": "波兰",
		"ZH_TW": "波蘭",
		"EN": "Poland",
		"KO": "폴란드",
		"AR": "بولندا",
		"IT": "Polonia",
		"ES": "Polonia",
		"DE": "Polen",
		"NB_NO": "Polen",
		"FR": "Pologne",
		"areaCode": "+48"
	},
	{
		"code": "PR",
		"ZH_CN": "波多黎各",
		"ZH_TW": "波多黎各",
		"EN": "Puerto Rico",
		"KO": "푸에르토 리코",
		"AR": "بورتوريكو",
		"IT": "Portorico",
		"ES": "Puerto Rico",
		"DE": "Puerto Rico",
		"NB_NO": "Puerto Rico",
		"FR": "Porto Rico",
		"areaCode": "+1787"
	},
	{
		"code": "QA",
		"ZH_CN": "卡塔尔",
		"ZH_TW": "卡塔爾",
		"EN": "Qatar",
		"KO": "카타르",
		"AR": "دولة قطر",
		"IT": "Qatar",
		"ES": "Qatar",
		"DE": "Katar",
		"NB_NO": "Qatar",
		"FR": "Qatar",
		"areaCode": "+974"
	},
	{
		"code": "RO",
		"ZH_CN": "罗马尼亚",
		"ZH_TW": "羅馬尼亞",
		"EN": "Romania",
		"KO": "루마니아",
		"AR": "رومانيا",
		"IT": "Romania",
		"ES": "Rumanía",
		"DE": "Rumänien",
		"NB_NO": "Romania",
		"FR": "Roumanie",
		"areaCode": "+40"
	},
	{
		"code": "RW",
		"ZH_CN": "卢旺达",
		"ZH_TW": "盧旺達",
		"EN": "Rwanda",
		"KO": "르완다",
		"AR": "رواندا",
		"IT": "Ruanda",
		"ES": "Ruanda",
		"DE": "Ruanda",
		"NB_NO": "Rwanda",
		"FR": "Rwanda",
		"areaCode": "+250"
	},
	{
		"code": "KN",
		"ZH_CN": "圣基茨和尼维斯",
		"ZH_TW": "聖基茨和尼維斯",
		"EN": "Saint Kitts and Nevis",
		"KO": "세인트키츠 네비스",
		"AR": "سانت كيتس ونيفيس",
		"IT": "Saint Kitts e Nevis",
		"ES": "San Cristóbal y Nieves",
		"DE": "St. Kitts und Nevis",
		"NB_NO": "Saint Kitts og Nevis",
		"FR": "Saint-Christophe-et-Niévès",
		"areaCode": "+1869"
	},
	{
		"code": "PM",
		"ZH_CN": "圣皮埃尔和密克隆",
		"ZH_TW": "聖皮埃爾和密克隆",
		"EN": "Saint Pierre and Miquelon",
		"KO": "생피에르 미켈론",
		"AR": "سانت بيير وميكلون",
		"IT": "Saint-Pierre e Miquelon",
		"ES": "San Pedro y Miquelón",
		"DE": "Saint-Pierre und Miquelon",
		"NB_NO": "St. Pierre og Miquelon",
		"FR": "Saint-Pierre-et-Miquelon",
		"areaCode": "+508"
	},
	{
		"code": "WS",
		"ZH_CN": "萨摩亚",
		"ZH_TW": "薩摩亞",
		"EN": "Samoa",
		"KO": "사모아",
		"AR": "ساموا",
		"IT": "Samoa",
		"ES": "Samoa",
		"DE": "Samoa",
		"NB_NO": "Samoa",
		"FR": "Samoa",
		"areaCode": "+685"
	},
	{
		"code": "ST",
		"ZH_CN": "圣多美和普林西比",
		"ZH_TW": "聖多美和普林西比",
		"EN": "Sao Tome and Principe",
		"KO": "상투 메 프린시 페",
		"AR": "ساو تومي وبرينسيبي",
		"IT": "São Tomé e Príncipe",
		"ES": "Santo Tomé y Príncipe",
		"DE": "São Tomé und Príncipe",
		"NB_NO": "São Tomé og Príncipe",
		"FR": "Sao Tomé-et-Principe",
		"areaCode": "+239"
	},
	{
		"code": "SN",
		"ZH_CN": "塞内加尔",
		"ZH_TW": "塞內加爾",
		"EN": "Senegal",
		"KO": "세네갈",
		"AR": "السنغال",
		"IT": "Senegal",
		"ES": "Senegal",
		"DE": "Senegal",
		"NB_NO": "Senegal",
		"FR": "Sénégal",
		"areaCode": "+221"
	},
	{
		"code": "SC",
		"ZH_CN": "塞舌尔",
		"ZH_TW": "塞舌爾",
		"EN": "Seychelles",
		"KO": "세이셸",
		"AR": "سيشيل",
		"IT": "Seychelles",
		"ES": "Seychelles",
		"DE": "Seychellen",
		"NB_NO": "Seychellene",
		"FR": "Seychelles",
		"areaCode": "+248"
	},
	{
		"code": "SI",
		"ZH_CN": "斯洛文尼亚",
		"ZH_TW": "斯洛文尼亞",
		"EN": "Slovenia",
		"KO": "슬로베니아",
		"AR": "سلوفينيا",
		"IT": "Slovenia",
		"ES": "Eslovenia",
		"DE": "Slowenien",
		"NB_NO": "Slovenia",
		"FR": "Slovénie",
		"areaCode": "+386"
	},
	{
		"code": "SO",
		"ZH_CN": "索马里",
		"ZH_TW": "索馬裏",
		"EN": "Somalia",
		"KO": "소말리아",
		"AR": "الصومال",
		"IT": "Somalia",
		"ES": "Somalia",
		"DE": "Somalia",
		"NB_NO": "Somalia",
		"FR": "Somalie",
		"areaCode": "+252"
	},
	{
		"code": "GS",
		"ZH_CN": "南乔治亚岛和南桑德韦奇岛",
		"ZH_TW": "南喬治亞島和南桑德韋奇島",
		"EN": "South Georgia and the South Sandwich Islands",
		"KO": "사우스 조지아 및 사우스 샌드위치 제도",
		"AR": "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
		"IT": "Georgia del Sud e Isole Sandwich Meridionali ",
		"ES": "Islas Georgias del Sur y Sandwich del Sur",
		"DE": "Südgeorgien und die Südlichen Sandwichinseln",
		"NB_NO": "Sør-Georgia og de sørlige Sandwich-øyene",
		"FR": "Îles Géorgie du Sud et Sandwich du Sud",
		"areaCode": "+500"
	},
	{
		"code": "LK",
		"ZH_CN": "斯里兰卡",
		"ZH_TW": "斯裏蘭卡",
		"EN": "Sri Lanka",
		"KO": "스리랑카",
		"AR": "سيريلانكا",
		"IT": "Sri Lanka",
		"ES": "Sri Lanka",
		"DE": "Sri Lanka",
		"NB_NO": "Sri Lanka",
		"FR": "Sri Lanka",
		"areaCode": "+94"
	},
	{
		"code": "SR",
		"ZH_CN": "苏里南",
		"ZH_TW": "蘇裏南",
		"EN": "Suriname",
		"KO": "수리남",
		"AR": "سورينام",
		"IT": "Suriname",
		"ES": "Surinam",
		"DE": "Suriname",
		"NB_NO": "Surinam",
		"FR": "Suriname",
		"areaCode": "+597"
	},
	{
		"code": "SZ",
		"ZH_CN": "斯威士兰",
		"ZH_TW": "斯威士蘭",
		"EN": "Eswatini",
		"KO": "스와질란드",
		"AR": "سوازيلاند",
		"IT": "eSwatini",
		"ES": "Suazilandia",
		"DE": "Eswatini",
		"NB_NO": "Swaziland",
		"FR": "Eswatini",
		"areaCode": "+268"
	},
	{
		"code": "CH",
		"ZH_CN": "瑞士",
		"ZH_TW": "瑞士",
		"EN": "Switzerland",
		"KO": "스위스",
		"AR": "سويسرا",
		"IT": "Svizzera",
		"ES": "Suiza",
		"DE": "Schweiz",
		"NB_NO": "Sveits",
		"FR": "Suisse",
		"areaCode": "+41"
	},
	{
		"code": "TZ",
		"ZH_CN": "坦桑尼亚",
		"ZH_TW": "坦桑尼亞",
		"EN": "Tanzania",
		"KO": "탄자니아",
		"AR": "تنزانيا",
		"IT": "Tanzania",
		"ES": "Tanzania",
		"DE": "Tansania",
		"NB_NO": "Tanzania",
		"FR": "Tanzanie",
		"areaCode": "+255"
	},
	{
		"code": "BS",
		"ZH_CN": "巴哈马",
		"ZH_TW": "巴哈馬",
		"EN": "Bahamas",
		"KO": "바하마",
		"AR": "الباهاما",
		"IT": "Bahamas",
		"ES": "Bahamas",
		"DE": "Bahamas",
		"NB_NO": "Bahamas",
		"FR": "Bahamas",
		"areaCode": "+1242"
	},
	{
		"code": "TG",
		"ZH_CN": "多哥",
		"ZH_TW": "多哥",
		"EN": "Togo",
		"KO": "가다",
		"AR": "ليذهب",
		"IT": "Togo",
		"ES": "Togo",
		"DE": "Togo",
		"NB_NO": "Togo",
		"FR": "Togo",
		"areaCode": "+228"
	},
	{
		"code": "TO",
		"ZH_CN": "汤加",
		"ZH_TW": "湯加",
		"EN": "Tonga",
		"KO": "통가",
		"AR": "تونغا",
		"IT": "Tonga",
		"ES": "Tonga",
		"DE": "Tonga",
		"NB_NO": "Tonga",
		"FR": "Tonga",
		"areaCode": "+676"
	},
	{
		"code": "TN",
		"ZH_CN": "突尼斯",
		"ZH_TW": "突尼斯",
		"EN": "Tunisia",
		"KO": "튀니지",
		"AR": "تونس",
		"IT": "Tunisia",
		"ES": "Túnez",
		"DE": "Tunesien",
		"NB_NO": "Tunisia",
		"FR": "Tunisie",
		"areaCode": "+216"
	},
	{
		"code": "TM",
		"ZH_CN": "土库曼斯坦",
		"ZH_TW": "土庫曼斯坦",
		"EN": "Turkmenistan",
		"KO": "투르크 메니스탄",
		"AR": "تركمانستان",
		"IT": "Turkmenistan",
		"ES": "Turkmenistán",
		"DE": "Turkmenistan",
		"NB_NO": "Turkmenistan",
		"FR": "Turkménistan",
		"areaCode": "+993"
	},
	{
		"code": "TV",
		"ZH_CN": "图瓦卢",
		"ZH_TW": "圖瓦盧",
		"EN": "Tuvalu",
		"KO": "투발루",
		"AR": "توفالو",
		"IT": "Tuvalu",
		"ES": "Tuvalu",
		"DE": "Tuvalu",
		"NB_NO": "Tuvalu",
		"FR": "Tuvalu",
		"areaCode": "+688"
	},
	{
		"code": "UA",
		"ZH_CN": "乌克兰",
		"ZH_TW": "烏克蘭",
		"EN": "Ukraine",
		"KO": "우크라이나",
		"AR": "أوكرانيا",
		"IT": "Ucraina",
		"ES": "Ucrania",
		"DE": "Ukraine",
		"NB_NO": "Ukraina",
		"FR": "Ukraine",
		"areaCode": "+380"
	},
	{
		"code": "GB",
		"ZH_CN": "英国",
		"ZH_TW": "英國",
		"EN": "United Kingdom",
		"KO": "영국",
		"AR": " بريطانيا",
		"IT": "Regno Unito",
		"ES": "Reino Unido",
		"DE": "Vereinigtes Königreich",
		"NB_NO": "Storbritannia",
		"FR": "Royaume-Uni",
		"areaCode": "+44"
	},
	{
		"code": "UY",
		"ZH_CN": "乌拉圭",
		"ZH_TW": "烏拉圭",
		"EN": "Uruguay",
		"KO": "우루과이",
		"AR": "أوروغواي",
		"IT": "Uruguay",
		"ES": "Uruguay",
		"DE": "Uruguay",
		"NB_NO": "Uruguay",
		"FR": "Uruguay",
		"areaCode": "+598"
	},
	{
		"code": "VU",
		"ZH_CN": "瓦努阿图",
		"ZH_TW": "瓦努阿圖",
		"EN": "Vanuatu",
		"KO": "바누아투",
		"AR": "فانواتو",
		"IT": "Vanuatu",
		"ES": "Vanuatu",
		"DE": "Vanuatu",
		"NB_NO": "Vanuatu",
		"FR": "Vanuatu",
		"areaCode": "+678"
	},
	{
		"code": "WF",
		"ZH_CN": "瓦利斯和富图纳",
		"ZH_TW": "瓦利斯和富圖納",
		"EN": "Wallis and Futuna",
		"KO": "월리스 푸 투나 제도",
		"AR": "جزر واليس وفوتونا",
		"IT": "Wallis e Futuna, Isole",
		"ES": "Wallis y Futuna",
		"DE": "Wallis und Futuna",
		"NB_NO": "Wallis og Futuna",
		"FR": "Wallis-et-Futuna",
		"areaCode": "+681"
	},
	{
		"code": "YE",
		"ZH_CN": "也门",
		"ZH_TW": "也門",
		"EN": "Yemen",
		"KO": "예멘 아랍 공화국",
		"AR": "اليمن",
		"IT": "Yemen",
		"ES": "Yemen",
		"DE": "Jemen",
		"NB_NO": "Jemen",
		"FR": "Yémen",
		"areaCode": "+967"
	},
	{
		"code": "PS",
		"ZH_CN": "巴勒斯坦",
		"ZH_TW": "巴勒斯坦",
		"EN": "Palestine",
		"KO": "팔레스타인 영토",
		"AR": "فلسطين",
		"IT": "Palestina",
		"ES": "Palestina",
		"DE": "Palästina",
		"NB_NO": "Palestinsk territorium",
		"FR": "Palestine",
		"areaCode": "+970"
	},
	{
		"code": "AL",
		"ZH_CN": "阿尔巴尼亚",
		"ZH_TW": "阿爾巴尼亞",
		"EN": "Albania",
		"KO": "알바니아",
		"AR": "ألبانيا",
		"IT": "Albania",
		"ES": "Albania",
		"DE": "Albanien",
		"NB_NO": "Albania",
		"FR": "Albanie",
		"areaCode": "+355"
	},
	{
		"code": "AS",
		"ZH_CN": "美属萨摩亚",
		"ZH_TW": "美屬薩摩亞",
		"EN": "American Samoa",
		"KO": "아메리칸 사모아",
		"AR": "ساموا الأمريكية",
		"IT": "Samoa americane",
		"ES": "Samoa Americana",
		"DE": "Samoa",
		"NB_NO": "Amerikansk Samoa",
		"FR": "Samoa américaines",
		"areaCode": "+1684"
	},
	{
		"code": "AO",
		"ZH_CN": "安哥拉",
		"ZH_TW": "安哥拉",
		"EN": "Angola",
		"KO": "앙골라",
		"AR": "أنغولا",
		"IT": "Angola",
		"ES": "Angola",
		"DE": "Angola",
		"NB_NO": "Angola",
		"FR": "Angola",
		"areaCode": "+244"
	},
	{
		"code": "AQ",
		"ZH_CN": "南极洲",
		"ZH_TW": "南極洲",
		"EN": "Antarctica",
		"KO": "남극",
		"AR": "القارة القطبية الجنوبية",
		"IT": "Antartide",
		"ES": "Antártida",
		"DE": "Antarktis",
		"NB_NO": "Antarktis",
		"FR": "Antarctique",
		"areaCode": "+672"
	},
	{
		"code": "AR",
		"ZH_CN": "阿根廷",
		"ZH_TW": "阿根廷",
		"EN": "Argentina",
		"KO": "아르헨티나",
		"AR": "الأرجنتين",
		"IT": "Argentina",
		"ES": "Argentina",
		"DE": "Argentinien",
		"NB_NO": "Argentina",
		"FR": "Argentine",
		"areaCode": "+54"
	},
	{
		"code": "AW",
		"ZH_CN": "阿鲁巴",
		"ZH_TW": "阿魯巴",
		"EN": "Aruba",
		"KO": "아루바",
		"AR": "أروبا",
		"IT": "Aruba",
		"ES": "Aruba",
		"DE": "Aruba",
		"NB_NO": "Aruba",
		"FR": "Aruba",
		"areaCode": "+297"
	},
	{
		"code": "AT",
		"ZH_CN": "奥地利",
		"ZH_TW": "奧地利",
		"EN": "Austria",
		"KO": "오스트리아",
		"AR": "النمسا",
		"IT": "Austria",
		"ES": "Austria",
		"DE": "Österreich",
		"NB_NO": "Østerrike",
		"FR": "Autriche",
		"areaCode": "+43"
	},
	{
		"code": "BH",
		"ZH_CN": "巴林",
		"ZH_TW": "巴林",
		"EN": "Bahrain",
		"KO": "바레인",
		"AR": "البحرين",
		"IT": "Bahrain",
		"ES": "Bahréin",
		"DE": "Bahrain",
		"NB_NO": "Bahrain",
		"FR": "Bahreïn",
		"areaCode": "+973"
	},
	{
		"code": "BB",
		"ZH_CN": "巴巴多斯",
		"ZH_TW": "巴巴多斯",
		"EN": "Barbados",
		"KO": "바베이도스",
		"AR": "بربادوس",
		"IT": "Barbados",
		"ES": "Barbados",
		"DE": "Barbados",
		"NB_NO": "Barbados",
		"FR": "Barbade",
		"areaCode": "+1246"
	},
	{
		"code": "BE",
		"ZH_CN": "比利时",
		"ZH_TW": "比利時",
		"EN": "Belgium",
		"KO": "벨기에",
		"AR": "بلجيكا",
		"IT": "Belgio",
		"ES": "Bélgica",
		"DE": "Belgien",
		"NB_NO": "Belgia",
		"FR": "Belgique",
		"areaCode": "+32"
	},
	{
		"code": "BJ",
		"ZH_CN": "贝宁",
		"ZH_TW": "貝寧",
		"EN": "Benin",
		"KO": "베닌",
		"AR": "بنين",
		"IT": "Benin",
		"ES": "Benín",
		"DE": "Benin",
		"NB_NO": "Benin",
		"FR": "Bénin",
		"areaCode": "+229"
	},
	{
		"code": "BT",
		"ZH_CN": "不丹",
		"ZH_TW": "不丹",
		"EN": "Bhutan",
		"KO": "부탄",
		"AR": "بوتان",
		"IT": "Bhutan",
		"ES": "Bután",
		"DE": "Bhutan",
		"NB_NO": "Bhutan",
		"FR": "Bhoutan",
		"areaCode": "+975"
	},
	{
		"code": "BA",
		"ZH_CN": "波黑",
		"ZH_TW": "波黑",
		"EN": "Bosnia and Herzegovina",
		"KO": "보스니아 헤르체고비나",
		"AR": "البوسنة والهرسك",
		"IT": "Bosnia ed Erzegovina",
		"ES": "Bosnia-Herzegovina",
		"DE": "Bosnien und Herzegowina",
		"NB_NO": "Bosnia-Hercegovina",
		"FR": "Bosnie-Herzégovine",
		"areaCode": "+387"
	},
	{
		"code": "BV",
		"ZH_CN": "布维岛",
		"ZH_TW": "布維島",
		"EN": "Bouvet Island",
		"KO": "부베 섬",
		"AR": "جزيرة بوفيت",
		"IT": "Bouvet, Isola",
		"ES": "Isla Bouvet",
		"DE": "Bouvetinsel",
		"NB_NO": "Bouvetøya",
		"FR": "Île Bouvet",
		"areaCode": "+47"
	},
	{
		"code": "IO",
		"ZH_CN": "英属印度洋领地",
		"ZH_TW": "英屬印度洋領地",
		"EN": "British Indian Ocean Territory",
		"KO": "영국령 인도양 준주",
		"AR": "إقليم المحيط البريطاني الهندي",
		"IT": "Territorio britannico dell'Oceano Indiano",
		"ES": "Territorio Británico del Océano Índico",
		"DE": "Britisches Territorium im Indischen Ozean",
		"NB_NO": "Britiske territorier i Indiahavet",
		"FR": "Territoires britanniques de l'Océan Indien",
		"areaCode": "+246"
	},
	{
		"code": "BN",
		"ZH_CN": "文莱",
		"ZH_TW": "文萊",
		"EN": "Brunei",
		"KO": "브루나이",
		"AR": "بروناي",
		"IT": "Brunei",
		"ES": "Brunéi",
		"DE": "Brunei",
		"NB_NO": "Brunei Darussalam",
		"FR": "Brunei",
		"areaCode": "+673"
	},
	{
		"code": "BF",
		"ZH_CN": "布基纳法索",
		"ZH_TW": "布基納法索",
		"EN": "Burkina Faso",
		"KO": "부키 나 파소",
		"AR": "بوركينا فاسو",
		"IT": "Burkina Faso",
		"ES": "Burkina Faso",
		"DE": "Burkina Faso",
		"NB_NO": "Burkina Faso",
		"FR": "Burkina Faso",
		"areaCode": "+226"
	},
	{
		"code": "BI",
		"ZH_CN": "布隆迪",
		"ZH_TW": "布隆迪",
		"EN": "Burundi",
		"KO": "부룬디",
		"AR": "بوروندي",
		"IT": "Burundi",
		"ES": "Burundi",
		"DE": "Burundi",
		"NB_NO": "Burundi",
		"FR": "Burundi",
		"areaCode": "+257"
	},
	{
		"code": "CM",
		"ZH_CN": "喀麦隆",
		"ZH_TW": "喀麥隆",
		"EN": "Cameroon",
		"KO": "카메룬",
		"AR": "الكاميرون",
		"IT": "Camerun",
		"ES": "Camerún",
		"DE": "Kamerun",
		"NB_NO": "Kamerun",
		"FR": "Cameroun",
		"areaCode": "+237"
	},
	{
		"code": "CV",
		"ZH_CN": "佛得角",
		"ZH_TW": "佛得角",
		"EN": "Cape Verde",
		"KO": "카보 베르데",
		"AR": "الرأس الأخضر",
		"IT": "Capo Verde",
		"ES": "Cabo Verde",
		"DE": "Kap Verde",
		"NB_NO": "Kapp Verde",
		"FR": "Cap-Vert",
		"areaCode": "+238"
	},
	{
		"code": "CF",
		"ZH_CN": "中非",
		"ZH_TW": "中非",
		"EN": "Central African Republic",
		"KO": "중앙 아프리카 공화국",
		"AR": "جمهورية افريقيا الوسطى",
		"IT": "Repubblica Centrafricana",
		"ES": "República Centroafricana",
		"DE": "Zentralafrikanische Republik",
		"NB_NO": "Den sentralafrikanske republikk",
		"FR": "République centrafricaine",
		"areaCode": "+236"
	},
	{
		"code": "CL",
		"ZH_CN": "智利",
		"ZH_TW": "智利",
		"EN": "Chile",
		"KO": "칠레",
		"AR": "تشيلي",
		"IT": "Cile",
		"ES": "Chile",
		"DE": "Chile",
		"NB_NO": "Chile",
		"FR": "Chili",
		"areaCode": "+56"
	},
	{
		"code": "CX",
		"ZH_CN": "圣诞岛",
		"ZH_TW": "聖誕島",
		"EN": "Christmas Island",
		"KO": "크리스마스 섬",
		"AR": "جزيرة الكريسماس",
		"IT": "Natale, Isola di",
		"ES": "Isla Navidad",
		"DE": "Weihnachtsinsel",
		"NB_NO": "Christmasøya",
		"FR": "Île Christmas",
		"areaCode": "+61"
	},
	{
		"code": "CO",
		"ZH_CN": "哥伦比亚",
		"ZH_TW": "哥倫比亞",
		"EN": "Colombia",
		"KO": "콜롬비아",
		"AR": "كولومبيا",
		"IT": "Colombia",
		"ES": "Colombia",
		"DE": "Kolumbien",
		"NB_NO": "Colombia",
		"FR": "Colombie",
		"areaCode": "+57"
	},
	{
		"code": "CD",
		"ZH_CN": "刚果（金）",
		"ZH_TW": "剛果（金）",
		"EN": "Congo (Democratic Republic of the)",
		"KO": "콩고, 민주 공화국",
		"AR": "جمهورية الكونغو الديمقراطية",
		"IT": "Congo, Repubblica Democratica del",
		"ES": "República Democrática del Congo",
		"DE": "Kongo, Demokratische Republik",
		"NB_NO": "Kongo-Kinshasa",
		"FR": "République démocratique du Congo",
		"areaCode": "+243"
	},
	{
		"code": "CK",
		"ZH_CN": "库克群岛",
		"ZH_TW": "庫克群島",
		"EN": "Cook Islands",
		"KO": "쿡 제도",
		"AR": "جزر كوك",
		"IT": "Cook, Isole",
		"ES": "Islas Cook",
		"DE": "Cookinseln",
		"NB_NO": "Cookøyene",
		"FR": "Cook (Îles)",
		"areaCode": "+682"
	},
	{
		"code": "CI",
		"ZH_CN": "科特迪瓦",
		"ZH_TW": "科特迪瓦",
		"EN": "Côte d'Ivoire",
		"KO": "코트 디부 아르",
		"AR": "كوت ديفوار",
		"IT": "Costa d'Avorio",
		"ES": "Costa de Marfil",
		"DE": "Elfenbeinküste",
		"NB_NO": "Elfenbenskysten",
		"FR": "Côte d'Ivoire",
		"areaCode": "+225"
	},
	{
		"code": "CU",
		"ZH_CN": "古巴",
		"ZH_TW": "古巴",
		"EN": "Cuba",
		"KO": "쿠바",
		"AR": "كوبا",
		"IT": "Cuba",
		"ES": "Cuba",
		"DE": "Kuba",
		"NB_NO": "Cuba",
		"FR": "Cuba",
		"areaCode": "+53"
	},
	{
		"code": "CZ",
		"ZH_CN": "捷克",
		"ZH_TW": "捷克",
		"EN": "Czech Republic",
		"KO": "체코 공화국",
		"AR": "جمهورية التشيك",
		"IT": "Repubblica Ceca",
		"ES": "República Checa",
		"DE": "Tschechien",
		"NB_NO": "Tsjekkia",
		"FR": "République tchèque",
		"areaCode": "+420"
	},
	{
		"code": "DJ",
		"ZH_CN": "吉布提",
		"ZH_TW": "吉布提",
		"EN": "Djibouti",
		"KO": "지부티",
		"AR": "جيبوتي",
		"IT": "Gibuti",
		"ES": "Yibuti",
		"DE": "Dschibuti",
		"NB_NO": "Djibouti",
		"FR": "Djibouti",
		"areaCode": "+253"
	},
	{
		"code": "DO",
		"ZH_CN": "多米尼加",
		"ZH_TW": "多米尼加",
		"EN": "Dominican Republic",
		"KO": "도미니카",
		"AR": "دومينيكا",
		"IT": "Repubblica Dominicana",
		"ES": "República Dominicana",
		"DE": "Dominikanische Republik",
		"NB_NO": "Den dominikanske republikk",
		"FR": "République dominicaine",
		"areaCode": "+1809"
	},
	{
		"code": "EG",
		"ZH_CN": "埃及",
		"ZH_TW": "埃及",
		"EN": "Egypt",
		"KO": "이집트",
		"AR": "مصر",
		"IT": "Egitto",
		"ES": "Egipto",
		"DE": "Ägypten",
		"NB_NO": "Egypt",
		"FR": "Égypte",
		"areaCode": "+20"
	},
	{
		"code": "GQ",
		"ZH_CN": "赤道几内亚",
		"ZH_TW": "赤道幾內亞",
		"EN": "Equatorial Guinea",
		"KO": "적도 기니",
		"AR": "غينيا الإستوائية",
		"IT": "Guinea Equatoriale",
		"ES": "Guinea Ecuatorial",
		"DE": "Äquatorialguinea",
		"NB_NO": "Ekvatorial-Guinea",
		"FR": "Guinée équatoriale",
		"areaCode": "+240"
	},
	{
		"code": "EE",
		"ZH_CN": "爱沙尼亚",
		"ZH_TW": "愛沙尼亞",
		"EN": "Estonia",
		"KO": "에스토니아",
		"AR": "استونيا",
		"IT": "Estonia",
		"ES": "Estonia",
		"DE": "Estland",
		"NB_NO": "Estland",
		"FR": "Estonie",
		"areaCode": "+372"
	},
	{
		"code": "ZW",
		"ZH_CN": "津巴布韦",
		"ZH_TW": "津巴布韋",
		"EN": "Zimbabwe",
		"KO": "짐바브웨",
		"AR": "زيمبابوي",
		"IT": "Zimbabwe",
		"ES": "Zimbabue",
		"DE": "Simbabwe",
		"NB_NO": "Zimbabwe",
		"FR": "Zimbabwe",
		"areaCode": "+263"
	},
	{
		"code": "FO",
		"ZH_CN": "法罗群岛",
		"ZH_TW": "法羅群島",
		"EN": "Faroe Islands",
		"KO": "페로 제도",
		"AR": "جزر صناعية",
		"IT": "Faroe, Isole",
		"ES": "Islas Feroe",
		"DE": "Färöer-Inseln",
		"NB_NO": "Færøyene",
		"FR": "Féroé (Îles)",
		"areaCode": "+298"
	},
	{
		"code": "FI",
		"ZH_CN": "芬兰",
		"ZH_TW": "芬蘭",
		"EN": "Finland",
		"KO": "핀란드",
		"AR": "فنلندا",
		"IT": "Finlandia",
		"ES": "Finlandia",
		"DE": "Finnland",
		"NB_NO": "Finland",
		"FR": "Finlande",
		"areaCode": "+358"
	},
	{
		"code": "GF",
		"ZH_CN": "法属圭亚那",
		"ZH_TW": "法屬圭亞那",
		"EN": "French Guiana",
		"KO": "프랑스령 기아나",
		"AR": "غيانا الفرنسية",
		"IT": "Guyana francese",
		"ES": "Guayana Francesa",
		"DE": "Französisch-Guayana",
		"NB_NO": "Fransk Guyana",
		"FR": "Guyane française",
		"areaCode": "+594"
	},
	{
		"code": "TF",
		"ZH_CN": "法属南部领土",
		"ZH_TW": "法屬南部領土",
		"EN": "French Southern Territories",
		"KO": "프랑스 남부 및 남극 대륙",
		"AR": "الأراضي الفرنسية الجنوبية والقطب الجنوبي",
		"IT": "Terre Australi e Antartiche Francesi",
		"ES": "Tierras Australes y Antárticas Francesas",
		"DE": "Französische Südgebiete",
		"NB_NO": "De franske sørterritorier",
		"FR": "Terres australes françaises",
		"areaCode": "+262"
	},
	{
		"code": "GE",
		"ZH_CN": "格鲁吉亚",
		"ZH_TW": "格魯吉亞",
		"EN": "Georgia",
		"KO": "그루지야",
		"AR": "جورجيا",
		"IT": "Georgia",
		"ES": "Georgia",
		"DE": "Georgien",
		"NB_NO": "Georgia",
		"FR": "Géorgie",
		"areaCode": "+995"
	},
	{
		"code": "GH",
		"ZH_CN": "加纳",
		"ZH_TW": "加納",
		"EN": "Ghana",
		"KO": "가나",
		"AR": "غانا",
		"IT": "Ghana",
		"ES": "Ghana",
		"DE": "Ghana",
		"NB_NO": "Ghana",
		"FR": "Ghana",
		"areaCode": "+233"
	},
	{
		"code": "GR",
		"ZH_CN": "希腊",
		"ZH_TW": "希臘",
		"EN": "Greece",
		"KO": "그리스",
		"AR": "اليونان",
		"IT": "Grecia",
		"ES": "Grecia",
		"DE": "Griechenland",
		"NB_NO": "Hellas",
		"FR": "Grèce",
		"areaCode": "+30"
	},
	{
		"code": "GD",
		"ZH_CN": "格林纳达",
		"ZH_TW": "格林納達",
		"EN": "Grenada",
		"KO": "그레나다",
		"AR": "غرينادا",
		"IT": "Grenada",
		"ES": "Granada",
		"DE": "Grenada",
		"NB_NO": "Grenada",
		"FR": "La Grenade",
		"areaCode": "+1473"
	},
	{
		"code": "GU",
		"ZH_CN": "关岛",
		"ZH_TW": "關島",
		"EN": "Guam",
		"KO": "괌",
		"AR": "غوام",
		"IT": "Guam",
		"ES": "Guam",
		"DE": "Guam",
		"NB_NO": "Guam",
		"FR": "Guam",
		"areaCode": "+1671"
	},
	{
		"code": "GG",
		"ZH_CN": "根西岛",
		"ZH_TW": "根西島",
		"EN": "Guernsey",
		"KO": "게르니",
		"AR": "غيرنسي",
		"IT": "Guernsey",
		"ES": "Guernsey",
		"DE": "Guernsey",
		"NB_NO": "Guernsey",
		"FR": "Guernesey",
		"areaCode": "+44"
	},
	{
		"code": "GW",
		"ZH_CN": "几内亚比绍",
		"ZH_TW": "幾內亞比紹",
		"EN": "Guinea-bissau",
		"KO": "기니 비사우",
		"AR": "غينيا بيساو",
		"IT": "Guinea-Bissau",
		"ES": "Guinea-Bissau",
		"DE": "Guinea-Bissau",
		"NB_NO": "Guinea-Bissau",
		"FR": "Guinée-Bissau",
		"areaCode": "+245"
	},
	{
		"code": "HT",
		"ZH_CN": "海地",
		"ZH_TW": "海地",
		"EN": "Haiti",
		"KO": "아이티",
		"AR": "هايتي",
		"IT": "Haiti",
		"ES": "Haití",
		"DE": "Haiti",
		"NB_NO": "Haiti",
		"FR": "Haïti",
		"areaCode": "+509"
	},
	{
		"code": "VA",
		"ZH_CN": "梵蒂冈",
		"ZH_TW": "梵蒂岡",
		"EN": "Vatican",
		"KO": "홀리시 (바티칸 시)",
		"AR": "الكرسي الرسولي (مدينة الفاتيكان)",
		"IT": "Vaticano, Stato della Città del",
		"ES": "Ciudad del Vaticano",
		"DE": "Vatikanstadt",
		"NB_NO": "Vatikanstaten",
		"FR": "Vatican (État de la Cité du)",
		"areaCode": "+379"
	},
	{
		"code": "IS",
		"ZH_CN": "冰岛",
		"ZH_TW": "冰島",
		"EN": "Iceland",
		"KO": "아이슬란드",
		"AR": "أيسلندا",
		"IT": "Islanda",
		"ES": "Islandia",
		"DE": "Island",
		"NB_NO": "Island",
		"FR": "Islande",
		"areaCode": "+354"
	},
	{
		"code": "IQ",
		"ZH_CN": "伊拉克",
		"ZH_TW": "伊拉克",
		"EN": "Iraq",
		"KO": "이라크",
		"AR": "العراق",
		"IT": "Iraq",
		"ES": "Iraq",
		"DE": "Irak",
		"NB_NO": "",
		"FR": "Irak",
		"areaCode": "+964"
	},
	{
		"code": "IL",
		"ZH_CN": "以色列",
		"ZH_TW": "以色列",
		"EN": "Israel",
		"KO": "이스라엘",
		"AR": "إسرائيل",
		"IT": "Israele",
		"ES": "Israel",
		"DE": "Israel",
		"NB_NO": "Israel",
		"FR": "Israël",
		"areaCode": "+972"
	},
	{
		"code": "JM",
		"ZH_CN": "牙买加",
		"ZH_TW": "牙買加",
		"EN": "Jamaica",
		"KO": "자메이카",
		"AR": "جامايكا",
		"IT": "Giamaica",
		"ES": "Jamaica",
		"DE": "Jamaika",
		"NB_NO": "Jamaica",
		"FR": "Jamaïque",
		"areaCode": "+1876"
	},
	{
		"code": "JE",
		"ZH_CN": "泽西岛",
		"ZH_TW": "澤西島",
		"EN": "Jersey",
		"KO": "저지",
		"AR": "جيرسي",
		"IT": "Jersey",
		"ES": "Jersey",
		"DE": "Jersey",
		"NB_NO": "Jersey",
		"FR": "Jersey",
		"areaCode": "+44"
	},
	{
		"code": "KZ",
		"ZH_CN": "哈萨克斯坦",
		"ZH_TW": "哈薩克斯坦",
		"EN": "Kazakhstan",
		"KO": "카자흐스탄",
		"AR": "كازاخستان",
		"IT": "Kazakistan",
		"ES": "Kazajistán",
		"DE": "Kasachstan",
		"NB_NO": "Kasakhstan",
		"FR": "Kazakhstan",
		"areaCode": "+7"
	},
	{
		"code": "KI",
		"ZH_CN": "基里巴斯",
		"ZH_TW": "基裏巴斯",
		"EN": "Kiribati",
		"KO": "키리바시",
		"AR": "كيريباس",
		"IT": "Kiribati",
		"ES": "Kiribati",
		"DE": "Kiribati",
		"NB_NO": "Kiribati",
		"FR": "Kiribati",
		"areaCode": "+686"
	},
	{
		"code": "KR",
		"ZH_CN": "韩国",
		"ZH_TW": "韓國",
		"EN": "South Korea",
		"KO": "대한민국",
		"AR": "كوريا الجنوبية",
		"IT": "Corea del Sud",
		"ES": "Corea del Sur",
		"DE": "Südkorea",
		"NB_NO": "Sør-Korea",
		"FR": "Corée du Sud",
		"areaCode": "+82"
	},
	{
		"code": "KG",
		"ZH_CN": "吉尔吉斯斯坦",
		"ZH_TW": "吉爾吉斯斯坦",
		"EN": "Kyrgyzstan",
		"KO": "키르기스스탄",
		"AR": "قرغيزستان",
		"IT": "Kirghizistan",
		"ES": "Kirguistán",
		"DE": "Kirgisistan",
		"NB_NO": "Kirgisistan",
		"FR": "Kirghizistan",
		"areaCode": "+996"
	},
	{
		"code": "LV",
		"ZH_CN": "拉脱维亚",
		"ZH_TW": "拉脫維亞",
		"EN": "Latvia",
		"KO": "라트비아",
		"AR": "لاتفيا",
		"IT": "Lettonia",
		"ES": "Letonia",
		"DE": "Lettland",
		"NB_NO": "Latvia",
		"FR": "Lettonie",
		"areaCode": "+371"
	},
	{
		"code": "LS",
		"ZH_CN": "莱索托",
		"ZH_TW": "萊索托",
		"EN": "Lesotho",
		"KO": "레소토",
		"AR": "ليسوتو",
		"IT": "Lesotho",
		"ES": "Lesoto",
		"DE": "Lesotho",
		"NB_NO": "Lesotho",
		"FR": "Lesotho",
		"areaCode": "+266"
	},
	{
		"code": "LY",
		"ZH_CN": "利比亚",
		"ZH_TW": "利比亞",
		"EN": "Libya",
		"KO": "리비아",
		"AR": "ليبيا",
		"IT": "Libia",
		"ES": "Libia",
		"DE": "Libyen",
		"NB_NO": "Libya",
		"FR": "Libye",
		"areaCode": "+218"
	},
	{
		"code": "LT",
		"ZH_CN": "立陶宛",
		"ZH_TW": "立陶宛",
		"EN": "Lithuania",
		"KO": "리투아니아",
		"AR": "ليتوانيا",
		"IT": "Lituania",
		"ES": "Lituania",
		"DE": "Litauen",
		"NB_NO": "Litauen",
		"FR": "Lituanie",
		"areaCode": "+370"
	},
	{
		"code": "MO",
		"ZH_CN": "澳门",
		"ZH_TW": "澳門",
		"EN": "Macau, China",
		"KO": "마카오",
		"AR": "ماكاو",
		"IT": "Macau, Cina",
		"ES": "Macao, China",
		"DE": "Macao, China",
		"NB_NO": "Macao S.A.R. Kina",
		"FR": "Macao, Chine",
		"areaCode": "+853"
	},
	{
		"code": "MG",
		"ZH_CN": "马达加斯加",
		"ZH_TW": "馬達加斯加",
		"EN": "Madagascar",
		"KO": "마다가스카르",
		"AR": "مدغشقر",
		"IT": "Madagascar",
		"ES": "Madagascar",
		"DE": "Madagaskar",
		"NB_NO": "Madagaskar",
		"FR": "Madagascar",
		"areaCode": "+261"
	},
	{
		"code": "ML",
		"ZH_CN": "马里",
		"ZH_TW": "馬裏",
		"EN": "Mali",
		"KO": "말리",
		"AR": "مالي",
		"IT": "Mali",
		"ES": "Malí",
		"DE": "Mali",
		"NB_NO": "Mali",
		"FR": "Mali",
		"areaCode": "+223"
	},
	{
		"code": "IM",
		"ZH_CN": "马恩岛",
		"ZH_TW": "馬恩島",
		"EN": "Isle of Man",
		"KO": "아일 오브 맨",
		"AR": "جزيرة آيل أوف مان",
		"IT": "Isola di Man",
		"ES": "Isla de Man",
		"DE": "Isle of Man",
		"NB_NO": "Man",
		"FR": "Île de Man",
		"areaCode": "+44"
	},
	{
		"code": "MQ",
		"ZH_CN": "马提尼克",
		"ZH_TW": "馬提尼克",
		"EN": "Martinique",
		"KO": "마르티니크",
		"AR": "مارتينيك",
		"IT": "Martinica",
		"ES": "Martinica",
		"DE": "Martinique",
		"NB_NO": "Martinique",
		"FR": "Martinique",
		"areaCode": "+596"
	},
	{
		"code": "MU",
		"ZH_CN": "毛里求斯",
		"ZH_TW": "毛裏求斯",
		"EN": "Mauritius",
		"KO": "모리셔스",
		"AR": "موريشيوس",
		"IT": "Mauritius",
		"ES": "Mauricio",
		"DE": "Mauritius",
		"NB_NO": "Mauritius",
		"FR": "Maurice",
		"areaCode": "+230"
	},
	{
		"code": "MX",
		"ZH_CN": "墨西哥",
		"ZH_TW": "墨西哥",
		"EN": "Mexico",
		"KO": "멕시코",
		"AR": "المكسيك",
		"IT": "Messico",
		"ES": "México",
		"DE": "Mexiko",
		"NB_NO": "Mexico",
		"FR": "Mexique",
		"areaCode": "+52"
	},
	{
		"code": "MD",
		"ZH_CN": "摩尔多瓦",
		"ZH_TW": "摩爾多瓦",
		"EN": "Moldova",
		"KO": "몰도바",
		"AR": "مولدوفا",
		"IT": "Moldavia",
		"ES": "Moldavia",
		"DE": "Republik Moldau",
		"NB_NO": "Moldova",
		"FR": "Moldavie",
		"areaCode": "+373"
	},
	{
		"code": "MN",
		"ZH_CN": "蒙古",
		"ZH_TW": "蒙古",
		"EN": "Mongolia",
		"KO": "몽골리아",
		"AR": "منغوليا",
		"IT": "Mongolia",
		"ES": "Mongolia",
		"DE": "Mongolei",
		"NB_NO": "Mongolia",
		"FR": "Mongolie",
		"areaCode": "+976"
	},
	{
		"code": "MA",
		"ZH_CN": "摩洛哥",
		"ZH_TW": "摩洛哥",
		"EN": "Morocco",
		"KO": "모로코",
		"AR": "المغرب",
		"IT": "Marocco",
		"ES": "Marruecos",
		"DE": "Marokko",
		"NB_NO": "Marokko",
		"FR": "Maroc",
		"areaCode": "+212"
	},
	{
		"code": "NA",
		"ZH_CN": "纳米尼亚",
		"ZH_TW": "納米尼亞",
		"EN": "Namibia",
		"KO": "나미비아",
		"AR": "ناميبيا",
		"IT": "Namibia",
		"ES": "Namibia",
		"DE": "Namibia",
		"NB_NO": "Namibia",
		"FR": "Namibie",
		"areaCode": "+264"
	},
	{
		"code": "NP",
		"ZH_CN": "尼泊尔",
		"ZH_TW": "尼泊爾",
		"EN": "Nepal",
		"KO": "네팔",
		"AR": "نيبال",
		"IT": "Nepal",
		"ES": "Nepal",
		"DE": "Nepal",
		"NB_NO": "Nepal",
		"FR": "Népal",
		"areaCode": "+977"
	},
	{
		"code": "AN",
		"ZH_CN": "荷属安的列斯",
		"ZH_TW": "荷屬安的列斯",
		"EN": "Netherlands Antilles",
		"KO": "네덜란드령 안틸레스",
		"AR": "جزر الأنتيل الهولندية",
		"IT": "Antille Olandesi",
		"ES": "Antillas Neerlandesas",
		"DE": "Niederländische Antillen",
		"NB_NO": "De nederlandske antiller",
		"FR": "Antilles néerlandaises",
		"areaCode": "+599"
	},
	{
		"code": "NZ",
		"ZH_CN": "新西兰",
		"ZH_TW": "新西蘭",
		"EN": "New Zealand",
		"KO": "뉴질랜드",
		"AR": "نيوزيلندا",
		"IT": "Nuova Zelanda",
		"ES": "Nueva Zelanda",
		"DE": "Neuseeland",
		"NB_NO": "New Zealand",
		"FR": "Nouvelle-Zélande",
		"areaCode": "+64"
	},
	{
		"code": "NE",
		"ZH_CN": "尼日尔",
		"ZH_TW": "尼日爾",
		"EN": "Niger",
		"KO": "니제르",
		"AR": "النيجر",
		"IT": "Niger",
		"ES": "Níger",
		"DE": "Niger",
		"NB_NO": "Niger",
		"FR": "Niger",
		"areaCode": "+227"
	},
	{
		"code": "NU",
		"ZH_CN": "纽埃",
		"ZH_TW": "紐埃",
		"EN": "Niue",
		"KO": "니우에",
		"AR": "نيوي",
		"IT": "Niue",
		"ES": "Niue",
		"DE": "Niue",
		"NB_NO": "Niue",
		"FR": "Niue",
		"areaCode": "+683"
	},
	{
		"code": "MP",
		"ZH_CN": "北马里亚纳",
		"ZH_TW": "北馬裏亞納",
		"EN": "Northern Mariana Islands",
		"KO": "북 마리아나 섬",
		"AR": "جزيرة ماريانا الشمالية",
		"IT": "Marianne Settentrionali, Isole",
		"ES": "Islas Marianas del Norte",
		"DE": "Nördliche Marianen",
		"NB_NO": "Nord-Marianene",
		"FR": "Îles Mariannes du Nord",
		"areaCode": "+1670"
	},
	{
		"code": "OM",
		"ZH_CN": "阿曼",
		"ZH_TW": "阿曼",
		"EN": "Oman",
		"KO": "오만",
		"AR": "سلطنة عمان",
		"IT": "Oman",
		"ES": "Omán",
		"DE": "Oman",
		"NB_NO": "Oman",
		"FR": "Oman",
		"areaCode": "+968"
	},
	{
		"code": "PW",
		"ZH_CN": "帕劳",
		"ZH_TW": "帕勞",
		"EN": "Palau",
		"KO": "팔라우",
		"AR": "بالاو",
		"IT": "Palau",
		"ES": "Palaos",
		"DE": "Palau",
		"NB_NO": "Palau",
		"FR": "Palaos",
		"areaCode": "+680"
	},
	{
		"code": "PG",
		"ZH_CN": "巴布亚新几内亚",
		"ZH_TW": "巴布亞新幾內亞",
		"EN": "Papua New Guinea",
		"KO": "파푸아 뉴기니",
		"AR": "بابوا غينيا الجديدة",
		"IT": "Papua Nuova Guinea",
		"ES": "Papúa Nueva Guinea",
		"DE": "Papua-Neuguinea",
		"NB_NO": "Papua Ny-Guinea",
		"FR": "Papouasie-Nouvelle-Guinée",
		"areaCode": "+675"
	},
	{
		"code": "PE",
		"ZH_CN": "秘鲁",
		"ZH_TW": "秘魯",
		"EN": "Peru",
		"KO": "페루",
		"AR": "بيرو",
		"IT": "Perù",
		"ES": "Perú",
		"DE": "Peru",
		"NB_NO": "Peru",
		"FR": "Pérou",
		"areaCode": "+51"
	},
	{
		"code": "PN",
		"ZH_CN": "皮特凯恩",
		"ZH_TW": "皮特凱恩",
		"EN": "Pitcairn",
		"KO": "핏케언 제도",
		"AR": "جزر بيتكيرن",
		"IT": "Pitcairn",
		"ES": "Pitcairn",
		"DE": "Pitcairn",
		"NB_NO": "Pitcairn",
		"FR": "Pitcairn",
		"areaCode": "+64"
	},
	{
		"code": "PT",
		"ZH_CN": "葡萄牙",
		"ZH_TW": "葡萄牙",
		"EN": "Portugal",
		"KO": "포르투갈",
		"AR": "البرتغال",
		"IT": "Portogallo",
		"ES": "Portugal",
		"DE": "Portugal",
		"NB_NO": "Portugal",
		"FR": "Portugal",
		"areaCode": "+351"
	},
	{
		"code": "ZM",
		"ZH_CN": "赞比亚",
		"ZH_TW": "贊比亞",
		"EN": "Zambia",
		"KO": "잠비아",
		"AR": "زامبيا",
		"IT": "Zambia",
		"ES": "Zambia",
		"DE": "Sambia",
		"NB_NO": "Zambia",
		"FR": "Zambie",
		"areaCode": "+260"
	},
	{
		"code": "RE",
		"ZH_CN": "留尼汪",
		"ZH_TW": "留尼汪",
		"EN": "Reunion",
		"KO": "재결합",
		"AR": "جمع شمل",
		"IT": "Riunione (Francia)",
		"ES": "Reunión",
		"DE": "Réunion",
		"NB_NO": "Reunion",
		"FR": "Réunion (Île de La)",
		"areaCode": "+262"
	},
	{
		"code": "RU",
		"ZH_CN": "俄罗斯",
		"ZH_TW": "俄羅斯",
		"EN": "Russia",
		"KO": "러시아 연방",
		"AR": "الاتحاد الروسي",
		"IT": "Russia",
		"ES": "Rusia",
		"DE": "Russland",
		"NB_NO": "Russland",
		"FR": "Russie",
		"areaCode": "+7"
	},
	{
		"code": "SH",
		"ZH_CN": "圣赫勒拿",
		"ZH_TW": "聖赫勒拿",
		"EN": "Saint Helena, Ascension and Tristan da Cunha",
		"KO": "세인트헬레나",
		"AR": "سانت هيلانة",
		"IT": "Sant'Elena, Ascensione e Tristan da Cunha",
		"ES": "Santa Elena, Ascensión y Tristán de Acuña",
		"DE": "St. Helena, Ascension und Tristan da Cunha",
		"NB_NO": "St. Helena",
		"FR": "Sainte-Hélène, Ascension et Tristan da Cunha",
		"areaCode": "+290"
	},
	{
		"code": "LC",
		"ZH_CN": "圣卢西亚",
		"ZH_TW": "聖盧西亞",
		"EN": "Saint Lucia",
		"KO": "세인트 루시아",
		"AR": "القديسة لوسيا",
		"IT": "Saint Lucia",
		"ES": "Santa Lucía",
		"DE": "St. Lucia",
		"NB_NO": "Saint Lucia",
		"FR": "Sainte-Lucie",
		"areaCode": "+1758"
	},
	{
		"code": "VC",
		"ZH_CN": "圣文森特和格林纳丁斯",
		"ZH_TW": "聖文森特和格林納丁斯",
		"EN": "Saint Vincent and the Grenadines",
		"KO": "세인트 빈센트 그레나딘",
		"AR": "سانت فنسنت وجزر غرينادين",
		"IT": "Saint Vincent e Grenadine",
		"ES": "San Vicente y las Granadinas",
		"DE": "St. Vincent und die Grenadinen",
		"NB_NO": "Saint Vincent og Grenadinene",
		"FR": "Saint-Vincent-et-les-Grenadines",
		"areaCode": "+1784"
	},
	{
		"code": "SM",
		"ZH_CN": "圣马力诺",
		"ZH_TW": "聖馬力諾",
		"EN": "San Marino",
		"KO": "산마리노",
		"AR": "سان مارينو",
		"IT": "San Marino",
		"ES": "San Marino",
		"DE": "San Marino",
		"NB_NO": "San Marino",
		"FR": "Saint-Marin",
		"areaCode": "+378"
	},
	{
		"code": "SA",
		"ZH_CN": "沙特阿拉伯",
		"ZH_TW": "沙特阿拉伯",
		"EN": "Saudi Arabia",
		"KO": "사우디 아라비아",
		"AR": "المملكة العربية السعودية",
		"IT": "Arabia Saudita",
		"ES": "Arabia Saudí",
		"DE": "Saudi-Arabien",
		"NB_NO": "Saudi-Arabia",
		"FR": "Arabie saoudite",
		"areaCode": "+966"
	},
	{
		"code": "RS",
		"ZH_CN": "塞尔维亚",
		"ZH_TW": "塞爾維亞",
		"EN": "Serbia",
		"KO": "세르비아",
		"AR": "صربيا",
		"IT": "Serbia",
		"ES": "Serbia",
		"DE": "Serbien",
		"NB_NO": "Serbia",
		"FR": "Serbie",
		"areaCode": "+381"
	},
	{
		"code": "SL",
		"ZH_CN": "塞拉利昂",
		"ZH_TW": "塞拉利昂",
		"EN": "Sierra Leone",
		"KO": "시에라 리온",
		"AR": "سيرا ليون",
		"IT": "Sierra Leone",
		"ES": "Sierra Leona",
		"DE": "Sierra Leone",
		"NB_NO": "Sierra Leone",
		"FR": "Sierra Leone",
		"areaCode": "+232"
	},
	{
		"code": "SK",
		"ZH_CN": "斯洛伐克",
		"ZH_TW": "斯洛伐克",
		"EN": "Slovakia",
		"KO": "슬로바키아",
		"AR": "سلوفاكيا",
		"IT": "Slovacchia",
		"ES": "Eslovaquia",
		"DE": "Slowakei",
		"NB_NO": "Slovakia",
		"FR": "Slovaquie",
		"areaCode": "+421"
	},
	{
		"code": "SB",
		"ZH_CN": "所罗门群岛",
		"ZH_TW": "所羅門群島",
		"EN": "Solomon Islands",
		"KO": "솔로몬 제도",
		"AR": "جزر سليمان",
		"IT": "Salomone, Isole",
		"ES": "Islas Salomón",
		"DE": "Salomonen",
		"NB_NO": "Salomonøyene",
		"FR": "Salomon (Îles)",
		"areaCode": "+677"
	},
	{
		"code": "ZA",
		"ZH_CN": "南非",
		"ZH_TW": "南非",
		"EN": "South Africa",
		"KO": "남아프리카",
		"AR": "جنوب أفريقيا",
		"IT": "Sud Africa",
		"ES": "Sudáfrica",
		"DE": "Südafrika",
		"NB_NO": "Sør-Afrika",
		"FR": "Afrique du Sud",
		"areaCode": "+27"
	},
	{
		"code": "ES",
		"ZH_CN": "西班牙",
		"ZH_TW": "西班牙",
		"EN": "Spain",
		"KO": "스페인",
		"AR": "إسبانيا",
		"IT": "Spagna",
		"ES": "España",
		"DE": "Spanien",
		"NB_NO": "Spania",
		"FR": "Espagne",
		"areaCode": "+34"
	},
	{
		"code": "SD",
		"ZH_CN": "苏丹",
		"ZH_TW": "蘇丹",
		"EN": "Sudan",
		"KO": "수단",
		"AR": "سودان",
		"IT": "Sudan",
		"ES": "Sudán",
		"DE": "Sudan",
		"NB_NO": "Sudan",
		"FR": "Soudan",
		"areaCode": "+249"
	},
	{
		"code": "SJ",
		"ZH_CN": "斯瓦尔巴岛和扬马延岛",
		"ZH_TW": "斯瓦爾巴島和揚馬延島",
		"EN": "Svalbard and Jan Mayen",
		"KO": "스발바르",
		"AR": "سفالبارد",
		"IT": "Svalbard e Jan Mayen, Isole di",
		"ES": "Svalbard y Jan Mayen",
		"DE": "Svalbard und Jan Mayen",
		"NB_NO": "Svalbard og Jan Mayen",
		"FR": "Svalbard et Jan Mayen",
		"areaCode": "+47"
	},
	{
		"code": "SE",
		"ZH_CN": "瑞典",
		"ZH_TW": "瑞典",
		"EN": "Sweden",
		"KO": "스웨덴",
		"AR": "السويد",
		"IT": "Svezia",
		"ES": "Suecia",
		"DE": "Schweden",
		"NB_NO": "Sverige",
		"FR": "Suède",
		"areaCode": "+46"
	},
	{
		"code": "SY",
		"ZH_CN": "叙利亚",
		"ZH_TW": "敘利亞",
		"EN": "Syria",
		"KO": "시리아",
		"AR": "سوريا",
		"IT": "Siria",
		"ES": "Siria",
		"DE": "Syrien",
		"NB_NO": "Syria",
		"FR": "Syrie",
		"areaCode": "+963"
	},
	{
		"code": "TJ",
		"ZH_CN": "塔吉克斯坦",
		"ZH_TW": "塔吉克斯坦",
		"EN": "Tajikistan",
		"KO": "타지키스탄",
		"AR": "طاجيكستان",
		"IT": "Tagikistan",
		"ES": "Tayikistán",
		"DE": "Tadschikistan",
		"NB_NO": "Tadsjikistan",
		"FR": "Tadjikistan",
		"areaCode": "+992"
	},
	{
		"code": "GM",
		"ZH_CN": "冈比亚",
		"ZH_TW": "岡比亞",
		"EN": "Gambia",
		"KO": "감비아",
		"AR": "غامبيا",
		"IT": "Gambia",
		"ES": "Gambia",
		"DE": "Gambia",
		"NB_NO": "Gambia",
		"FR": "Gambie",
		"areaCode": "+220"
	},
	{
		"code": "TK",
		"ZH_CN": "托克劳",
		"ZH_TW": "托克勞",
		"EN": "Tokelau",
		"KO": "토켈라우",
		"AR": "توكيلاو",
		"IT": "Tokelau",
		"ES": "Tokelau",
		"DE": "Tokelau",
		"NB_NO": "Tokelau",
		"FR": "Tokelau",
		"areaCode": "+690"
	},
	{
		"code": "TT",
		"ZH_CN": "特立尼达和多巴哥",
		"ZH_TW": "特立尼達和多巴哥",
		"EN": "Trinidad and Tobago",
		"KO": "트리니다드 토바고",
		"AR": "ترينداد وتوباغو",
		"IT": "Trinidad e Tobago",
		"ES": "Trinidad y Tobago",
		"DE": "Trinidad und Tobago",
		"NB_NO": "Trinidad og Tobago",
		"FR": "Trinité-et-Tobago",
		"areaCode": "+1868"
	},
	{
		"code": "TR",
		"ZH_CN": "土耳其",
		"ZH_TW": "土耳其",
		"EN": "Türkiye (Turkey)",
		"KO": "터키",
		"AR": "ديك رومي",
		"IT": "Turchia",
		"ES": "Turquía",
		"DE": "Türkei",
		"NB_NO": "Tyrkia",
		"FR": "Turquie",
		"areaCode": "+90"
	},
	{
		"code": "TC",
		"ZH_CN": "特克斯和凯科斯群岛",
		"ZH_TW": "特克斯和凱科斯群島",
		"EN": "Turks and Caicos Islands",
		"KO": "터크 스 케이 커스 제도",
		"AR": "جزر تركس وكايكوس",
		"IT": "Turks e Caicos, Isole",
		"ES": "Islas Turcas y Caicos",
		"DE": "Turks- und Caicosinseln",
		"NB_NO": "Turks- og Caicosøyene",
		"FR": "Turques-et-Caïques (Îles)",
		"areaCode": "+1649"
	},
	{
		"code": "UG",
		"ZH_CN": "乌干达",
		"ZH_TW": "烏幹達",
		"EN": "Uganda",
		"KO": "우간다",
		"AR": "أوغندا",
		"IT": "Uganda",
		"ES": "Uganda",
		"DE": "Uganda",
		"NB_NO": "Uganda",
		"FR": "Ouganda",
		"areaCode": "+256"
	},
	{
		"code": "AE",
		"ZH_CN": "阿拉伯联合酋长国",
		"ZH_TW": "阿拉伯聯合酋長國",
		"EN": "United Arab Emirates",
		"KO": "아랍 에미리트",
		"AR": "الإمارات العربية المتحدة",
		"IT": "Emirati Arabi Uniti",
		"ES": "Emiratos Árabes Unidos",
		"DE": "Vereinigte Arabische Emirate",
		"NB_NO": "De forente arabiske emirater",
		"FR": "Émirats arabes unis",
		"areaCode": "+971"
	},
	{
		"code": "US",
		"ZH_CN": "美国",
		"ZH_TW": "美國",
		"EN": "United States",
		"KO": "아메리카 합중국",
		"AR": "الولايات المتحدة الامريكية",
		"IT": "Stati Uniti d'America",
		"ES": "Estados Unidos de América",
		"DE": "Vereinigte Staaten",
		"NB_NO": "USA",
		"FR": "États-Unis",
		"areaCode": "+1"
	},
	{
		"code": "UZ",
		"ZH_CN": "乌兹别克斯坦",
		"ZH_TW": "烏茲別克斯坦",
		"EN": "Uzbekistan",
		"KO": "우즈베키스탄",
		"AR": "أوزبكستان",
		"IT": "Uzbekistan",
		"ES": "Uzbekistán",
		"DE": "Usbekistan",
		"NB_NO": "Usbekistan",
		"FR": "Ouzbékistan",
		"areaCode": "+998"
	},
	{
		"code": "VE",
		"ZH_CN": "委内瑞拉",
		"ZH_TW": "委內瑞拉",
		"EN": "Venezuela",
		"KO": "베네수엘라",
		"AR": "فنزويلا",
		"IT": "Venezuela",
		"ES": "Venezuela",
		"DE": "Venezuela",
		"NB_NO": "Venezuela",
		"FR": "Venezuela",
		"areaCode": "+58"
	},
	{
		"code": "VI",
		"ZH_CN": "美属维尔京群岛",
		"ZH_TW": "美屬維爾京群島",
		"EN": "Virgin Islands, U.S.",
		"KO": "미국령 버진 아일랜드",
		"AR": "جزر فيرجن التابعة للولايات المتحدة",
		"IT": "Vergini Americane,Isole",
		"ES": "Islas Vírgenes de los Estados Unidos",
		"DE": "Jungferninseln, Amerikanische",
		"NB_NO": "Jomfruøyene, USA",
		"FR": "Îles Vierges américaines",
		"areaCode": "+1340"
	},
	{
		"code": "EH",
		"ZH_CN": "西撒哈拉",
		"ZH_TW": "西撒哈拉",
		"EN": "Western Sahara",
		"KO": "서부 사하라",
		"AR": "الصحراء الغربية",
		"IT": "Sahrawi (Sahara Occidentale), Repubblica Araba Democratica dei",
		"ES": "Sáhara Occidental",
		"DE": "Westsahara",
		"NB_NO": "Vest-Sahara",
		"FR": "Sahara occidental",
		"areaCode": "+212"
	}
]