
spring:
  application:
    name: demo-gateway-service # 微服务的名称
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 # Nacos服务地址
      discovery:
        watch:
          enabled: true # 开启服务变更监听
        register-enabled: false # 禁用服务注册
      config:
        shared-configs:
          - data-id: application-database.yml
            group: DIDA-COMMON
            refresh: true

server:
  port: 3456 # 网关服务端口