export default {
    cancel: "Cancel",
    BookingDate: "Booking Date",
    nationalityPlaceholder: "Select nationality",
    Apr: "Apr",
    INNum: "Enter ID number",
    onlineCheckIn: "Online Check-in",
    NoFistNamecheck: "Please enter first & middle name",
    FlightsInfo: "Flights Info",
    Reject: "Reject",
    Month: "m",
    protected: "Protected",
    DelayedBaggageService: "Delayed Baggage Protection",
    About_Us_txt22: "Customer service is provided in various was to better assist your needs.",
    IDNotice: "ID Notice • Names Must Match ID • > 6-month Validity",
    About_Us_txt21: "Attentive Service",
    addres_require_select: "Please enter address",
    FlightDelayedCanceled: "Have thoughts to share? ",
    excluding_baggage_allowance: "Excluding baggage allowance",
    AllLanguages: "All Languages",
    riskManagement: "Risk Management",
    Aisle: "Aisle sest",
    ShareThoughts: "Share your thoughts and help us enhance your experience by providing feedback on our website.",
    No_thanks: "No, thanks",
    recentSearchesCities: "Recent Searches Cities",
    partially_used_ticket: "Partially Used ticket(s)",
    Sun: "Sun",
    defaultKey: "Time(Local time)",
    seat: "Seat",
    InfantsTips: "Under 2 years old at time of travel",
    Details: "Details",
    Passengers: "Passengers",
    OtherServices: "Other Services",
    all_unused_tickets: "All Unused tickets",
    Post_ZIP_Code: "* Post/ZIP Code",
    NationalityPrompt: "Nationality",
    cardNumber: "Card Number",
    city_require_select: "Please enter city",
    Sep: "Sep",
    ViewCurrentBaggagePolicy: "View current Baggage Policy",
    before_departure: "Before departure",
    lowest_price: "Lowest price",
    country_require_select: "Please select a country",
    Infant: "Infant",
    selected_passegers: "Selected: {num} passegers",
    policy_detail: "*Change and cancellation fees are charged according tothe policies listed on the airline's website.",
    SeatSelection: "Seat Selection",
    ContactUs: "Contact Us",
    Part_included: "Part-included",
    Passport: "Passport",
    PassengersContactInfo: "Passengers & Contact Info",
    SecurePayment: "100% Secure Payment",
    Adult: "Adult",
    Stops: "Stops",
    Changes_not_permitted: "Change not permitted",
    free: "Free",
    IDNumber: "ID number",
    Window: "Window seat",
    Thu: "Thu",
    Jul: "Jul",
    About_Us_txt3: "Debodia International Limited,address at 2F, 38 Wong Chuk Hang Road,Wong Chuk Hang, Hong Kong with company register NO. 2585004.",
    About_Us_txt4: "BIGSKY Grup S.A.U.,address at Avda. Sant Antoni38,AD400 La Massana,Andorra,with company certificate register NO. L-7085322-S.",
    numBaggageChecked: "Add checked baggage for {num} passengers",
    cvv: "CVV",
    CallUs: "Call Us",
    Jun: "Jun",
    About_Us_txt1: "IWOFLY PTE LTD, address at 6 RAFFLES QUAY #16-01, SINGAPORE (048580) with company registry NO. 202338315R.",
    About_Us_txt2: "IWOFLY S.L., address at Paseo de las Delicias 30, 7a planta de la localidad de Madrid, 28045 with company registry NO. B88532528.;",
    Adultticket: "Adult ticket",
    About_Us_txt7: "10+ years air ticket online B2C experience, we have the experience of multi-national customer service and providing Chinese, English, French language services.",
    updatesFlightTips: "Log-in to check the flight updates",
    About_Us_txt8: "Knowing the pain points of the airfare industry's sales chain of layers of markups. We are committed to providing you with the lowest tier of pricing by removing the middlemen.",
    About_Us_txt5: "Why choose Sky-tours.com?",
    businessClass: "Business Class",
    About_Us_txt6: "30+ years air ticket B2B experience with rich resources, providing domestic air tickets and international air tickets from more than 40 countries, including Full Service airlines and Low Cost carriers.",
    About_Us_txt9: "Nowhere to obtain a special promotion which can be only purchased offline? We are here to offer you a treatment which can't be offered in the tycoon OTA!",
    WhyNot: "Why not ",
    Fare: "Fare",
    the_price_difference_generated_1: "The price difference for the Change Flight shall be covered by you. The Change Fee shall be charged by per person and by per change.",
    NoMatchingFlightsFound: "No matching results. Why not change your search criteria?",
    MalePlaceholder: "Male",
    E_Wallet: "E-Wallet",
    the_price_difference_generated_2: "If your flight has schedule change due to external factors (involuntary schedule change), we will offer you alternative solution accoridng to the airline's feedback. ",
    price_per: "per passenger",
    Select: "Select",
    Submit: "Submit",
    Back_to_select: "Back to select",
    to: "To",
    noEnLastNmaecheck: "Please enter last name in English only with no special characters",
    Add: "Add",
    Email: "Email",
    unpaid_booking_for_same_route: "Unpaid booking for same route",
    Pay: "Pay",
    questionsContactUs: "If you have any questions please contact us our customer service team.",
    pleaseLocation: "Please enter city or airport",
    premiumEconomy: "Premium Economy",
    WhyBookSt: "Why book with sky-tours?\n",
    buy_refundable: "Yes, make my booking refundable",
    FeedbackCounts: "Your Feedback Counts!",
    Restassured: "Rest assured with our secure payment system and robustrisk control measures prioritizing the protection of yourpersonal information and payments.",
    About_Us: "About Us",
    letDoThis: "Let's do this",
    Aug: "Aug",
    fistClass: "First Class",
    Search: "Search",
    LastUpdated: "*Last updated:",
    SeparateSelection: "Separate Selection",
    OurPartners: "Our Partners",
    myBooking: "My Bookings",
    search_similar_flights: "Search Similar Flights",
    Airports: "Airports",
    SecurityReliability: "Security and Reliability",
    kg_per_person: "kg per person",
    ShowFlights: "Show Flights",
    About: "About Us",
    province_require_select: "Please enter state/province",
    firstName: "First and middle name",
    flightsAlerts: "Flights Alerts",
    Nov: "Nov",
    each_piece_cannot_exceed: "Each piece cannot exceed {num} cm in size.",
    piece: "piece",
    nationalityCheck: "Please select nationality",
    please_retry: "System Internal Exception, Please Retry!",
    General: "General",
    Class: "Class",
    Adults: "Adults",
    BookingInstructions: "Booking instructions forchildren/infants>",
    peace_of_mind: "Book your flights width peace of mind",
    bookingNo: "Booking No",
    FAQ_Q5: "Can I modify my contact information?",
    Good_scenery: "Good scenery",
    FAQ_Q4: "Can my ticket be changed or cancelled?",
    delete_all_records: "Are you sure to delete all records?",
    FAQ_Q1: "How to find my order?",
    FAQ_Q3: "How to purchase baggage?",
    FAQ_Q2: "How to confirm whether the ticket is issued successfully?",
    CancellationFee: "Cancellation Fee",
    privacy: "We value your privacy",
    Time: "Time",
    buy_bags: "Yes, please track my bags",
    State_Province: "* State/Province",
    Continue: "Continue",
    alter_prices: "The airline has changed the price of this flight.",
    travelDreamsRunWild: "Sign up today and let travel dreams run wild.",
    Checked_baggage_included: "Checked baggage included",
    CheckIn2: "Facilitate a swift boarding process for your flight bypassing the need to wait in queues at the airport.",
    expiryDate: "Expiry Date",
    FAQ_A5: "If passengers have provided the wrong email addresses or phone numbers when booking, they can apply to modify the information no later than 48 hours before departure. Passengers need to send emails to support{'@'}sky-tours.com and provide the correct information.",
    duration: "Duration",
    CheckIn1: "The boarding pass will be sent to you within 24 hours before departure.",
    FAQ_A4: "The change and cancellation rules of each ticket vary according to different airline rules and cabin classes. When you purchase a ticket, the specific change and cancellation rules are displayed on the right side of the reservation page. After your booking is completed, you can also check the change and cancellation rules of the ticket that you purchased in \"My Bookings\".",
    LeaveFeedback: "Leave feedback",
    CheckIn3: "Avoid the expensive check-in fee at the counter.",
    FAQ_A1: "When you successfully place an order on Sky-tours, the system will automatically send an email containing the order number to your reserved email address. You can click \"My Bookings\" in the upper right corner of the homepage of Sky-tours website, enter the order number and your reserved email address, and then you can find your order.\nIf you fail to receive the notification email, please check your junk folder first. If it is not in the junk folder, maybe you have entered the wrong email address when booking. In this case, please contact our customer care team in time to assist you in modifying it.",
    Language: "Language",
    FAQ_A3: "Sky-tours can help you purchase the checked baggage allowance of most airlines. According to the regulations of airlines, different routes have different baggage pieces, weights and prices. You can purchase the baggage along with your booking. If you want to purchase extra baggage after placing an order, please contact us, and we will notify you of the corresponding fee. If you agree with the fee, we will send you a payment link via email. After your payment, we will handle it ASAP and send you the result via email.\nPlease be noted: Our Customer Service team will only contact you through the email address support{'@'}sky-tours.com. For the safety of your communication and funds, do not trust payment notifications from any other email addresses.",
    InfantsTicket: "Infant ticket (on lap)",
    FAQ_A2: "Your ticket has been successfully issued if you receive an email from tickets{'@'}sky-tours.com stating that your order is \"TICKETED\" with your ticket number.\nIf you haven't received the \"TICKETED\" notification email 72 hours after you placed an order, please check your junk folder first. If you are sure that you haven't received the notification email or need any other assistance, please feel free to contact our customer care team at any time.",
    Policies_Baggage: "Policies & Baggage",
    recommendedCheapFlights: "Recommended cheap flights",
    Children: "Children",
    non_refundable: "Non-refundable",
    changeSearch: "change your search criteria?",
    lowestPricedTips: "The lowest-priced flight departing within one month!",
    fistNamePrompt: "First & middle name",
    Return: "Return",
    payment_failed: "Payment failed!",
    ticket: "ticket",
    MobilePhoneTips: "Please provide a phone number",
    AddSeat: "Adding seats after booking usually costs more!",
    stop1: "1 stop",
    riskInfo: "We need you to provide the following information to pass payment verification.",
    INNumCheck: "Please enter ID number",
    About_Us_txt20: "The safety of your personal information is guaranteed.",
    BusinessClass: "Business Class",
    futureAdventures: "Curated travel content to inspire future adventures.",
    cardholder: "Cardholder's Name",
    Mon: "Mon",
    Checked: "Checked baggage",
    About_Us_txt19: "Secured Payment",
    TermsConditions: "Terms & Conditions",
    About_Us_txt18: "The flight routes cover over 200 countries and the  prices are highly competitive",
    TickeTpricesTips: "Searching for flights",
    notIncluded: "not included",
    Asia: "Asia",
    FAQ: "FAQ",
    Within: "Within {num} hours before ",
    priceRise: "Price Change",
    About_Us_txt11: "As long as the airlines provide free involuntary refund/cancellation, we will also offer you a free of charge service with no conditions.",
    About_Us_txt10: "Every customer will be serviced by warm and high-quality solution. No robot answers, but targeted solutions.",
    stop2: "2+ stops",
    About_Us_txt13: "We Make Your Wings",
    About_Us_txt12: "Sky-tours.com will become your personal online travel partner and make your wings to travel around the world.",
    Fri: "Fri",
    About_Us_txt15: "Contact Info",
    noLastNamecheck: "Please enter last name",
    About_Us_txt14: "More connectivity, more flexibility, more affordability",
    About_Us_txt17: "Rich Routes",
    About_Us_txt16: "If you have any questions, please feel free to contact our customer service team and we will be at your service 24/7 .",
    PriceDetails: "Price Details",
    birthPlaceholder: "Select date of birth",
    book_now: "Book now before it soars even higher.",
    Oct: "Oct",
    copyright: "{'@'} 2024 Sky-tours.com All Rights Reserved",
    StopoverCity: "Stopover city",
    Policies: "Policies",
    Address: "* Address",
    IDexpirationDateCheck: "Please select ID expiration date",
    offeringHighly: "Our flight network spans over 200 countries offering highlycompetitive prices for your convenience.\n",
    PleaseCompletePayment: "Please complete your payment within ",
    NameGuidelines: "Name Guidelines",
    oneWay: "One-way",
    required: "Required field",
    PaymentMethods: "Payment Methods",
    after_departure: "After departure",
    WishingpleasantJourney: "Wishing you a pleasant journey!",
    PaymentProgress: "Secure Payment",
    info_safe: "Sky-tours will protect your trip and keep your information safe!",
    lastNamePlaceholder: "e.g.CLINTON",
    ContactInfo: "Contact Info",
    Sameselection: "Same selection for all {num} passengers",
    SittingTogether: "Sitting together",
    ID: "ID",
    enter: "Enter",
    ServicesAdded: "Services Added",
    PaymentSuccessful: "Payment successful!",
    Child: "Child",
    Added: "Added",
    Recommended: "Recommended",
    post_ZIP_Code_require_select: "Please enter post/zip code",
    seatCompletedTxt: " passenger(s) have not selected seats. Would you like to go back to reserve seats?",
    enterEmailAdress: "Enter your email address",
    Carry_on_baggage: "Carry-on baggage",
    baggageAllowanceAndPolicies: "Baggage Allowance & Policies",
    risk_control_rejected: "Risk control rejected",
    all_airports: "All Airports",
    price_rise: "Price Rise",
    Wed: "Wed",
    Country: "* Country",
    pay_fail_txt: "If you have any questions, ",
    enterNameExactly: "Please ensure that the name entered matches the name on the travel document to avoid any issues during boarding.",
    Mar: "Mar",
    Hide: "Hide",
    lastName: "Last name",
    StayInspired: "Stay Inspired",
    unknow: "details",
    May: "May",
    Cancel: "cancel",
    add_insurance: " Add Insurance ",
    privacy3: "Privacy Policy",
    Confirm: "Confirm",
    privacy2: "Read more about our cookie practice here",
    privacy1: "We use technical, analytical and marketing cookies to help you with things like logging in and picking up your search where you left off.",
    completeSubmission: "Please complete the submission within",
    About_Us_txt: "This website is jointly managed by the following companies:",
    privacy4: "Close or ignore the banner notice means you agree to the use of essential cookies on your device or browser.",
    Hide_2_transfers: "Hide flights with more than 2 transfers",
    Economy: "Economy",
    Airlines: "Airlines",
    check34: "First & middle name exceeds 34 characters. Please revise or contact customer support for help",
    NonstopOnly: "Nonstop only",
    CheckIn: "Check-in",
    roundTrip: "Round-trip",
    pieces_per_person: "pieces per person",
    Feb: "Feb",
    kg_per_piece: "kg per piece",
    reminder: "Reminder",
    more: "More",
    CurrentLanguage: "Current Language",
    gotit: "Gotit",
    SeatSelectionTips: "Select your preferred seat for a comfortableourney.",
    bookingEmail: "Email for booking confirmation",
    AddBaggage: "Add Baggage",
    totallyBaggagePrice: "{num} piece(s) {weight} kg totally",
    AdditionalServices: "Additional Services",
    check29: "Last name exceeds 29 characters. Please revise or contact customer support for help ",
    SeatSelectionTipss: "We will try our best to meet your selection preferences. lf there are no eligible seats available we will promptly negotiate/refund with you. (Please ensure that your contact email address and phone number are filled in correctly.）",
    offer_time: "Office Hours: 9:00-18:00 (GMT+08), Mon - Sun",
    CustomerSupport: "Customer Support",
    AddPassengers: "Add Passengers",
    contactEmailEnter: "Please enter contact email",
    BaggageAllowance: "Baggage Allowance",
    SelectFare: "Select Fare",
    None: "None",
    IDTypePromptCheck: "Please select ID Type",
    Tips: "Tips",
    change_to_airport: "{num} Change to different airport",
    GenderPrompt: "Gender",
    CustomerService: "Global Customer Service",
    Done: "Done",
    FemalePlaceholder: "Female",
    ChildrenTips: "2-11 years old at time of travel",
    firstNamePlaceholder: "e.g. WILLIAM JEFFERSON",
    IDTypePrompt: "ID type",
    Infants: "Infants",
    system_processing: "System error, please try again",
    MobilePhone: "Mobile phone",
    noEncheck: "Please enter first & middle name in English only with no special characters ",
    Childticket: "Child ticket",
    please_enter_ID_info: "Please enter lD info",
    Filters: "Filters",
    Random: "Random seat",
    Cancellation_Fee: "Cancellation Fee",
    continue_booking: "Continue Booking",
    numSelected: "of {passegersnum} selected",
    backToSelect: "Back to select",
    from: "From {num}",
    credit: "Credit/Debit Card",
    Reset: "Reset",
    Baggage: "Baggage",
    INNumCheckDigits: "The document number is between 5 to 15 digits or letters",
    payNow: "Pay Now",
    Accept: "Accept",
    Europe: "Europe",
    NoThanks: "No, thanks",
    avoid_price_change: "to avoid price changes.",
    birthCheck: "Please select date of birth",
    City: "* City",
    Personal_item: "Personal item",
    IDexpirationDatePlaceholder: "Select ID expiration date",
    birthPrompt: "Date of birth",
    Refer_to_the_regulations_of_airline: "Refer to the regulations of airline",
    Change_Fee: "Change Fee",
    Cancellation_fee: "Cancellation Fee",
    PremiumEconomy: "Premium Economy",
    Price: "Price",
    person: "/person",
    CustomerCentricSupport: "Customer-Centric support",
    ShowMore: "Show more",
    ChangeFee: "Change Fee",
    IDexpirationDatePrompt: "ID expiration date",
    Save: "Save",
    transfer_in: "Self-transfer in {num}",
    professionalmanner: "Our glocal customer service team is available to assist you with all your requests in a friendly and professional manner.",
    at_least: "At least {num} hours before ",
    passegers: " passeger(s)",
    select_date: "SelectDates",
    Checked_baggage: "Checked baggage",
    PopularCities: "Popular Cities",
    ChangeFlight: "Change Flight",
    Sat: "Sat",
    PassengersInfo: "Passengers lnfo",
    carry_on_baggage_included: "Carry-on baggage included",
    Any: "Any",
    SelectClassPrice: "Select Class and Price",
    Clear: "Clear",
    AddBaggageTips: "Add enough baggage allowance. Now you can bring everything to travel around the world!",
    total: "Total",
    hour: "h",
    Feedback: "Share Your Feedback",
    pay_fail_txt1: "please contact our customer service team.",
    Depart: "Depart",
    ok: "OK",
    ExtensiveRoutes: "Extensive Routes\n",
    included: "included",
    NorthAmerica: "North America",
    Easy_Access: "Easy Access",
    agreedTerms: "I have read and agreed to the following Skytours.com booking Terms & Conditions and\nPrivacy Policy.\n",
    Dec: "Dec",
    Tue: "Tue",
    Change: "Change",
    Farefees: "Taxes & fees",
    insureCopywry: "Smart choice: 85% travellers' preference!",
    not_buy_hint: "You have not chosen any insurance services. Would you like to go back and make a choice?",
    PassengersAddTips: "Children and infants must be accompanied by an adult during the flight.",
    SelectClassPriceTips: "Total for all passengers (incl. taxes and fees)",
    Jan: "Jan",
    non_fefundable: "Cancellation not permitted",
    Partial_included: "Partial-included",
    RefundableBooking: "100% Refundable Booking",
    not_buy: "No thanks, I'll take the risk",
    ServiceChat: "Service Chat",
    cityAirport: "City or Airpor",
    SelectFareTips: "Upgrade your fare package so that you can rebook or receive a refund when you decide to change your plan.",
    non_changeable: "Non-changeable",
};
