export default {
    cancel: "Cancelar",
    BookingDate: "Fecha de reserva",
    nationalityPlaceholder: "Seleccione la nacionalidad",
    Apr: "Abr",
    INNum: "Introduzca su número de identificación",
    onlineCheckIn: "Check-in en línea",
    NoFistNamecheck: "Por favor introduzca su nombre y segundo nombre",
    FlightsInfo: "Información de vuelos",
    Reject: "Rechazar",
    Month: "m",
    protected: "Protegido",
    DelayedBaggageService: "Servicio de equipajes retrasados",
    About_Us_txt22: "El servicio de atención al cliente se presta de varias formas para atender mejor sus necesidades.",
    IDNotice: "Aviso de identificación - Los nombres deben coincidir con el documento de identidad - > Validez de 6 meses",
    About_Us_txt21: "Servicio atento",
    addres_require_select: "Introduzca la dirección",
    FlightDelayedCanceled: "¿Quiere compartir su opinión? ",
    excluding_baggage_allowance: "Excluyendo el equipaje permitido",
    AllLanguages: "Todas los idiomas",
    riskManagement: "Gestión de riesgos",
    Aisle: "Pasillo",
    ShareThoughts: "Comparta su opinión y ayúdenos a mejorar su experiencia dando su opinión en nuestro sitio web.",
    No_thanks: "No, gracias",
    recentSearchesCities: "Búsquedas recientes",
    partially_used_ticket: "Boleto parcialmente utilizado",
    Sun: "Dom",
    defaultKey: "Hora (hora local)",
    seat: "Asiento",
    InfantsTips: "Menores de 2 años en el periodo de viaje",
    Details: "Detalles",
    Passengers: "Pasajeros",
    OtherServices: "Otros servicios",
    all_unused_tickets: "Todos los boletos no utilizados",
    Post_ZIP_Code: "* Código postal",
    NationalityPrompt: "Nacionalidad",
    cardNumber: "Número de tarjeta",
    city_require_select: "Por favor, introduzca la ciudad",
    Sep: "Sep",
    ViewCurrentBaggagePolicy: "Ver la política actual de equipajes",
    before_departure: "Antes de la salida",
    lowest_price: "Precio más bajo",
    country_require_select: "Seleccione un país",
    selected_passegers: "Seleccionados: {num} pasajeros",
    policy_detail: "Los gastos de cambio y cancelación se cobran de acuerdo con las políticas indicadas en el sitio web de la aerolínea.",
    SeatSelection: "Selección de asientos",
    ContactUs: "Póngase en contacto con nosotros",
    Part_included: "Parcialmente incluido",
    Passport: "Pasaporte ",
    PassengersContactInfo: "Pasajeros e información de contacto",
    SecurePayment: "Pago 100% asegurado",
    Adult: "Adulto",
    Stops: "Escalas",
    Changes_not_permitted: "Cambio no permitido",
    free: "Gratis",
    IDNumber: "Número del documento de identidad",
    Window: "Ventanilla",
    Thu: "Jue",
    Jul: "Jul",
    About_Us_txt3: "Debodia International Limited, con domicilio social en 2F, 38 Wong Chuk Hang Road, Wong Chuk Hang, Hong Kong con registro mercantil NO. 2585004.",
    About_Us_txt4: "BIGSKY Grup S.A.U., con domicilio en Avda. Sant Antoni 38, AD400 La Massana, Andorra, con certificado de registro de empresa NO. L-7085322-S.",
    numBaggageChecked: "Añadir equipaje facturado para {num} pasajeros",
    cvv: "CVV",
    CallUs: "Llámenos",
    Jun: "Jun",
    About_Us_txt1: "IWOFLY PTE LTD, con domicilio social en 6 RAFFLES QUAY #16-01, SINGAPUR (048580) con registro mercantil NO. 202338315R.",
    About_Us_txt2: "IWOFLY S.L., con domicilio social en Paseo de las Delicias 30, 7a planta de la localidad de Madrid, 28045 con registro mercantil NO. B88532528.",
    Adultticket: "Billete de adulto",
    About_Us_txt7: "Más de 10 años de experiencia en la venta de billetes de avión en línea B2C, tenemos experiencia en atención al cliente multinacional y ofrecemos servicios en chino, inglés y francés.",
    updatesFlightTips: "Inicie sesión para comprobar las actualizaciones de sus vuelos",
    About_Us_txt8: "Conocemos los puntos débiles de la cadena de ventas de la industria de las tarifas aéreas, con capas de márgenes. Nos comprometemos a ofrecerle el nivel más bajo de precios eliminando a los intermediarios.",
    About_Us_txt5: "¿Por qué elegir Sky-tours.com?",
    businessClass: "Reserva",
    About_Us_txt6: "Más de 30 años de experiencia en billetes de avión B2B con abundantes recursos, proporcionando billetes de avión nacionales e internacionales de más de 40 países, incluidas aerolíneas de servicio completo y compañías de bajo coste.",
    About_Us_txt9: "¿No puede obtener una promoción especial que sólo se puede comprar fuera de línea? ¡Estamos aquí para ofrecerle un trato que no se puede ofrecer en la magnate OTA!",
    Fare: "Tarifa",
    the_price_difference_generated_1: "La diferencia de precio del vuelo de cambio correrá a su cargo. La tasa de cambio se cobrará por persona y por cambio.",
    NoMatchingFlightsFound: "No hay resultados. ¿Por qué no cambia los criterios de búsqueda?",
    MalePlaceholder: "Masculino",
    E_Wallet: "Billetera electrónica",
    the_price_difference_generated_2: "Si su vuelo sufre un cambio de horario debido a factores externos (cambio de horario involuntario), le ofreceremos una solución alternativa de acuerdo con los comentarios de la compañía aérea.",
    price_per: "por pasajero",
    Select: "Seleccione",
    Submit: "Enviar",
    Back_to_select: "Volver a seleccionar",
    to: "Hacia",
    noEnLastNmaecheck: "Por favor introduzca su apellido sólo en inglés y sin caracteres especiales",
    Add: "Agregar",
    Email: "Correo electrónico",
    unpaid_booking_for_same_route: "Reserva no pagada para la misma ruta",
    Pay: "Pagar",
    questionsContactUs: "Si tiene alguna duda, póngase en contacto con nuestro equipo de atención al cliente.",
    pleaseLocation: "Introduzca la ciudad o el aeropuerto",
    premiumEconomy: "Turista superior",
    WhyBookSt: "¿Por qué reservar con Sky-tours?",
    buy_refundable: "Sí, haga que mi reserva sea reembolsable",
    FeedbackCounts: "Su opinión cuenta!",
    Restassured: "Quédese tranquilo con nuestro sistema de pago seguro y nuestras eficaces medidas de control de riesgos que dan prioridad a la protección de sus datos personales y sus pagos.",
    About_Us: "Quiénes somos",
    letDoThis: "Hagamos esto",
    Aug: "Ago",
    fistClass: "Primera clase",
    Search: "Búsqueda",
    LastUpdated: "*Última actualización",
    SeparateSelection: "Selección por separado",
    OurPartners: "Nuestros colaboradores",
    myBooking: "Mis Reservas",
    search_similar_flights: "Buscar vuelos similares",
    Airports: "Aeropuertos",
    SecurityReliability: "Seguridad y confianza",
    kg_per_person: "kg por persona",
    ShowFlights: "Mostrar vuelos",
    province_require_select: "Por favor, introduzca estado/provincia",
    firstName: "Primer Nombre",
    flightsAlerts: "Alertas de vuelos",
    Nov: "Nov",
    each_piece_cannot_exceed: "Cada pieza no puede exceder los {num} cm de tamaño.",
    piece: "pieza",
    nationalityCheck: "Por favor seleccione su nacionalidad",
    please_retry: "Excepción interna del sistema, ¡Por favor, vuelva a intentarlo!",
    General: "General",
    Class: "Clase",
    Adults: "Adultos",
    BookingInstructions: "Instrucciones de reserva para niños y/o Infantes",
    peace_of_mind: "Reserve sus vuelos con toda tranquilidad",
    bookingNo: "Número de reserva",
    FAQ_Q5: "¿Puedo modificar mi información de contacto?",
    Good_scenery: "Buenos paisajes",
    FAQ_Q4: "¿Se puede cambiar o cancelar mi billete?",
    delete_all_records: "¿Está seguro de eliminar todos los registros?",
    FAQ_Q1: "¿Cómo encontrar mi pedido?",
    FAQ_Q3: "¿Cómo comprar equipaje?",
    FAQ_Q2: "¿Cómo confirmar si el billete se ha emitido correctamente?",
    CancellationFee: "Tasa de cancelación",
    Time: "Hora",
    buy_bags: "Sí, por favor rastrea mis maletas",
    State_Province: "* Estado/Provincia",
    Continue: "Continuar",
    alter_prices: "La compañía aérea ha cambiado el precio de este vuelo.",
    travelDreamsRunWild: "Regístrese hoy mismo y déjese llevar por sus sueños de viajar.",
    Checked_baggage_included: "Equipaje facturado incluido",
    CheckIn2: "Facilite un acceso rápido a su vuelo sin tener que aguardar colas en el aeropuerto.",
    expiryDate: "Fecha de caducidad",
    FAQ_A5: "Si los pasajeros proporcionaron direcciones de correo electrónico o números de teléfono incorrectos al hacer la reserva, pueden solicitar la modificación de la información a más tardar 48 horas antes de la salida. Los pasajeros deben enviar correos electrónicos a support{'@'}sky-tours.com y proporcionar la información correcta.",
    duration: "Duración",
    CheckIn1: "La tarjeta de embarque será enviada 24 horas antes de la salida.",
    FAQ_A4: "Las reglas de cambio y cancelación de cada boleto varían de acuerdo a las reglas de las diferentes aerolíneas y clases de cabina. Cuando compra un boleto, las reglas específicas de cambio y cancelación se muestran en el lado derecho de la página de reserva. Después de completar su reserva, también puede consultar las reglas de cambio y cancelación del boleto que compró en \"Mis Reservas\".",
    LeaveFeedback: "Deja tus comentarios",
    CheckIn3: "Evita la elevada tasa de facturación en el mostrador",
    FAQ_A1: "Cuando realiza con éxito un pedido en Sky-tours, el sistema enviará automáticamente un correo electrónico con el número de pedido a su dirección de correo electrónico reservada. Puede hacer clic en \"Mis Reservas\" en la esquina superior derecha de la página de inicio del sitio web de Sky-tours, ingresar el número de pedido y su dirección de correo electrónico reservada, y luego podrá encontrar su pedido.\nSi no recibe el correo electrónico de notificación, primero revise su carpeta de correo no deseado. Si no está en la carpeta de correo no deseado, es posible que haya ingresado una dirección de correo electrónico incorrecta al hacer la reserva. En este caso, comuníquese con nuestro equipo de atención al cliente a tiempo para ayudarlo a modificarlo.",
    Language: "Idioma",
    FAQ_A3: "Sky-tours puede ayudarlo a comprar la franquicia de equipaje facturado de la mayoría de las aerolíneas. De acuerdo con las regulaciones de las aerolíneas, las diferentes rutas tienen diferentes piezas de equipaje, pesos y precios. Puede comprar el equipaje junto con su reserva. Si desea comprar equipaje adicional después de realizar un pedido, comuníquese con nosotros y le notificaremos la tarifa correspondiente. Si está de acuerdo con la tarifa, le enviaremos un enlace de pago por correo electrónico. Después de su pago, lo manejaremos lo antes posible y le enviaremos el resultado por correo electrónico.\nTenga en cuenta: Nuestro equipo de Atención al Cliente solo se comunicará con usted a través de la dirección de correo electrónico support{'@'}sky-tours.com. Por la seguridad de sus comunicaciones y fondos, no confíe en las notificaciones de pago de ninguna otra dirección de correo electrónico.",
    InfantsTicket: "Billete de bebé en el regazo",
    FAQ_A2: "Su boleto ha sido emitido con éxito si recibe un correo electrónico de tickets{'@'}sky-tours.com que indica que su pedido está \"ENTRADO\" con su número de boleto.\nSi no ha recibido el correo electrónico de notificación \"TICKETED\" 72 horas después de realizar un pedido, verifique primero su carpeta de correo no deseado. Si está seguro de que no ha recibido el correo electrónico de notificación o necesita otra ayuda, no dude en ponerse en contacto con nuestro equipo de atención al cliente en cualquier momento.",
    Policies_Baggage: "Políticas y equipajes",
    recommendedCheapFlights: "Vuelos económicos recomendados",
    Children: "Niños",
    non_refundable: "No reembolsable",
    lowestPricedTips: "¡El vuelo más económico saliendo en el próximo mes! ",
    fistNamePrompt: "Primer y segundo nombre",
    Return: "Vuelta",
    payment_failed: "¡Pago fallido!",
    ticket: "boleto",
    MobilePhoneTips: "Por favor indique un número de teléfono",
    AddSeat: "Añadir asientos una vez realizada la reserva resulta más caro!",
    stop1: "1 escala",
    riskInfo: "Necesitamos que nos facilite la siguiente información para pasar la verificación del pago.",
    INNumCheck: "Por favor introduzca su número de identificación",
    About_Us_txt20: "La seguridad de sus datos personales está garantizada.",
    BusinessClass: "Reserva",
    futureAdventures: "Contenido de viajes para inspirar futuras aventuras.",
    cardholder: "Nombre del titular",
    Mon: "Lun",
    Checked: "Comprobado",
    About_Us_txt19: "Pago seguro",
    TermsConditions: "Términos y condiciones",
    About_Us_txt18: "Las rutas de vuelo cubren más de 200 países y los precios son muy competitivos",
    TickeTpricesTips: "Búsqueda de vuelos",
    notIncluded: "no incluido",
    Asia: "亞洲",
    FAQ: "FAQ",
    Within: "Dentro de {num} horas antes",
    priceRise: "Cambio de precio",
    About_Us_txt11: "Mientras las compañías aéreas ofrezcan reembolso/cancelación involuntaria gratuita, nosotros también le ofreceremos un servicio gratuito sin condiciones.",
    About_Us_txt10: "Cada cliente será atendido con una solución cálida y de alta calidad. No respuestas robotizadas, sino soluciones específicas.",
    stop2: "Más de 2 escalas",
    About_Us_txt13: "Damos alas a tu vuelo",
    About_Us_txt12: "Sky-tours.com se convertirá en su socio personal de viajes en línea y hará que sus alas viajen por todo el mundo.",
    Fri: "Vie",
    About_Us_txt15: "Información de contacto",
    noLastNamecheck: "Por favor introduzca su apellido",
    About_Us_txt14: "Más conexiones, más opciones, más económico",
    About_Us_txt17: "Rutas variadas",
    About_Us_txt16: "Si tiene alguna pregunta, no dude en ponerse en contacto con nuestro equipo de atención al cliente y estaremos a su servicio 24/7 .",
    PriceDetails: "Detalles del precio",
    birthPlaceholder: "Seleccione la fecha de nacimiento",
    book_now: "Reserva ahora antes de que suba aún más.",
    Oct: "Oct",
    copyright: "{'@'} 2024 Sky-tours.com Todos los derechos reservados",
    StopoverCity: "Ciudad de escala",
    Policies: "Políticas",
    Address: "* Dirección",
    IDexpirationDateCheck: "Por favor seleccione la fecha de vencimiento del documento de identidad",
    offeringHighly: "Nuestra red de vuelos abarca más de 200 países y ofrece precios muy ventajosos para su comodidad.",
    PleaseCompletePayment: "Por favor, complete su pago dentro de",
    NameGuidelines: "Pautas de nombres",
    oneWay: "Sólo ida",
    required: "Campo obligatorio",
    PaymentMethods: "Métodos de pago",
    after_departure: "Después de la salida",
    WishingpleasantJourney: "Le deseamos un buen viaje.",
    PaymentProgress: "Pago seguro",
    info_safe: "¡Sky-tours protegerá su viaje y mantendrá su información segura!",
    lastNamePlaceholder: "por ejemplo CLINTON",
    ContactInfo: "Información de contacto",
    SittingTogether: "Sentados juntos",
    ID: "Documento de identidad",
    enter: "Ingresar",
    ServicesAdded: "Servicios añadidos",
    PaymentSuccessful: "Pago exitoso",
    Added: "Agregado",
    Recommended: "Recomendados",
    post_ZIP_Code_require_select: "Introduzca el código postal",
    seatCompletedTxt: "pasajero(s) no ha(n) seleccionado asientos. ¿Desea volver a reservar asientos?",
    enterEmailAdress: "Introduzca su correo electrónico",
    Carry_on_baggage: "Equipaje de mano",
    baggageAllowanceAndPolicies: "Equipaje permitido y política",
    risk_control_rejected: "Control de riesgos rechazado",
    all_airports: "Todos los aeropuertos",
    price_rise: "Subida de precios",
    Wed: "Mié",
    Country: "* País",
    pay_fail_txt: "Si tienes alguna pregunta,",
    enterNameExactly: "Asegúrese de introducir el nombre exactamente como aparece en el documento de identidad que se utilizará al registrarse",
    Mar: "Mar",
    Hide: "Ocultar",
    lastName: "Apellido",
    StayInspired: "Manténgase inspirado",
    unknow: "detalles",
    May: "May",
    Cancel: "Cancelar",
    add_insurance: "Añadir seguro",
    privacy3: "Política de privacidad",
    Confirm: "confirmar",
    privacy2: "Lee más sobre nuestra política de cookies aquí.",
    privacy1: "Utilizamos cookies técnicas, analíticas y de marketing para ayudarle, por ejemplo, a iniciar sesión a continuar su búsqueda donde la dejó.",
    completeSubmission: "Por favor, complete el envío dentro de",
    About_Us_txt: "Este sitio web está gestionado conjuntamente por las siguientes empresas:",
    privacy4: "Cerrar o ignorar el aviso de banner significa que acepta el uso de cookies esenciales en su dispositivo o navegador.",
    Hide_2_transfers: "Ocultar vuelos con más de 2 transbordos",
    Economy: "Tuirsta",
    Airlines: "Aerolíneas",
    check34: "El primer y segundo nombre superan los 34 caracteres por favor revise o póngase en contacto con el servicio de atención al cliente para obtener ayuda",
    NonstopOnly: "Sólo sin escalas",
    CheckIn: "Check-in",
    roundTrip: "Ida y vuelta",
    pieces_per_person: "piezas por persona",
    Feb: "Feb",
    kg_per_piece: "kg por pieza",
    reminder: "Recordatorio",
    CurrentLanguage: "Idioma actual",
    gotit: "Confirmado",
    SeatSelectionTips: "Seleccione su asiento preferido para un viaje más cómodo.",
    bookingEmail: "Correo electrónico de confirmación de reserva",
    AddBaggage: "Añadir equipaje",
    totallyBaggagePrice: "{num} pieza(s) {weigh} kg totalmente",
    AdditionalServices: "Servicios adicionales",
    check29: "El apellido tiene más de 29 caracteres por favor revise o póngase en contacto con el servicio de atención al cliente para obtener ayuda",
    SeatSelectionTipss: "Haremos todo lo posible por satisfacer sus preferencias de selección. Si no hay plazas disponibles, negociaremos o le devolveremos el dinero lo antes posible. (Asegúrese de que la dirección de correo electrónico y el número de teléfono de contacto son correctos).",
    offer_time: "Horario de trabajo: 9:00~18:00 (GMT+08), Lun-Dom",
    CustomerSupport: "Atención al cliente",
    AddPassengers: "Añadir pasajeros",
    contactEmailEnter: "Por favor introduzca su correo electrónico de contacto",
    BaggageAllowance: "Permiso de equipaje",
    SelectFare: "Seleccione la tarifa",
    None: "Ninguno",
    IDTypePromptCheck: "Por favor seleccione el tipo de documento",
    Tips: "Consejos",
    change_to_airport: "{num} Cambio a otro aeropuerto",
    GenderPrompt: "Género",
    CustomerService: "24/7 Servicio de atención al cliente",
    Done: "Confirmar",
    FemalePlaceholder: "Femenino",
    ChildrenTips: "2-11 años en el periodo de viaje",
    firstNamePlaceholder: "por ejemplo WILLIAM JEFFERSON",
    IDTypePrompt: "Tipo de documento de identidad",
    Infants: "Infantes",
    system_processing: "Error del sistema, inténtelo de nuevo",
    MobilePhone: "Número de móvil",
    noEncheck: "Por favor introduzca su primer y segundo nombre sólo en inglés y sin caracteres especiales",
    Childticket: "Billete de niño",
    please_enter_ID_info: "Por favor, ingrese la información de su documento de identidad",
    Filters: "Filtros",
    Random: "Asiento aleatorio",
    Cancellation_Fee: "Tarifa de cancelación",
    continue_booking: "Continuar con la reserva",
    numSelected: "de {passegersnum} seleccionados",
    from: "Desde {num}",
    credit: "Tarjeta de crédito/débito",
    Reset: "Reiniciar",
    Baggage: "Equipaje",
    INNumCheckDigits: "El número de documento tiene entre 5 y 15 dígitos o letras",
    payNow: "Paga ahora",
    Accept: "Aceptar",
    Europe: "歐洲",
    NoThanks: "No, gracias",
    avoid_price_change: "para evitar cambios en el precio.",
    birthCheck: "Por favor seleccione una fecha de nacimiento",
    City: "* Ciudad",
    Personal_item: "Artículo personal",
    IDexpirationDatePlaceholder: "Seleccione la fecha de vencimiento del documento de identidad",
    birthPrompt: "Fecha de nacimiento",
    Refer_to_the_regulations_of_airline: "Consulte las normas de la compañía aérea",
    Change_Fee: "Tarifa de cambio",
    Cancellation_fee: "Tarifa de cancelación",
    PremiumEconomy: "Turista superior",
    Price: "Precio",
    person: "/Persona",
    CustomerCentricSupport: "Asistencia centrada en el cliente",
    ShowMore: "Mostrar más",
    ChangeFee: "Tasa de cambio",
    IDexpirationDatePrompt: "Fecha de vencimiento del documento de identidad",
    transfer_in: "Autotransferencia en {num}",
    professionalmanner: "Nuestro equipo global de atención al cliente está a su disposición para ayudarle  con todas sus peticiones de forma amable y profesional.",
    at_least: "Al menos {num} horas antes",
    passegers: "pasajero(s)",
    select_date: "SeleccioneFechas",
    Checked_baggage: "Comprobado",
    PopularCities: "熱門城市",
    ChangeFlight: "Cambio de vuelo",
    Sat: "Sáb",
    PassengersInfo: "Información sobre los pasajeros",
    carry_on_baggage_included: "Equipaje de mano incluido",
    Any: "Cualquiera",
    SelectClassPrice: "Seleccione clase y precio",
    Clear: "Eliminar",
    AddBaggageTips: "Añade la cantidad suficiente de equipaje. ¡Ahora puedes llevarte todo para viajar por el mundo!",
    total: "Total",
    hour: "h",
    Feedback: "Comparta su opinión",
    pay_fail_txt1: "póngase en contacto con nuestro equipo de atención al cliente.",
    Depart: "Ida",
    ok: "De acuerdo",
    ExtensiveRoutes: "Rutas de gran extensión",
    included: "incluido",
    NorthAmerica: "北美洲",
    Easy_Access: "Fácil acceso",
    agreedTerms: "He leído y acepto los siguientes Términos y Condiciones de reserva de Skytours.com y la Política de privacidad.",
    Dec: "Dic",
    Tue: "Mar",
    Change: "Cambio",
    Farefees: "Impuestos y tasas",
    insureCopywry: "Elección acertada: ¡la opción más deseada por el 85% de los viajeros!",
    not_buy_hint: "No ha elegido ningún servicio de seguros. ¿Le gustaría volver atrás y hacer una elección?",
    PassengersAddTips: "Los niños e infantes deben ir acompañados de un adulto durante el vuelo.",
    SelectClassPriceTips: "Total para todos los pasajeros (impuestos y tasas incluidos)",
    Jan: "Ene",
    non_fefundable: "Cancelación no permitida",
    Partial_included: "Parcialmente incluido",
    RefundableBooking: "Reserva 100% reembolsable",
    not_buy: "No gracias, me arriesgaré",
    ServiceChat: "Servicio de Chat",
    cityAirport: "Ciudad o aeropuerto",
    SelectFareTips: "Actualice su paquete de tarifas para poder volver a reservar o recibir un reembolso cuando decida cambiar de plan.",
    non_changeable: "No modificable",
};
