export default {
    About_Us_txt3: "Debodia International Limited, adresse 2F, 38 Wong Chuk Hang Road, Wong Chuk Hang, Hong Kong avec le numéro d'enregistrement NO. 2585004.",
    About_Us_txt4: "BIGSKY Grup S.A.U., domicilié à Avda. Sant Antoni 38, AD400 La Massana, Andorre, avec le registre des certificats d'entreprise NO. L-7085322-S.",
    About_Us_txt1: "IWOFLY PTE LTD, dont l'adresse est 6 RAFFLES QUAY #16-01, SINGAPORE (048580) et dont le numéro d'enregistrement est NO. 202338315R.",
    About_Us_txt2: "IWOFLY S.L., Paseo de las Delicias 30, 7a planta de la localidad de Madrid, 28045 avec le numéro d'enregistrement NO. B88532528.",
    About_Us_txt7: "Plus de 10 ans d'expérience dans la vente en ligne de billets d'avion B2C, nous avons l'expérience d'un service client multinational et fournissons des services en chinois, anglais et français.",
    About_Us_txt8: "Nous connaissons les points douloureux de la chaîne de vente de l'industrie des billets d'avion, qui se compose de plusieurs couches de marges. Nous nous engageons à vous fournir les prix les plus bas en supprimant les intermédiaires.",
    About_Us_txt5: "Pourquoi choisir Sky-tours.com ?",
    About_Us_txt6: "Plus de 30 ans d'expérience dans le domaine des billets d'avion B2B avec de riches ressources, fournissant des billets d'avion nationaux et internationaux de plus de 40 pays, y compris des compagnies aériennes à service complet et des transporteurs à bas prix.",
    About_Us_txt: "Ce site web est géré conjointement par les sociétés suivantes :",
    About_Us_txt9: "Vous ne savez pas où obtenir une promotion spéciale qui ne peut être achetée que hors ligne ? Nous sommes là pour vous offrir un traitement qui ne peut pas être proposé par les tycoons de l'OTA !",
    buy_bags: "Oui, s'il vous plaît, suivez mes bagages",
    About_Us: "A propos de nous",
    offer_time: "Horaires de travail: 9:00-18:00 (GMT+08),Lun - Dim",
    About_Us_txt11: "Tant que les compagnies aériennes offrent un service gratuit de remboursement/annulation involontaire, nous vous offrons également un service gratuit sans conditions.",
    About_Us_txt10: "Chaque client sera servi par une solution chaleureuse et de haute qualité. Pas de réponses robotisées, mais des solutions ciblées.",
    About_Us_txt12: "Sky-tours.com deviendra votre partenaire personnel de voyage en ligne et vous donnera des ailes pour voyager dans le monde entier.",
    not_buy: "Non merci, je prends le risque",
    About_Us_txt15: "Informations sur le contact",
};
