export default {
    cancel: "Annulla",
    BookingDate: "Data di prenotazione",
    nationalityPlaceholder: "Seleziona nazionalità",
    Apr: "Apr",
    INNum: "Inserisci il numero ID",
    onlineCheckIn: "Check-in online",
    NoFistNamecheck: "Inserisci il nome e il secondo nome",
    FlightsInfo: "Informazioni sui voli",
    Reject: "Rifiutare",
    Month: "m",
    protected: "Protetto",
    DelayedBaggageService: "Servizio bagagli in ritardo",
    About_Us_txt22: "Il servizio clienti viene fornito in varie modalità per meglio rispondere alle vostre esigenze.",
    IDNotice: "Avviso ID • I nomi devono corrispondere allID • > Validità di 6 mesi",
    About_Us_txt21: "Servizio attento",
    addres_require_select: "Inserire l'indirizzo",
    FlightDelayedCanceled: "Avete pensieri da condividere? ",
    excluding_baggage_allowance: "Esclusa la franchigia bagaglio",
    AllLanguages: "Tutte le lingue",
    riskManagement: "Gestione del rischio",
    Aisle: "Posto lato corridoio",
    ShareThoughts: "Condividi i tuoi pensieri e aiutaci a migliorare la tua esperienza fornendo feedback sul nostro sito Web.",
    No_thanks: "No, grazie",
    recentSearchesCities: "Ricerche recenti",
    partially_used_ticket: "Biglietti parzialmente utilizzati",
    Sun: "Dom",
    defaultKey: "Ora (ora locale)",
    seat: "Posto a sedere",
    InfantsTips: "Meno di 2 anni al momento del viaggio",
    Details: "Dettagli",
    Passengers: "Passeggeri",
    OtherServices: "Altri Servizi",
    all_unused_tickets: "Tutti i biglietti non utilizzati",
    Post_ZIP_Code: "* Codice postale",
    NationalityPrompt: "Nazionalità",
    cardNumber: "Numero della carta",
    city_require_select: "Inserire la città",
    Sep: "Set",
    ViewCurrentBaggagePolicy: "Visualizza la politica sui bagagli attuale",
    before_departure: "Prima della partenza",
    lowest_price: "Prezzo più basso",
    country_require_select: "Selezionare un paese",
    Infant: "Neonato",
    selected_passegers: "Selezionato: {num} passegger",
    policy_detail: "*Le spese di modifica e cancellazione vengono addebitate in base alle politiche elencate sul sito web della compagnia aerea.",
    SeatSelection: "Selezione del Posto",
    ContactUs: "Contattaci",
    Part_included: "Parzialmente incluso",
    Passport: "Passaporto",
    PassengersContactInfo: "Passeggeri e informazioni di contatto",
    SecurePayment: "Pagamento sicuro al 100%",
    Adult: "Adulto",
    Stops: "Fermate",
    Changes_not_permitted: "Modifica non consentita",
    free: "Gratuito",
    IDNumber: "Numero identificativo",
    Window: "Posto al finestrino",
    Thu: "Gio",
    Jul: "Lug",
    About_Us_txt3: "Debodia International Limited, indirizzo 2F, 38 Wong Chuk Hang Road, Wong Chuk Hang, Hong Kong, registro delle imprese NO. 2585004.",
    About_Us_txt4: "BIGSKY Grup S.A.U., indirizzo Avda. Sant Antoni 38, AD400 La Massana, Andorra, con certificato societario NO. L-7085322-S.",
    numBaggageChecked: "Aggiungi il bagaglio registrato per {num} passeggeri",
    cvv: "CVV",
    CallUs: "Chiamaci",
    Jun: "Giu",
    About_Us_txt1: "IWOFLY PTE LTD, indirizzo 6 RAFFLES QUAY #16-01, SINGAPORE (048580) con registro aziendale NO. 202338315R.",
    About_Us_txt2: "IWOFLY S.L., all'indirizzo Paseo de las Delicias 30, 7a planta de la localidad de Madrid, 28045 con registro aziendale NO. B88532528.",
    Adultticket: "Biglietto per adulti",
    About_Us_txt7: "Oltre 10 anni di esperienza nel settore dei biglietti aerei online B2C, con un servizio clienti multinazionale e servizi in lingua cinese, inglese e francese.",
    updatesFlightTips: "Accedi per controllare gli aggiornamenti sui voli",
    About_Us_txt8: "Conosciamo i punti dolenti della catena di vendita dell'industria dei biglietti aerei, fatta di strati di ricarichi. Ci impegniamo a fornirvi i prezzi più bassi eliminando gli intermediari.",
    About_Us_txt5: "Perché scegliere Sky-tours.com?",
    businessClass: "Business class",
    About_Us_txt6: "Più di 30 anni di esperienza nel settore B2B dei biglietti aerei, con risorse ricche, che forniscono biglietti aerei nazionali e internazionali da più di 40 paesi, comprese le compagnie aeree a servizio completo e i vettori low cost.",
    About_Us_txt9: "Dove trovare una promozione speciale che può essere acquistata solo offline? Siamo qui per offrirvi un trattamento che non può essere offerto nelle OTA dei magnati!",
    Fare: "Tariffa",
    the_price_difference_generated_1: "La differenza di prezzo per il cambio di volo è a carico del passeggero. La tassa di cambio viene addebitata per persona e per cambio.",
    NoMatchingFlightsFound: "Nessun risultato corrispondente. Vuoi modificare i criteri di ricerca?",
    MalePlaceholder: "Maschio",
    E_Wallet: "Portafoglio elettronico",
    the_price_difference_generated_2: "Se il volo subisce un cambiamento di orario a causa di fattori esterni (cambio di orario involontario), vi offriremo una soluzione alternativa in base al feedback della compagnia aerea. ",
    price_per: "per passeggero",
    Select: "Seleziona",
    Submit: "Invio",
    Back_to_select: "Torna a selezionare",
    to: "a",
    noEnLastNmaecheck: "Inserisci il cognome solo in inglese senza caratteri speciali",
    Add: "Aggiungi",
    Email: "E-mail",
    Pay: "Paga",
    questionsContactUs: "Se avete domande, contattate il nostro servizio clienti.",
    pleaseLocation: "Inserisci la città o l'aeroporto",
    premiumEconomy: "Premium Economy",
    WhyBookSt: "Perché prenotare con Sky-tours?",
    buy_refundable: "Sì, rendere la mia prenotazione rimborsabile",
    FeedbackCounts: "Il tuo Feedback Conta!",
    Restassured: "Stai tranquillo con il nostro sistema di pagamento sicuro e solide misure di controllo rischi per dare priorità alla protezione delle tue informazioni personali e dei tuoi pagamenti.",
    About_Us: "Informazioni su di noi",
    letDoThis: "Facciamolo",
    Aug: "Ago",
    fistClass: "Prima classe",
    Search: "Cerca",
    LastUpdated: "*Ultimo aggiornamento",
    SeparateSelection: "Selezione separata",
    OurPartners: "Nostri partner",
    myBooking: "Le Mie Prenotazioni",
    search_similar_flights: "Cerca voli simili",
    Airports: "Aeroporti",
    SecurityReliability: "Sicurezza e Affidabilità",
    kg_per_person: "kg per persona",
    ShowFlights: "Mostra Voli",
    province_require_select: "Inserire stato/provincia",
    firstName: "Nome",
    flightsAlerts: "Avvisi voli",
    Nov: "Nov",
    each_piece_cannot_exceed: "Ogni pezzo non può superare la dimensione di {num} cm.",
    piece: "pezzo",
    nationalityCheck: "Seleziona la nazionalità",
    please_retry: "Eccezione interna al sistema, riprovare!",
    General: "Generale",
    Class: "Classe",
    Adults: "Adulti",
    BookingInstructions: "Istruzioni per la prenotazione per bambini/neonati",
    peace_of_mind: "Prenotate i vostri voli in tutta tranquillità",
    bookingNo: "Prenotazione n.",
    FAQ_Q5: "Posso modificare le mie informazioni di contatto?",
    Good_scenery: "Un buon paesaggio",
    FAQ_Q4: "Il mio biglietto può essere modificato o annullato?",
    delete_all_records: "Sei sicuro di voler cancellare tutti i record?",
    FAQ_Q1: "Come trovare il mio ordine?",
    FAQ_Q3: "Come acquistare il bagaglio?",
    FAQ_Q2: "Come confermare se il biglietto è stato emesso correttamente?",
    CancellationFee: "Tassa di cancellazione",
    privacy: "Teniamo alla vostra privacy",
    Time: "Tempo",
    buy_bags: "Sì, per favore traccia i miei bagagli",
    State_Province: "* Stato/Provincia",
    Continue: "Continua",
    alter_prices: "La compagnia aerea ha modificato il prezzo di questo volo.",
    travelDreamsRunWild: "Iscriviti oggi e lascia scatenare i tuoi sogni di viaggio.",
    Checked_baggage_included: "Bagaglio registrato incluso",
    CheckIn2: "Facilita una rapida procedura di imbarco sul tuo volo evitando la necessità di aspettare in coda in aeroporto.",
    expiryDate: "Data di scadenza",
    FAQ_A5: "Se i passeggeri hanno fornito indirizzi e-mail o numeri di telefono errati al momento della prenotazione, possono richiedere la modifica delle informazioni entro e non oltre 48 ore prima della partenza. I passeggeri devono inviare e-mail a support{'@'}sky-tours.com e fornire le informazioni corrette.",
    duration: "Durata",
    CheckIn1: "La carta dimbarco ti verrà inviata entro 24 ore prima della partenza.",
    FAQ_A4: "Le regole di modifica e cancellazione di ciascun biglietto variano in base alle diverse regole della compagnia aerea e alle classi di cabina. Quando acquisti un biglietto, le specifiche regole di modifica e cancellazione vengono visualizzate sul lato destro della pagina di prenotazione. Dopo aver completato la prenotazione, puoi anche controllare le regole di modifica e cancellazione del biglietto che hai acquistato in \"Le Mie Prenotazioni\".",
    LeaveFeedback: "Lasciate un feedback",
    CheckIn3: "Evita la costosa tariffa del check-in al banco.",
    FAQ_A1: "Quando effettui correttamente un ordine su Sky-tours, il sistema invierà automaticamente un'e-mail contenente il numero dell'ordine all'indirizzo e-mail riservato. Puoi fare clic su \"Le Mie Prenotazioni\" nell'angolo in alto a destra della home page del sito Web di Sky-tours, inserire il numero dell'ordine e il tuo indirizzo e-mail riservato, quindi puoi trovare il tuo ordine.\nSe non ricevi l'e-mail di notifica, controlla prima la cartella della posta indesiderata. Se non è nella cartella della posta indesiderata, forse hai inserito l'indirizzo email sbagliato al momento della prenotazione. In questo caso, ti preghiamo di contattare il nostro team di assistenza clienti in tempo per aiutarti a modificarlo.",
    Language: "Lingua",
    FAQ_A3: "Sky-tours può aiutarti ad acquistare la franchigia bagaglio registrato della maggior parte delle compagnie aeree. Secondo i regolamenti delle compagnie aeree, rotte diverse hanno bagagli, pesi e prezzi diversi. Puoi acquistare il bagaglio insieme alla tua prenotazione. Se desideri acquistare un bagaglio extra dopo aver effettuato un ordine, contattaci e ti comunicheremo la tariffa corrispondente. Se sei d'accordo con la commissione, ti invieremo un link di pagamento via e-mail. Dopo il pagamento, lo gestiremo al più presto e ti invieremo il risultato via e-mail.\nNota: il nostro team del servizio clienti ti contatterà solo tramite l'indirizzo e-mail support{'@'}sky-tours.com. Per la sicurezza delle tue comunicazioni e dei tuoi fondi, non fidarti delle notifiche di pagamento provenienti da altri indirizzi email.",
    InfantsTicket: "Biglietto per neonati in braccio",
    FAQ_A2: "Il tuo biglietto è stato emesso con successo se ricevi un'email da tickets{'@'}sky-tours.com che indica che il tuo ordine è \"TICKETED\" con il tuo numero di biglietto.\nSe non hai ricevuto l'e-mail di notifica \"TICKETED\" 72 ore dopo aver effettuato un ordine, controlla prima la cartella della posta indesiderata. Se sei sicuro di non aver ricevuto l'e-mail di notifica o di aver bisogno di altra assistenza, non esitare a contattare il nostro team di assistenza clienti in qualsiasi momento.",
    Policies_Baggage: "Politiche e Bagagli",
    recommendedCheapFlights: "Voli economici consigliati",
    Children: "Bambini",
    non_refundable: "Non rimborsabile",
    lowestPricedTips: "Il volo più economico in partenza entro un mese!",
    fistNamePrompt: "Nome e secondo nome",
    Return: "Ritorno",
    payment_failed: "Pagamento fallito!",
    ticket: "biglietto",
    MobilePhoneTips: "Fornisci un numero di telefono",
    AddSeat: "Laggiunta di posti dopo la prenotazione solitamente costa di più!",
    stop1: "1 scalo",
    riskInfo: "È necessario fornire le seguenti informazioni per superare la verifica del pagamento.",
    INNumCheck: "Inserisci il numero ID",
    About_Us_txt20: "La sicurezza dei vostri dati personali è garantita.",
    BusinessClass: "Business class",
    futureAdventures: "Contenuti di viaggio curati per ispirare avventure future.",
    cardholder: "Nome del titolare carta",
    Mon: "Lun",
    Checked: "Imbarcato",
    About_Us_txt19: "Pagamento sicuro",
    TermsConditions: "Termini & Condizioni",
    About_Us_txt18: "Le rotte di volo coprono oltre 200 paesi e i prezzi sono altamente competitivi.",
    TickeTpricesTips: "Ricerca di voli",
    notIncluded: "0.0",
    Asia: "Asia",
    FAQ: "FAQ",
    Within: "Entro {num} ore prima ",
    priceRise: "Variazione di prezzo",
    About_Us_txt11: "Finché le compagnie aeree offriranno un rimborso/cancellazione involontaria gratuita, anche noi vi offriremo un servizio gratuito e senza condizioni.",
    About_Us_txt10: "Ogni cliente sarà assistito da soluzioni calorose e di alta qualità. Nessuna risposta robotica, ma soluzioni mirate.",
    stop2: "2+ scali",
    About_Us_txt13: "Creiamo le vostre ali",
    About_Us_txt12: "Sky-tours.com diventerà il vostro partner di viaggio online personale e metterà le ali ai vostri viaggi in tutto il mondo.",
    Fri: "Ven",
    About_Us_txt15: "Informazioni di contatto",
    noLastNamecheck: "Inserisci il cognome",
    About_Us_txt14: "Più connettività, più scelta, più conveniente",
    About_Us_txt17: "Rotte ricche",
    About_Us_txt16: "Per qualsiasi domanda, non esitate a contattare il nostro servizio clienti e saremo a vostra disposizione 24 ore su 24, 7 giorni su 7.",
    PriceDetails: "Dettagli prezzo",
    birthPlaceholder: "Seleziona la data di nascita",
    book_now: "Prenotate ora prima che il prezzo salga ancora di più.",
    Oct: "Ott",
    copyright: "{'@'} 2024 Sky-tours.com Tutti i diritti riservati",
    StopoverCity: "Città di scalo",
    Policies: "Politiche",
    Address: "* Indirizzo",
    IDexpirationDateCheck: "Seleziona la data di scadenza dellID",
    offeringHighly: "La nostra rete di voli copre oltre 200 paesi e offre prezzi altamente competitivi per la tua comodità.",
    PleaseCompletePayment: "Completare il pagamento entro",
    NameGuidelines: "Linee guida sui nomi",
    oneWay: "Solo andata",
    required: "Campo obbligatorio",
    PaymentMethods: "Modalità di Pagamento",
    after_departure: "Dopo la partenza",
    WishingpleasantJourney: "Vi auguriamo un buon viaggio!",
    PaymentProgress: "Pagamento sicuro",
    info_safe: "Sky-tours proteggerà il vostro viaggio e terrà al sicuro le vostre informazioni!",
    lastNamePlaceholder: "ad esempio CLINTON",
    ContactInfo: "Informazioni di contatto",
    Sameselection: "Stessa selezione per tutti i {num} passeggeri",
    SittingTogether: "Seduti insieme",
    ID: "DOCUMENTO D'IDENTITÀ",
    enter: "Inserisci",
    ServicesAdded: "Servizi aggiunti",
    PaymentSuccessful: "Pagamento riuscito!",
    Child: "Bambino",
    Added: "Aggiunto",
    Recommended: "Consigliato",
    post_ZIP_Code_require_select: "Inserire il codice postale",
    seatCompletedTxt: "i passeggeri non hanno selezionato i posti. Desidera tornare a prenotare i posti?",
    enterEmailAdress: "Inserisci il tuo indirizzo email",
    Carry_on_baggage: "Bagaglio a mano",
    baggageAllowanceAndPolicies: "Franchigia bagaglio e politiche",
    risk_control_rejected: "Controllo dei rischi rifiutato",
    all_airports: "Tutti gli aeroporti",
    price_rise: "Aumento del prezzo",
    Wed: "Mer",
    Country: "* Paese",
    pay_fail_txt: "Se avete domande, ",
    enterNameExactly: "Assicurati di inserire il nome esattamente come appare sullID che verrà utilizzato al momento del check-in",
    Mar: "Mar",
    Hide: "Nascondi",
    lastName: "Cognome",
    StayInspired: "Resta ispirato",
    unknow: "dettagli",
    May: "Mag",
    Cancel: "annullare",
    add_insurance: " Aggiungi l'assicurazione ",
    privacy3: "Informativa sulla privacy",
    Confirm: "Confermare",
    privacy2: "Per saperne di più sulla nostra prassi in materia di cookie, cliccate qui",
    privacy1: "Utilizziamo cookie tecnici, analitici e di marketing per aiutarvi, ad esempio, a effettuare il login e a riprendere la ricerca da dove l'avete interrotta.",
    completeSubmission: "Si prega di completare l'invio entro",
    About_Us_txt: "Questo sito web è gestito congiuntamente dalle seguenti società:",
    privacy4: "Chiudere o ignorare il banner significa accettare l'uso dei cookie essenziali sul proprio dispositivo o browser.",
    Hide_2_transfers: "Nascondi i voli con più di 2 trasferimenti",
    Economy: "Economia",
    Airlines: "Compagnie aeree",
    check34: "Il nome e il secondo nome superano i 34 caratteri modificali o contatta lassistenza clienti per ricevere assistenza",
    NonstopOnly: "Solo diretto",
    CheckIn: "Check-in",
    roundTrip: "Andata e ritorno",
    pieces_per_person: "pezzi per persona",
    Feb: "Feb",
    kg_per_piece: "kg per pezzo",
    reminder: "Promemoria",
    more: "Di più",
    CurrentLanguage: "Lingua corrente",
    gotit: "Gotit",
    SeatSelectionTips: "Seleziona il tuo posto preferito per un viaggio confortevole.",
    bookingEmail: "E-mail per la conferma della prenotazione",
    AddBaggage: "Aggiungi bagaglio",
    totallyBaggagePrice: "{num} pezzi {weight} kg totalmente",
    AdditionalServices: "Servizi aggiuntivi",
    check29: "Il cognome supera i 29 caratteri modificalo o contatta lassistenza clienti per ricevere assistenza.",
    SeatSelectionTipss: "Faremo del nostro meglio per soddisfare le vostre preferenze di selezione. Se non sono disponibili posti idonei, negozieremo prontamente con voi il rimborso. (Assicurarsi che l'indirizzo e-mail e il numero di telefono siano inseriti correttamente).",
    offer_time: "Orari di lavoro: 9:00-18:00 (GMT+08), Lun - Dim",
    CustomerSupport: "Servizio Clienti",
    AddPassengers: "Aggiungi Passeggeri",
    contactEmailEnter: "Inserisci le-mail di contatto",
    BaggageAllowance: "Franchigia Bagaglio",
    SelectFare: "Seleziona Tariffa",
    None: "Nessuno",
    IDTypePromptCheck: "Seleziona il tipo di documento",
    Tips: "Suggerimenti",
    change_to_airport: "{num} Cambiamento di aeroporto",
    GenderPrompt: "Genere",
    CustomerService: "Servizio clienti 24 ore su 24 7 giorni su 7",
    Done: "Fatto",
    FemalePlaceholder: "Femmina",
    ChildrenTips: "2-11 anni al momento del viaggio",
    firstNamePlaceholder: "ad esempio WILLIAM JEFFERSON",
    IDTypePrompt: "Tipo di documento didentità",
    Infants: "Neonati",
    system_processing: "Errore di sistema, riprovare",
    MobilePhone: "Cellulare",
    noEncheck: "Inserisci il nome e il secondo nome solo in inglese senza caratteri speciali",
    Childticket: "Biglietto bambino",
    please_enter_ID_info: "Inserisci i dati della carta di credito",
    Filters: "Filtri",
    Random: "Posto casuale",
    Cancellation_Fee: "Tassa di Cancellazione",
    continue_booking: "Continua la prenotazione",
    numSelected: "di {passegersnum} selezionato",
    backToSelect: "Torna a selezionare",
    from: "Da {num}",
    credit: "Carta di credito/debito",
    Reset: "Ripristina",
    Baggage: "Bagaglio",
    INNumCheckDigits: "Il numero del documento è compreso tra 5 e 15 cifre o lettere.",
    payNow: "Paga ora",
    Accept: "Accetta",
    Europe: "Europa",
    NoThanks: "No, Grazie",
    avoid_price_change: "per evitare variazioni di prezzo.",
    birthCheck: "Seleziona la data di nascita",
    City: "* Città",
    Personal_item: "Articolo Personale",
    IDexpirationDatePlaceholder: "Seleziona la data di scadenza dellID",
    birthPrompt: "Data di nascita",
    Refer_to_the_regulations_of_airline: "Consultare il regolamento della compagnia aerea",
    Change_Fee: "Commissione di Modifica",
    Cancellation_fee: "Tassa di Cancellazione",
    PremiumEconomy: "Premium Economy",
    Price: "Prezzo",
    person: "/persona",
    CustomerCentricSupport: "Supporto Incentrato sul Cliente",
    ShowMore: "Mostra di più",
    ChangeFee: "Tassa di cambio",
    IDexpirationDatePrompt: "Data di scadenza dellID",
    transfer_in: "Autotrasferimento in {num}",
    professionalmanner: "Il nostro team di assistenza clienti globale è disponibile per assisterti con tutte le tue richieste in modo amichevole e professionale. ",
    at_least: "Almeno {num} ore prima ",
    passegers: "passeger(i)",
    select_date: "SelezionaDate",
    Checked_baggage: "Imbarcato",
    PopularCities: "Populære byer",
    ChangeFlight: "Cambia volo",
    Sat: "Sab",
    PassengersInfo: "Informazioni sui passeggeri",
    carry_on_baggage_included: "Bagaglio a mano incluso",
    Any: "Qualunque",
    SelectClassPrice: "Seleziona Classe e Prezzo",
    Clear: "Cancella",
    AddBaggageTips: "«Aggiungi una franchigia bagaglio sufficiente. Ora puoi portare tutto con te per viaggiare in giro per il mondo!",
    total: "Totale",
    hour: "h",
    Feedback: "Condividi il tuo feedback",
    pay_fail_txt1: "si prega di contattare il nostro servizio clienti.",
    Depart: "Partenza",
    ok: "ok",
    ExtensiveRoutes: "Percorsi Estesi",
    included: "incluso",
    NorthAmerica: "Nord-Amerika",
    Easy_Access: "Accesso facile",
    agreedTerms: "Ho letto e accettato i seguenti Termini e condizioni di prenotazione e l'Informativa sulla privacy di Skytours.com. Informativa sulla privacy.",
    Dec: "Dic",
    Tue: "Mar",
    Change: "Modifica",
    Farefees: "Tasse e commissioni",
    insureCopywry: "Scelta intelligente: preferenza dell'85% dei viaggiatori!",
    not_buy_hint: "Non avete scelto alcun servizio assicurativo. Desidera tornare indietro e fare una scelta?",
    PassengersAddTips: "I bambini e i neonati devono essere accompagnati da un adulto durante il volo.",
    SelectClassPriceTips: "Totale per tutti i passeggeri (tasse e supplementi inclusi)",
    Jan: "Gen",
    non_fefundable: "Cancellazione non consentita",
    Partial_included: "Parzialmente incluso",
    RefundableBooking: "Prenotazione rimborsabile al 100%",
    not_buy: "No grazie, correrò il rischio",
    ServiceChat: "Chat di servizio",
    cityAirport: "Città o aeroporto",
    SelectFareTips: "Aggiorna il tuo pacchetto tariffario in modo da poter riprenotare o ricevere un rimborso quando decidi di cambiare piano.",
    non_changeable: "Non intercambiabile",
};
