export default {
    cancel: "취소",
    BookingDate: "예약 일자",
    nationalityPlaceholder: "선택국적",
    Apr: "4월",
    INNum: "주민등록번호 입력",
    onlineCheckIn: "온라인 체크인",
    NoFistNamecheck: "이름과 중간이름 입력하세요.",
    FlightsInfo: "항공편 정보",
    Reject: "거부",
    Month: "m",
    protected: "보험 가입",
    DelayedBaggageService: "수하물 분실 보험",
    About_Us_txt22: "고객의 요구를 더 잘 충족하기 위해 다양한 형태의 고객 서비스를 제공합니다.",
    IDNotice: "신분증 안내                                            • 이름은 신분증과 일치해야 함          • 최소 6개월 유효 기간",
    About_Us_txt21: "서비스",
    addres_require_select: "주소를 입력하세요",
    FlightDelayedCanceled: "공유하고 싶은 생각이 있나요? ",
    excluding_baggage_allowance: "수하물 허용량 제외",
    AllLanguages: "모든 언어",
    riskManagement: "위험 관리 확인",
    Aisle: "통로 쪽 좌석",
    ShareThoughts: "저희 웹사이트에서 피드백을 보내주시면, 아이디어를 공유하고 경험을 향상할 수 있도록 도와드릴 수 있습니다.",
    No_thanks: "아닙니다, 감사합니다.",
    recentSearchesCities: "최근 검색 비평가",
    partially_used_ticket: "부분적으로 사용한 항공권",
    Sun: "일요일",
    defaultKey: "시간(현지 시간)",
    seat: "좌석 ",
    InfantsTips: "여행 당시 만 2세 미만",
    Details: "상세한 상황",
    Passengers: "승객",
    OtherServices: "기타 서비스",
    all_unused_tickets: "모든 미사용 항공권",
    Post_ZIP_Code: "* 우편 번호",
    NationalityPrompt: "국적",
    cardNumber: "카드 번호",
    city_require_select: "도시를 입력하세요",
    Sep: "9월",
    ViewCurrentBaggagePolicy: "현재 수하물 정책 보기",
    before_departure: "출발 전",
    lowest_price: "최저가",
    country_require_select: "국가를 선택해 주세요.",
    Infant: "영아",
    selected_passegers: "선택됨: {} 승객",
    policy_detail: "*일정 변경 및 취소 수수료는 항공사의 공식 웹사이트에 명시된 정책에 따라 부과됩니다.",
    SeatSelection: "좌석 선택",
    ContactUs: "문의하기",
    Part_included: "부분적으로 포함됨",
    Passport: "여권",
    PassengersContactInfo: "승객 및 연락처 정보",
    SecurePayment: "100% 안전결제",
    Adult: "성인",
    Stops: "경유지",
    Changes_not_permitted: "일정 변경 불가능",
    free: "무료",
    IDNumber: "주민등록번호",
    Window: "창가 좌석",
    Thu: "목요일",
    Jul: "7월",
    About_Us_txt3: "Debodia International Limited, 주소: 2F, 38 Wong Chuk Hang Road, Wong Chuk Hang, Hong Kong, 회사 등록 번호. 2585004.",
    About_Us_txt4: "BIGSKY Grup S.A.U., 주소: Avda. Sant Antoni 38, AD400 La Massana, Andorra, 회사 인증서 등록 번호. L-7085322-S.",
    numBaggageChecked: "숫자} 승객의 위탁 수하물 추가",
    cvv: "CVV",
    CallUs: "전화문의",
    Jun: "6월",
    About_Us_txt1: "IWOFLY PTE LTD, 주소: 6 RAFFLES QUAY #16-01, 싱가포르(048580), 회사 등록 번호. 202338315R.",
    About_Us_txt2: "IWOFLY S.L., 주소: Paseo de las Delicias 30, 7a planta de la localidad de Madrid, 28045, 회사 등록 번호. B88532528.",
    Adultticket: "성인용 티켓",
    About_Us_txt7: "10년 이상의 항공권 온라인 B2C 경험을 바탕으로 다국적 고객 서비스 및 중국어, 영어, 프랑스어 서비스 제공 경험을 보유하고 있습니다.",
    updatesFlightTips: "항공편 상태를 확인하려면 로그인하세요",
    About_Us_txt8: "여러 단계의 마크업으로 이루어진 항공권 판매 체인의 고충을 잘 알고 있습니다. 우리는 중개인을 제거하여 가장 낮은 수준의 가격을 제공하기 위해 최선을 다하고 있습니다.",
    About_Us_txt5: "왜 우리를 선택해야 하나요?",
    businessClass: "비즈니스석",
    About_Us_txt6: "30년 이상의 항공권 B2B 경험과 풍부한 리소스로 풀 서비스 항공사 및 저가 항공사를 포함한 40여 개국의 국내선 항공권 및 국제선 항공권을 제공합니다.",
    About_Us_txt9: "오프라인에서만 구매할 수 있는 특별 프로모션을 받을 수 있는 곳이 없나요? 저희는 거대 OTA에서 제공할 수 없는 특별한 대우를 제공해 드립니다!",
    Fare: "표값",
    the_price_difference_generated_1: "항공편 변경에 따른 차액은 회원님의 책임입니다. 변경 수수료는 변경 건당 1인당 부과됩니다.",
    NoMatchingFlightsFound: "해당 항공편을 찾을 수 없습니다. 검색 조건을 변경하고 다시 시도해보시겠어요?",
    MalePlaceholder: "남성",
    E_Wallet: "월렛",
    the_price_difference_generated_2: "외부 요인(비자발적 변경)으로 인해 항공편이 변경된 경우 항공사의 대응에 따라 해결책을 제시해 드립니다.",
    price_per: "승객당",
    Select: "선택",
    Submit: "Submit",
    Back_to_select: "다시 추가",
    to: "~까지",
    noEnLastNmaecheck: "성씨는 영문으로 입력해주세요. 특수문자는 포함할 수 없습니다.",
    Add: "추가",
    Email: "전자우편",
    unpaid_booking_for_same_route: "동일한 노선의 미결제 주문",
    Pay: "지불",
    questionsContactUs: "만약 궁금한 사항이 있으면, 저희 고객 서비스 팀에 연락해주세요.",
    pleaseLocation: "도시 또는 공항을 입력하세요",
    premiumEconomy: "프리미엄 이코노미석",
    WhyBookSt: "Sky-tours를 통해 예약하는 이유는 무엇인가요?",
    buy_refundable: "예, 예약을 환불 가능하게 설정합니다.",
    FeedbackCounts: "당신의 피드백이 중요합니다!",
    Restassured: "우리는 안전한 결제 시스템과 강력한 리스크 컨트롤 조치를 보유하고 있으며 개인 정보와 결제를 우선적으로 보호합니다.",
    About_Us: "회사 소개",
    letDoThis: "지금 구독",
    Aug: "8월",
    fistClass: "일등석",
    Search: "수색",
    LastUpdated: "최근 업데이트 시간",
    SeparateSelection: "단독선택",
    OurPartners: "동반자",
    myBooking: "나의 주문서",
    search_similar_flights: "유사한 항공편 검색",
    Airports: "비행기",
    SecurityReliability: "안전성과 신뢰성",
    kg_per_person: "1인당 kg",
    ShowFlights: "항공편 표시",
    About: "저희에 대해서",
    province_require_select: "주/도를 입력하세요.",
    firstName: "이름 및 중간 이름",
    flightsAlerts: "항공편 알림",
    Nov: "11월",
    each_piece_cannot_exceed: "각 조각의 크기는 {num} 센티미터를 초과할 수 없습니다.",
    piece: "조각",
    nationalityCheck: "국적을 선택하세요.",
    please_retry: "시스템에 오류가 발생했습니다. 다시 시도해 주세요!",
    General: "일반적인 조건",
    Class: "클래스(항공)",
    Adults: "성인",
    BookingInstructions: "어린이/유아용 예약 정보",
    peace_of_mind: "안심하고 항공편 예약하기",
    bookingNo: "주문번호",
    FAQ_Q5: "연락처 정보를 수정할 수 있을까요? ",
    Good_scenery: "시야가 더 넓은",
    FAQ_Q4: "제 항공권을 환불하거나 날짜를 변경할 수 있습니까? ",
    delete_all_records: "모든 기록을 삭제하시겠습니까?",
    FAQ_Q1: "어떻게 주문을 조회하나요?                    ",
    FAQ_Q3: "수하물을 어떻게 구매할 수 있나요?",
    FAQ_Q2: "항공권 발권 성공 여부를 어떻게 확인할 수 있나요?                               ",
    CancellationFee: "취소 수수료",
    privacy: "당사는 사용자의 개인정보를 존중합니다.",
    Time: "시간",
    buy_bags: "네, 제 수하물을 추적해 주세요",
    State_Province: "* 주/도",
    Continue: "계속",
    alter_prices: "항공사가 이 항공편의 가격을 변경했습니다. ",
    travelDreamsRunWild: "지금 바로 가입하여 여행 꿈을 자유롭게 펼쳐보세요.",
    Checked_baggage_included: "위탁 수하물 포함",
    CheckIn2: "공항에서 줄을 서서 기다릴 필요 없이 탑승 절차를 간소화하세요.",
    expiryDate: "만료일",
    FAQ_A5: " 만약 승객이 여행 예약 시 잘못된 이메일 주소 또는 전화 번호를 제공했다면, 최대한 비행 48시간 전에 정보 수정을 신청할 수 있습니다. 승객은 support{'@'}sky-tours.com으로 이메일을 보내서 올바른 정보를 제공해야 합니다.",
    duration: "소모 시간",
    CheckIn1: "탑승권은 출발 24시간 전에 발송됩니다.",
    FAQ_A4: "각 항공사의 정책 및 좌석 등급에 따라 각 티켓의 환불 및 변경 규정이 다릅니다. 항공권을 구매할 때 예약 상세 정보 페이지 우측에 구체적인 환불 및 변경 규정이 표시됩니다. 예약을 완료한 후에도 '내 예약'에서 구매한 항공권의 환불 및 변경 규정을 확인할 수 있습니다.",
    LeaveFeedback: " 피드백을 남겨주세요",
    CheckIn3: "비싼 체크인 수수료를 계산대에서 피하세요.",
    FAQ_A1: " Sky-tours에서 성공적으로 주문을 완료하면 시스템이 주문 번호가 포함된 이메일을 예약한 이메일 주소로 자동으로 보냅니다. Sky-tours 웹 사이트 홈페이지 오른쪽 상단의 '내 예약'을 클릭하고 주문 번호와 예약한 이메일 주소를 입력하면 주문을 조회할 수 있습니다. 이메일을 받지 못한 경우 스팸 메일함을 먼저 확인해 보세요. 스팸 메일함에도 없는 경우 예약한 이메일 주소를 잘못 입력한 것일 수 있으니 빠르게 고객 서비스에 문의하여 수정을 도움받으세요.",
    Language: "언어",
    FAQ_A3: " Sky-tours는 대부분의 항공사의 수하물 허용량을 구매하는데 도움을 줄 수 있습니다. 항공사의 규정에 따라 다른 노선마다 수하물의 무게와 가격이 다를 수 있습니다. 티켓을 구매할 때 주문에 따라 구매할 수 있습니다. 주문 후 추가 수하물 구매를 원하시면 Sky-tours 고객 상담원에게 메일로 연락하여 요청 사항을 알려주시면 해당 비용에 대한 답변을 드리겠습니다.동의하시면 결제 링크를 메일로 보내드리고, 결제 후 빠른 처리 후 결과를 메일로 피드백 드리겠습니다. 참고: 고객 서비스 담당자는 support{'@'}sky-tours.com 이메일을 통해서만 연락합니다. 통신 및 자금의 안전을 위해 다른 이메일의 결제 통지를 믿지 마십시오.",
    InfantsTicket: "유아 티켓(좌석 없음)",
    FAQ_A2: "만약 tickets{'@'}sky-tours.com에서 온 이메일에서 주문이 '발권 완료'되었음과 함께 항공권 번호가 첨부되어 있다면, 이는 발권이 성공적으로 이루어졌음을 나타냅니다. 만일 주문 결제 후 72시간이 지나도 발권 이메일을 받지 못한 경우 스팸 메일함을 먼저 확인하세요. 발권 확인 이메일을 받지 못했다고 확신되거나 다른 도움이 필요한 경우 언제든지 고객 서비스에 문의하세요.",
    Policies_Baggage: "정책과 수하물",
    recommendedCheapFlights: "저가 항공편 추천",
    Children: "어린이",
    non_refundable: "환불 불가",
    lowestPricedTips: "한 달 내에 출발하는 가장 저렴한 항공편!",
    fistNamePrompt: "이름 및 중간 이름",
    Return: "Return",
    payment_failed: "결제 실패!",
    ticket: "항공권",
    MobilePhoneTips: "휴대전화 번호를 알려주세요.",
    AddSeat: "예약 후 좌석 추가는 일반적으로 더 많은 비용이 발생할 수 있습니다!",
    stop1: "1회 경유",
    riskInfo: "결제 확인을 통과하려면 다음 정보가 필요합니다.",
    INNumCheck: "주민등록번호를 입력하세요.",
    About_Us_txt20: "개인 정보를 안전하게 보호하세요.",
    BusinessClass: "비즈니스 클래스",
    futureAdventures: "잘 기획된 여행 콘텐츠는 미래의 여행에 대한 영감을 불러일으킵니다.",
    cardholder: "카드 소유자 성명",
    Mon: "월요일",
    Checked: "위탁수하물",
    About_Us_txt19: "안전한 결제",
    TermsConditions: "약관",
    About_Us_txt18: "경쟁력 있는 가격으로 200개 이상의 국가로 향하는 노선.",
    TickeTpricesTips: "항공편을 검색하고 있습니다.",
    notIncluded: "포함하지 않음",
    Asia: "아시아",
    FAQ: "자주 묻는 질문",
    Within: "출발 최대 {NUM}시간 전까지",
    priceRise: "가격 변경",
    About_Us_txt11: "항공사가 비자발적 환불/취소를 무료로 제공하는 한, 저희도 조건 없이 무료로 서비스를 제공합니다.",
    About_Us_txt10: "모든 고객에게 따뜻하고 수준 높은 서비스를 제공합니다. 로봇이 대답하는 것이 아니라 맞춤형 솔루션을 제공합니다.",
    stop2: "2회 경유",
    About_Us_txt13: "날개를 펼쳐드립니다",
    About_Us_txt12: "여러분의 개인 온라인 여행 파트너가 되어 세계 여행을 위한 날개를 달아드리겠습니다.",
    Fri: "금요일",
    About_Us_txt15: "연락처 정보",
    noLastNamecheck: "성(이름)을 입력하세요.",
    About_Us_txt14: "더 많은 연결, 더 많은 옵션, 더 많은 경제성",
    About_Us_txt17: "다양한 노선",
    About_Us_txt16: "궁금한 점이 있으시면 언제든지 고객 서비스 팀에 문의해 주시면 연중무휴 24시간 대기하고 있습니다.",
    PriceDetails: "상세 가격",
    birthPlaceholder: "생년월일 선택",
    book_now: "가격이 급등하기 직전에 예약하는 것이 좋습니다.",
    Oct: "10월",
    copyright: "{'@'} 2024 Sky-tours.com 저작권 소유",
    StopoverCity: "중간 경유 도시",
    Policies: "정책",
    Address: "* 주소",
    IDexpirationDateCheck: "신분증 유효기간을 선택하세요.",
    offeringHighly: "우리의 항공 네트워크는 200개 이상의 국가를 포함하며 여행의 편의를 위해 매우 경쟁력 있는 가격을 제공합니다.",
    PleaseCompletePayment: "지정된 시간 내에 결제를 완료해 주세요.",
    NameGuidelines: "이름 규칙",
    oneWay: "편도",
    required: "필수항목",
    PaymentMethods: "지불방식",
    after_departure: "출발 후",
    PaymentProgress: "안전결제",
    info_safe: "스카이투어는 귀하의 여행을 보호하고 귀하의 정보를 안전하게 보호합니다!",
    lastNamePlaceholder: "예를 들면 장씨",
    ContactInfo: "연락방식",
    Sameselection: "{num} 명의 승객에게 동일한 선택을 적용합니다.",
    SittingTogether: "인접 좌석 ",
    ID: "문서",
    enter: "입력",
    ServicesAdded: "선택된 서비스",
    PaymentSuccessful: "결제 완료되었습니다!",
    Child: "아동",
    Added: "추가완료",
    Recommended: "추천",
    post_ZIP_Code_require_select: "코드를 입력하세요",
    seatCompletedTxt: "명의 승객이 아직 좌석을 선택하지 않았는데, 좌석 예약으로 돌아가시겠습니까?",
    enterEmailAdress: "이메일 주소 입력하세요.",
    Carry_on_baggage: "휴대수하물",
    baggageAllowanceAndPolicies: "수하물 허용량 및 정책",
    risk_control_rejected: "위험 관리 이상",
    all_airports: "모든 공항",
    price_rise: "가격 인상",
    Wed: "수요일",
    Country: "* 국가",
    pay_fail_txt: "만약 궁금한 사항이 있으면,",
    enterNameExactly: "체크인 시 제출한 신분증의 이름과 입력한 이름이 완전히 일치하는지 확인하세요.",
    Mar: "3월",
    Hide: "숨기다",
    lastName: "성(퍼스트네임)",
    StayInspired: "여행 영감 받기",
    unknow: "세부 정보",
    May: "5월",
    Cancel: "취소",
    add_insurance: "보험 추가하기",
    privacy3: "개인정보 처리방침",
    Confirm: "확인",
    privacy2: "쿠키에 대해 자세히 알아보려면 개인정보처리방침을 읽어보세요.",
    privacy1: "당사는 기술, 분석 및 마케팅 쿠키를 사용하여 로그인 및 중단한 부분부터 검색을 계속하는 등의 작업을 지원합니다. ",
    completeSubmission: "가격 변경을 피하려면",
    About_Us_txt: "본 웹사이트는 다음 회사에서 공동으로 관리합니다:",
    privacy4: "배너 알림을 끄거나 무시하면 장치 또는 브라우저에서 기본 쿠키 사용에 동의하는 것입니다.",
    Hide_2_transfers: "2회 이상의 경유가 있는 항공편 숨김",
    Economy: "이코노미석(일반석)",
    Airlines: "항공사",
    check34: "이름과 중간 이름이 34자를 초과하였습니다. 수정 또는 고객센터로 연락하여 처리해 주시기 바랍니다.",
    NonstopOnly: "직항만 허용",
    CheckIn: "탑승 수속(체크인)",
    roundTrip: "왕복",
    pieces_per_person: "1인당 개수",
    Feb: "2월",
    kg_per_piece: "개당 천 그램",
    reminder: "알림",
    more: "상세한 상황",
    CurrentLanguage: "현재 언어",
    gotit: "확인됨",
    SeatSelectionTips: "원하시는 좌석 선택하시고, 편안한 여행 되세요.",
    bookingEmail: "예약 확인 이메일 수신",
    AddBaggage: "수하물 추가",
    totallyBaggagePrice: "총 {num}개 {weight} 킬로그램",
    AdditionalServices: "부가서비스",
    check29: "성씨가 29자를 초과하였습니다. 수정하거나 고객센터에 연락하여 도움을 요청하세요.",
    SeatSelectionTipss: "귀하의 선택에 따라 좌석을 예약을 위해 최선을 다하겠습니다.해당 좌석이 없으면 바로 협의나 환불 진행하겠습니다.연락처 이메일 주소와 전화번호를 정확하게 입력하세요.",
    offer_time: "영업 시간: 9:00~18:00 (GMT+08)，월요일~일요일",
    CustomerSupport: "고객지원",
    AddPassengers: "추가 승객",
    contactEmailEnter: "연락 이메일을 입력하세요.",
    BaggageAllowance: "수하물 한도",
    SelectFare: "티켓 가격 선택",
    None: "no",
    IDTypePromptCheck: "신분증 유형을 선택하세요.",
    Tips: "제시(팁)",
    change_to_airport: "{num} 명이 다른 공항으로 변경했습니다.",
    GenderPrompt: "성별",
    CustomerService: "글로벌 고객 서비스 지원",
    Done: "확인",
    FemalePlaceholder: "여성",
    ChildrenTips: "여행 당시 만 2세~11세",
    firstNamePlaceholder: "예를 들면 XIAOMING",
    IDTypePrompt: "신분증 유형",
    Infants: "유아",
    system_processing: "시스템 오류, 다시 시도하세요",
    MobilePhone: "휴대전화 번호",
    noEncheck: "이름과 중간 이름을 영문으로 입력해 주세요. 특수문자는 포함할 수 없습니다.",
    Childticket: "어린이 티켓",
    please_enter_ID_info: "서류 정보를 입력하세요",
    Filters: "선별",
    Random: "무작위 좌석",
    Cancellation_Fee: "취소 비용",
    continue_booking: "예약 계속하기",
    numSelected: " {passegersnum} 좌석 선택됨",
    backToSelect: "다시 좌석 선택으로 돌아가기",
    from: "~로 부터",
    credit: "신용카드/체크카드",
    Reset: "재설정(초기화)",
    Baggage: "수하물",
    INNumCheckDigits: "5~15자리 숫자 또는 문자로 된 문서 번호",
    payNow: "즉시지불",
    Accept: "동의",
    Europe: "유럽",
    NoThanks: "아닙니다, 감사합니다.",
    avoid_price_change: "일 이내에 정보 제출을 완료해 주세요.",
    birthCheck: "생년월일을 선택하세요.",
    City: "* 도시",
    Personal_item: "휴대물품",
    IDexpirationDatePlaceholder: "신분증 유효기간 선택",
    birthPrompt: "생년월일",
    Refer_to_the_regulations_of_airline: "항공사 규정 참조",
    Change_Fee: "변경 비용",
    Cancellation_fee: "환불 수수료",
    PremiumEconomy: "프리미엄 이코노미 클래스",
    Price: "가격",
    person: "/인",
    CustomerCentricSupport: "고객 최우선의 서비스",
    ShowMore: "더보기",
    ChangeFee: "항공편 변경 수수료",
    IDexpirationDatePrompt: "신분증 유효일",
    Save: "보존",
    transfer_in: "스스로 이동",
    professionalmanner: "저희 글로벌 고객 서비스 팀은 모든 문의에 친절하고 전문적으로 도움을 드릴 준비가 되어 있습니다.",
    at_least: "최소 {num}시간 전",
    passegers: "승객 X명",
    select_date: "날짜 선택",
    Checked_baggage: "위탁수하물",
    PopularCities: "인기 도시",
    ChangeFlight: "항공편 변경",
    Sat: "토요일",
    PassengersInfo: "승객정보",
    carry_on_baggage_included: "휴대 수하물 포함",
    Any: "어떠한(아무)",
    SelectClassPrice: "좌석 및 가격 선택",
    Clear: "지우기",
    AddBaggageTips: "충분한 수하물을 추가하세요. 이제 세계 일주에 필요한 모든 물건을 챙길 수 있습니다!",
    total: "합계",
    hour: "h",
    Feedback: "의견 공유",
    pay_fail_txt1: "저희 고객 서비스 팀에 연락해주세요.",
    Depart: "출발",
    ok: "좋아요!",
    ExtensiveRoutes: "광범위한 항로",
    included: "포함됨",
    NorthAmerica: "북미",
    Easy_Access: "출입이 편리한",
    agreedTerms: "나는 Sky-tours의 이용 약관과 개인정보 처리 방침을 읽었으며 이에 동의합니다.",
    Dec: "12월",
    Tue: "화요일",
    Change: "개정",
    Farefees: "세금 및 부가요금",
    insureCopywry: "현명한 선택: 여행자 85%의 선호도!",
    not_buy_hint: "보험을 선택하지 않았습니다. 추가하려면 돌아가시겠습니까?",
    PassengersAddTips: "어린이와 유아는 비행 중 성인과 동행해야 합니다.",
    SelectClassPriceTips: "모든 승객의 요금(세금&수수료 포함)",
    Jan: "1월",
    non_fefundable: "환불 불가능",
    Partial_included: "부분적으로 포함됨",
    RefundableBooking: "100% 환불 예약 가능",
    not_buy: "아니요, 위험을 감수할게요",
    ServiceChat: "고객상담",
    cityAirport: "도시 또는 공항",
    SelectFareTips: "티켓 요금제를 업그레이드하여 계획을 변경할 때 다시 예약하거나 환불을 받을 수 있도록 합니다.",
    non_changeable: "변경 금지",
};
