export default {
    cancel: "Avbryt",
    BookingDate: "Bestillingsdato",
    nationalityPlaceholder: "Velg nasjonalitet",
    Apr: "Apr",
    INNum: "Skriv inn ID-nummer",
    onlineCheckIn: "Innsjekking på nett",
    NoFistNamecheck: "Vennligst skriv inn for- og mellomnavn",
    FlightsInfo: "Informasjon om flyreiser",
    Reject: "Avvis",
    Month: "m",
    protected: "Beskyttet",
    DelayedBaggageService: "Forsinket bagasjeservice",
    About_Us_txt22: "Vi tilbyr kundeservice på ulike måter for å hjelpe deg på best mulig måte.",
    IDNotice: "ID-merknad • Navn må samsvare med ID • > 6-måneders gyldighet",
    About_Us_txt21: "Oppmerksom service",
    addres_require_select: "Vennligst skriv inn adresse",
    FlightDelayedCanceled: "Har du noen tanker å dele? ",
    excluding_baggage_allowance: "Eksklusive tillatt bagasje",
    AllLanguages: "Alle språk",
    riskManagement: "Risikohåndtering",
    Aisle: "Sete ved midtgangen",
    ShareThoughts: "Del tankene dine og hjelp oss med å forbedre opplevelsen din ved å gi tilbakemelding på nettstedet vårt.",
    No_thanks: "Nei takk",
    recentSearchesCities: "Siste søk",
    partially_used_ticket: "Delvis brukte billetter",
    Sun: "Søn",
    defaultKey: "Tid (lokal tid)",
    seat: "Sete",
    InfantsTips: "Under 2 år på reisetidspunktet",
    Details: "Detaljer",
    Passengers: "Passasjerer",
    OtherServices: "Andre tjenester»",
    all_unused_tickets: "Alle ubrukte billetter",
    Post_ZIP_Code: "* Post-/postnummer",
    NationalityPrompt: "Nasjonalitet",
    cardNumber: "Kortnummer",
    city_require_select: "Vennligst skriv inn by",
    Sep: "Sep",
    ViewCurrentBaggagePolicy: "Se gjeldende bagasjeregler",
    before_departure: "Før avreise",
    lowest_price: "Laveste pris",
    country_require_select: "Vennligst velg et land",
    Infant: "Spedbarn",
    selected_passegers: "Valgt: {num} passeringer",
    policy_detail: "*Endrings- og avbestillingsgebyrer belastes i henhold til retningslinjene som er oppført på flyselskapets nettside.",
    SeatSelection: "Setevalg",
    ContactUs: "Kontakt oss",
    Part_included: "Delvis inkludert",
    Passport: "Pass",
    PassengersContactInfo: "Passasjerer og kontaktinformasjon",
    SecurePayment: "100% sikker betaling",
    Adult: "Voksen",
    Stops: "Stopp",
    Changes_not_permitted: "Endring ikke tillatt",
    free: "Gratis",
    IDNumber: "ID-nummer",
    Window: "Vindussete",
    Thu: "Tor",
    Jul: "Jul",
    About_Us_txt3: "Debodia International Limited, adresse 2F, 38 Wong Chuk Hang Road, Wong Chuk Hang, Hong Kong, med organisasjonsnummer NO. 2585004.",
    About_Us_txt4: "BIGSKY Grup S.A.U., adresse Avda. Sant Antoni 38, AD400 La Massana, Andorra, med organisasjonsnummer NO. L-7085322-S.",
    numBaggageChecked: "Legg til innsjekket bagasje for {num} passasjerer",
    cvv: "CVV",
    CallUs: "Ring oss",
    Jun: "Jun",
    About_Us_txt1: "IWOFLY PTE LTD, adresse 6 RAFFLES QUAY #16-01, SINGAPORE (048580) med organisasjonsnummer NO. 202338315R.",
    About_Us_txt2: "IWOFLY S.L., adresse Paseo de las Delicias 30, 7a planta de la localidad de Madrid, 28045 med organisasjonsnummer NO. B88532528.",
    Adultticket: "Voksenbillett",
    About_Us_txt7: "10+ års erfaring med flybilletter online B2C, vi har erfaring med multinasjonal kundeservice og tilbud på kinesisk, engelsk og fransk.",
    updatesFlightTips: "Logg inn for å sjekke oppdateringer om flighter",
    About_Us_txt8: "Vi kjenner smertepunktene i flybillettbransjens salgskjede med flere lag med påslag. Vi er opptatt av å gi deg de laveste prisene ved å fjerne mellomleddene.",
    About_Us_txt5: "Hvorfor velge Sky-tours.com?",
    businessClass: "Businessklase",
    About_Us_txt6: "Vi har mer enn 30 års erfaring innen B2B-flybilletter og tilbyr innenlands flybilletter og internasjonale flybilletter fra mer enn 40 land, inkludert fullserviceselskaper og lavprisselskaper.",
    About_Us_txt9: "Har du ingen steder å få tak i et spesialtilbud som bare kan kjøpes offline? Vi er her for å tilby deg en behandling som ikke kan tilbys i tycoon OTA!",
    Fare: "Billettpris",
    the_price_difference_generated_1: "Prisforskjellen for endringsflyvningen skal dekkes av deg. Endringsgebyret belastes per person og per endring.",
    NoMatchingFlightsFound: "Ingen matchende resultater. Hvorfor ikke endre søkekriteriene?",
    MalePlaceholder: "Mann",
    E_Wallet: "E-lommebok",
    the_price_difference_generated_2: "Hvis flyvningen din blir endret på grunn av eksterne faktorer (ufrivillig ruteendring), vil vi tilby deg en alternativ løsning i henhold til flyselskapets tilbakemeldinger.",
    price_per: "per passasjer",
    Select: "Velg",
    Submit: "Send inn",
    Back_to_select: "Tilbake til valg",
    to: "til",
    noEnLastNmaecheck: "Vennligst skriv inn etternavn på engelsk uten spesialtegn",
    Add: "Legg til",
    Email: "E-post",
    Pay: "Betal",
    questionsContactUs: "Hvis du har spørsmål, kan du kontakte vår kundeservice.",
    pleaseLocation: "Vennligst skriv inn by eller flyplass",
    premiumEconomy: "Premium økonomi",
    WhyBookSt: "Hvorfor bestille med Sky-tours?",
    buy_refundable: "Ja, gjør bestillingen min refunderbar",
    FeedbackCounts: "Din tilbakemelding teller!",
    Restassured: "Vær trygg med vårt sikre betalingssystem og robuste risikokontrolltiltak som prioriterer beskyttelsen av dine personlige opplysninger og betalinger.",
    About_Us: "Om oss",
    letDoThis: "La oss gjøre dette",
    Aug: "Aug",
    fistClass: "Første klasse",
    Search: "Søk",
    LastUpdated: "*Sist oppdatert",
    SeparateSelection: "Separat valg",
    OurPartners: "Våre partnere",
    myBooking: "Min bestilling",
    search_similar_flights: "Søk etter lignende flyreiser",
    Airports: "Flyplasser",
    SecurityReliability: "Sikkerhet og pålitelighet",
    kg_per_person: "kg per person",
    ShowFlights: "Vis flyreiser",
    province_require_select: "Vennligst skriv inn delstat/provins",
    firstName: "fornavn",
    flightsAlerts: "Flightvarsler",
    Nov: "Nov",
    each_piece_cannot_exceed: "Hver del kan ikke overstige {num} cm i størrelse.",
    piece: "stykke",
    nationalityCheck: "Vennligst velg nasjonalitet",
    please_retry: "Systeminternt unntak, vennligst prøv på nytt!",
    General: "Generelt",
    Class: "klasse",
    Adults: "Voksne",
    BookingInstructions: "Bestillingsinstruksjoner for barn/spedbarn",
    peace_of_mind: "Bestill flyreisen med ro i sjelen",
    bookingNo: "Bestillingsnr.",
    FAQ_Q5: "Kan jeg endre kontaktinformasjonen min?",
    Good_scenery: "Fin natur",
    FAQ_Q4: "Kan billetten min endres eller kanselleres?",
    delete_all_records: "Er du sikker på at du vil slette alle poster?",
    FAQ_Q1: "Hvordan finner jeg bestillingen min?",
    FAQ_Q3: "Hvordan kjøpe bagasje?",
    FAQ_Q2: "Hvordan bekrefte om billetten er utstedt vellykket?",
    CancellationFee: "Avbestillingsgebyr",
    privacy: "Vi setter pris på personvernet ditt",
    Time: "Tid",
    buy_bags: "Ja, vær så snill å spore bagasjene mine",
    State_Province: "* Delstat/provins",
    Continue: "Fortsett",
    alter_prices: "Flyselskapet har endret prisen på denne flyreisen.",
    travelDreamsRunWild: "Registrer deg i dag og la  reisedrømmene løpe løpsk.",
    Checked_baggage_included: "Innsjekket bagasje inkludert",
    CheckIn2: "Legg til rette for en rask ombordstigningsprosess for flyet ditt og unngå behovet for å vente i køer på flyplassen.",
    expiryDate: "Utløpsdato",
    FAQ_A5: "Dersom passasjerer har oppgitt feil e-postadresser eller telefonnumre ved bestilling, kan de søke om å endre informasjonen senest 48 timer før avgang. Passasjerer må sende e-post til support{'@'}sky-tours.com og oppgi riktig informasjon.",
    duration: "Varighet",
    CheckIn1: "Ombordstigningskortet vil bli sendt til deg innen 24 timer før avgang.",
    FAQ_A4: "Reglene for endring og kansellering av hver billett varierer i henhold til ulike flyselskapsregler og kabinklasser. Når du kjøper en billett, vises de spesifikke endrings- og kanselleringsreglene på høyre side av reservasjonssiden. Etter at bestillingen er fullført, kan du også sjekke endrings- og kanselleringsreglene for billetten du har kjøpt i \"Min bestilling\".",
    LeaveFeedback: "Legg igjen en tilbakemelding",
    CheckIn3: "Unngå det dyre innsjekkingsgebyret ved skranken.",
    FAQ_A1: "Når du har lagt inn en bestilling på Sky-tours, vil systemet automatisk sende en e-post med ordrenummeret til din reserverte e-postadresse. Du kan klikke \"Min bestilling\" øverst til høyre på hjemmesiden til Sky-tours nettside, skriv inn ordrenummeret og din reserverte e-postadresse, og deretter kan du finne bestillingen din.\nHvis du ikke mottar e-postvarslingen, sjekk søppelpostmappen først. Hvis den ikke ligger i søppelposten, har du kanskje oppgitt feil e-postadresse ved bestilling. I dette tilfellet, vennligst kontakt vårt kundeserviceteam i tide for å hjelpe deg med å endre det.",
    Language: "Språk",
    FAQ_A3: "Sky-tours kan hjelpe deg med å kjøpe innsjekket bagasje til de fleste flyselskaper. I henhold til flyselskapenes regelverk har forskjellige ruter forskjellige bagasjestykker, vekter og priser. Du kan kjøpe bagasjen sammen med bestillingen. Hvis du ønsker å kjøpe ekstra bagasje etter å ha lagt inn en bestilling, vennligst kontakt oss, og vi vil varsle deg om det tilsvarende gebyret. Hvis du godtar gebyret, sender vi deg en betalingslenke via e-post. Etter betalingen din vil vi håndtere det ASAP og sende deg resultatet via e-post.\nVær oppmerksom på: Vårt kundeserviceteam vil kun kontakte deg via e-postadressen support{'@'}sky-tours.com. For sikkerheten til din kommunikasjon og midler, ikke stol på betalingsvarsler fra andre e-postadresser.",
    InfantsTicket: "Spedbarnsbillett på fanget",
    FAQ_A2: "Billetten din har blitt utstedt hvis du mottar en e-post fra tickets{'@'}sky-tours.com om at bestillingen din er \"TICKETED\" med billettnummeret ditt.\nHvis du ikke har mottatt \"BILLETTET\"-varslings-e-posten 72 timer etter at du la inn en bestilling, vennligst sjekk søppelmappen din først. Hvis du er sikker på at du ikke har mottatt e-postvarslingen eller trenger annen hjelp, kan du når som helst kontakte vårt kundeserviceteam.",
    Policies_Baggage: "Retningslinjer og bagasje",
    recommendedCheapFlights: "Anbefalte billige flyreiser",
    Children: "Barn",
    non_refundable: "Refunderes ikke",
    lowestPricedTips: "Den rimeligste flyreisen med avgang innen én måned!",
    fistNamePrompt: "For- og mellomnavn",
    Return: "Retur",
    payment_failed: "Betaling mislyktes!",
    ticket: "billett",
    MobilePhoneTips: "Vennligst oppgi et telefonnummer",
    AddSeat: "Det koster vanligvis mer å legge til seter etter bestilling!",
    stop1: "1 stopp",
    riskInfo: "Du må oppgi følgende informasjon for å kunne verifisere betalingen.",
    INNumCheck: "Vennligst skriv inn ID-nummer",
    About_Us_txt20: "Vi garanterer at personopplysningene dine er trygge.",
    BusinessClass: "Businessklase",
    futureAdventures: "Kuratert reiseinnhold for å inspirere til fremtidige eventyr.",
    cardholder: "Kortinnehaverens navn",
    Mon: "Man",
    Checked: "Innjekket",
    About_Us_txt19: "Sikker betaling",
    TermsConditions: "Vilkår og betingelser",
    About_Us_txt18: "Flyrutene dekker over 200 land, og prisene er svært konkurransedyktige.",
    TickeTpricesTips: "Søke etter flyreiser",
    notIncluded: "0.0",
    Asia: "Asien",
    FAQ: "FAQ",
    Within: "Innen {num} timer før ",
    priceRise: "Prisendring",
    About_Us_txt11: "Så lenge flyselskapene tilbyr gratis ufrivillig refusjon/avbestilling, vil vi også tilby deg en gratis tjeneste uten betingelser.",
    About_Us_txt10: "Hver eneste kunde vil bli betjent med varme og høykvalitetsløsninger. Ingen robotsvar, men målrettede løsninger.",
    stop2: "2+ stopp",
    About_Us_txt13: "Vi lager vingene dine",
    About_Us_txt12: "Sky-tours.com blir din personlige reisepartner på nettet og gir deg vinger til å reise verden rundt.",
    Fri: "Fre",
    About_Us_txt15: "Kontaktinformasjon",
    noLastNamecheck: "Vennligst skriv inn etternavn",
    About_Us_txt14: "Flere tilkoblingsmuligheter, flere valgmuligheter, billigere",
    About_Us_txt17: "Rike flyruter",
    About_Us_txt16: "Hvis du har spørsmål, er du velkommen til å kontakte vårt kundeserviceteam, så står vi til tjeneste døgnet rundt.",
    PriceDetails: "Prisdetaljer",
    birthPlaceholder: "Velg fødselsdato",
    book_now: "Bestill nå før prisen stiger enda mer.",
    Oct: "Okt",
    copyright: "{'@'} 2024 Sky-tours.com Med enerett",
    StopoverCity: "Stop-over by",
    Policies: "Retningslinjer",
    Address: "* Adresse",
    IDexpirationDateCheck: "Vennligst velg utløpsdato for ID",
    offeringHighly: "Vårt flynettverk spenner over 200 land og tilbyr svært konkurransedyktige priser for enkelhets skyld.",
    PleaseCompletePayment: "Vennligst fullfør betalingen innen",
    NameGuidelines: "Retningslinjer for navn",
    oneWay: "En vei",
    required: "Obligatorisk felt",
    PaymentMethods: "Betalingsmetoder",
    after_departure: "Etter avreise",
    WishingpleasantJourney: "Vi ønsker deg en god reise!",
    PaymentProgress: "Sikker betaling",
    info_safe: "Sky-tours vil beskytte reisen din og holde informasjonen din trygg!",
    lastNamePlaceholder: "f.eks. CLINTON",
    ContactInfo: "Kontaktinfo",
    Sameselection: "Samme valg for alle {num} passasjerer",
    SittingTogether: "Sitter sammen",
    ID: "LEGITIMASJON",
    enter: "Skriv inn",
    ServicesAdded: "Tjenester lagt til",
    PaymentSuccessful: "Betaling vellykket!",
    Child: "Barn",
    Added: "Lagt til",
    Recommended: "Anbefalt",
    post_ZIP_Code_require_select: "Vennligst skriv inn postnummer",
    seatCompletedTxt: "passasjeren(e) har ikke valgt sete. Vil du gå tilbake for å reservere seter?",
    enterEmailAdress: "Skriv inn e-postadressen din",
    Carry_on_baggage: "Håndbagasje",
    baggageAllowanceAndPolicies: "Tillatt bagasje og retningslinjer",
    risk_control_rejected: "Risikokontroll avvist",
    all_airports: "Alle flyplasser",
    price_rise: "Pris Stigning",
    Wed: "Ons",
    Country: "* Land",
    pay_fail_txt: "Hvis du har noen spørsmål, ",
    enterNameExactly: "Pass på at du skriver inn navnet nøyaktig slik det vises på ID-en som skal brukes når du sjekker inn",
    Mar: "Mar",
    Hide: "Skjul",
    lastName: "etternavn",
    StayInspired: "Hold deg inspirert",
    unknow: "detaljer",
    May: "Mai",
    Cancel: "avbryt",
    add_insurance: " Legg til forsikring ",
    privacy3: "Retningslinjer for personvern",
    Confirm: "Bekreft",
    privacy2: "Les mer om vår praksis for informasjonskapsler her",
    privacy1: "Vi bruker tekniske, analytiske og markedsføringsmessige informasjonskapsler for å hjelpe deg med ting som å logge inn og fortsette søket der du slapp.",
    completeSubmission: "Vennligst fullfør innsendingen innen",
    About_Us_txt: "Dette nettstedet administreres i fellesskap av følgende selskaper:",
    privacy4: "Hvis du lukker eller ignorerer banneret, godtar du bruken av viktige informasjonskapsler på enheten eller i nettleseren din.",
    Hide_2_transfers: "Skjul flyreiser med mer enn 2 transfer",
    Economy: "Økonomi",
    Airlines: "Flyselskaper",
    check34: "Fornavn og mellomnavn overskrider 34 tegn vennligst endre eller kontakt kundeservice for å få hjelp",
    NonstopOnly: "Kun direkte",
    CheckIn: "Innsjekking",
    roundTrip: "Tur-retur",
    pieces_per_person: "stykker per person",
    Feb: "Feb",
    kg_per_piece: "kg per stykk",
    reminder: "Påminnelse",
    more: "Mer om dette",
    CurrentLanguage: "Nåværende språk",
    gotit: "Gotit",
    SeatSelectionTips: "Velg ditt foretrukne sete for en komfortabel reise.",
    bookingEmail: "E-post for bestillingsbekreftelse",
    AddBaggage: "Legg til bagasje",
    totallyBaggagePrice: "{num} stykke(r) {weight} kg totalt",
    AdditionalServices: "Tilleggstjenester",
    check29: "Etternavnet overskrider 29 tegn vennligst korriger eller kontakt kundeservice for å få hjelp.",
    SeatSelectionTipss: "Vi vil gjøre vårt beste for å oppfylle dine preferanser. Hvis det ikke er noen kvalifiserte seter tilgjengelig, vil vi umiddelbart forhandle/refundere med deg. (Sørg for at e-postadressen og telefonnummeret til kontaktpersonen din er korrekt utfylt).",
    offer_time: "Arbeidstid: 9:00-18:00 (GMT+08), Man-Søn",
    CustomerSupport: "Kundeservice",
    AddPassengers: "Legg til passasjerer",
    contactEmailEnter: "Vennligst skriv inn kontaktens e-post",
    BaggageAllowance: "Tillatt bagasje",
    SelectFare: "Velg billettpris",
    None: "Ingen",
    IDTypePromptCheck: "Velg dokumenttype",
    Tips: "Tips",
    change_to_airport: "{nummer} Bytte til en annen flyplass",
    GenderPrompt: "Kjønn",
    CustomerService: "24/7 kundeservice",
    Done: "Ferdig",
    FemalePlaceholder: "Kvinne",
    ChildrenTips: "2-11 år på reisetidspunktet",
    firstNamePlaceholder: "f.eks. WILLIAM JEFFERSON",
    IDTypePrompt: "ID-type",
    Infants: "Spedbarn",
    system_processing: "Systemfeil, vennligst prøv igjen",
    MobilePhone: "Mobiltelefon",
    noEncheck: "Vennligst skriv inn fornavn og mellomnavn på engelsk uten spesialtegn",
    Childticket: "Barnebillett",
    please_enter_ID_info: "Vennligst skriv inn ID-informasjon",
    Filters: "Filtre",
    Random: "Tilfeldig sete",
    Cancellation_Fee: "Avbestillingsgebyr",
    continue_booking: "Fortsett bestillingen",
    numSelected: "av {passegersnum} valgt",
    backToSelect: "Tilbake til å velge",
    from: "Fra {num}",
    credit: "Kreditt-/debetkort",
    Reset: "Tilbakestill",
    Baggage: "Bagasje",
    INNumCheckDigits: "Dokumentnummeret er på mellom 5 og 15 sifre eller bokstaver.",
    payNow: "Betal nå",
    Accept: "Godta",
    Europe: "Europa",
    NoThanks: "Nei, takk",
    avoid_price_change: "for å unngå prisendringer.",
    birthCheck: "Vennligst velg fødselsdato",
    City: "* By",
    Personal_item: "Personlig gjenstand",
    IDexpirationDatePlaceholder: "Velg utløpsdato for ID",
    birthPrompt: "Fødselsdato",
    Refer_to_the_regulations_of_airline: "Se flyselskapets bestemmelser",
    Change_Fee: "Endre gebyr",
    Cancellation_fee: "Avbestillingsgebyr",
    PremiumEconomy: "Premium økonomi",
    Price: "Pris",
    person: "/person",
    CustomerCentricSupport: "Kundesentrert support",
    ShowMore: "Vis mer",
    ChangeFee: "Gebyr for endring",
    IDexpirationDatePrompt: "Utløpsdato for ID",
    transfer_in: "Selvoverføring i {num}",
    professionalmanner: "Vårt globale kundeserviceteam er tilgjengelig for å hjelpe deg med alle dine forespørsler på en vennlig og profesjonell måte. ",
    at_least: "Minst {num} timer før ",
    passegers: "passasjeren(e)",
    select_date: "VelgDatoer",
    Checked_baggage: "Innjekket",
    PopularCities: "Beliebte Städte",
    ChangeFlight: "Endre fly",
    Sat: "Lør",
    PassengersInfo: "PassasjerInfo",
    carry_on_baggage_included: "Håndbagasje inkludert",
    Any: "Enhver",
    SelectClassPrice: "Velg klasse og pris",
    Clear: "Slett",
    AddBaggageTips: "Legg til nok bagasjekvote. Nå kan du ta  med deg alt for å reise rundt i verden!",
    total: "Totalt",
    hour: "t",
    Feedback: "Del din tilbakemelding",
    pay_fail_txt1: "vennligst kontakt vår kundeservice.",
    Depart: "Avreise",
    ok: "OK",
    ExtensiveRoutes: "Omfattende ruter",
    included: "Inkludert",
    NorthAmerica: "Nordamerika",
    Easy_Access: "Lett tilgjengelig",
    agreedTerms: "Jeg har lest og godtatt følgende bestillingsvilkår og personvernerklæring for Skytours.com.",
    Dec: "Des",
    Tue: "Tir ",
    Change: "Endre",
    Farefees: "Skatter og avgifter",
    insureCopywry: "Smart valg: 85% reisendes preferanse!",
    not_buy_hint: "Du har ikke valgt noen forsikringstjenester. Vil du gå tilbake og gjøre et valg?",
    PassengersAddTips: "Barn og spedbarn må være i følge med en voksen under flyvningen.",
    SelectClassPriceTips: "Totalt for alle passasjerer (inkl. skatter og avgifter)",
    Jan: "Jan",
    non_fefundable: "Avbestilling ikke tillatt",
    Partial_included: "Delvis inkludert",
    RefundableBooking: "100% refunderbar bestilling",
    not_buy: "Nei takk, jeg tar risikoen",
    ServiceChat: "Service Chat",
    cityAirport: "By eller flyplass",
    SelectFareTips: "Oppgrader prispakken din slik at du kan booke om eller motta refusjon når du bestemmer deg for å endre reisen ditt.",
    non_changeable: "Kan ikke byttes ut",
};
