export default {
    cancel: "取消",
    BookingDate: "预订日期",
    nationalityPlaceholder: "选择国籍",
    Apr: "4月",
    INNum: "输入证件号码",
    onlineCheckIn: "在线办理登机手续",
    NoFistNamecheck: "请输入名字和中间名",
    FlightsInfo: "航班信息",
    Reject: "拒绝",
    Month: "m",
    protected: "已投保",
    DelayedBaggageService: "行李遗失保障",
    About_Us_txt22: "为更好地满足您的需求，我们提供多种形式的客户服务。",
    IDNotice: "证件通知 • 姓名必须与证件一致 • 至少 6 个月有效期",
    About_Us_txt21: "贴心服务",
    addres_require_select: "请输入地址",
    FlightDelayedCanceled: "有想法要分享吗？",
    excluding_baggage_allowance: "不包括行李额",
    AllLanguages: "所有语言",
    riskManagement: "风控验证",
    Aisle: "靠过道座位",
    ShareThoughts: "您可以在我们的网站上反馈，分享您的想法并帮助我们提升您的体验。",
    No_thanks: "不了，谢谢",
    recentSearchesCities: "最近的搜索评论家",
    partially_used_ticket: "部分使用的机票",
    Sun: "周日",
    defaultKey: "时间（当地时间）",
    seat: "座位 ",
    InfantsTips: "旅行时未满 2 岁",
    Details: "详情",
    Passengers: "乘客",
    OtherServices: "其他服务",
    all_unused_tickets: "所有未使用的机票",
    Post_ZIP_Code: "* 邮编",
    NationalityPrompt: "国籍",
    cardNumber: "卡号",
    city_require_select: "请输入城市",
    Sep: "9月",
    ViewCurrentBaggagePolicy: "查看当前行李政策",
    before_departure: "起飞前",
    lowest_price: "最低价",
    country_require_select: "请选择国家",
    Infant: "婴儿",
    selected_passegers: "已选：{num} 位乘客",
    policy_detail: "*改期和取消费用按照航空公司官网上列出的政策收取。",
    SeatSelection: "座位选择",
    ContactUs: "联系我们",
    Part_included: "部分包含",
    Passport: "护照",
    PassengersContactInfo: "乘客及联系人信息",
    SecurePayment: "100%安全支付",
    Adult: "成人",
    Stops: "中转",
    Changes_not_permitted: "不允许改期",
    free: "免费",
    IDNumber: "证件号",
    Window: "靠窗座位",
    Thu: "周四",
    Jul: "7月",
    About_Us_txt3: "Debodia International Limited,地址:香港黄竹坑黄竹坑道38号2楼,公司注册号： 2585004;",
    About_Us_txt4: "BIGSKY Grup S.A.U.，地址:Avda. Sant Antoni 38, AD400 La Massana, Andorra,公司注册号: L-7085322-S。",
    numBaggageChecked: "为 {num}位乘客添加托运行李",
    cvv: "CVV",
    CallUs: "致电我们",
    Jun: "6月",
    About_Us_txt1: "IWOFLY PTE LTD,地址:6 RAFFLES QUAY #16-01, SINGAPORE (048580)，公司注册号： 202338315R;",
    About_Us_txt2: "IWOFLY S.L.,地址:Paseo de las Delicias 30, 7a planta de la localidad de Madrid, 28045,公司注册号： B88532528;",
    Adultticket: "成人票",
    About_Us_txt7: "10+年机票B2C经验,我们拥有跨国客户服务经验，提供中文、英语、法语服务。",
    updatesFlightTips: "登录查看航班动态",
    About_Us_txt8: "深知机票行业销售链层层加价的痛点，去掉中间商，我们致力于提供给您最低层的价格。",
    About_Us_txt5: "为什么选择Sky-tours.com?",
    businessClass: "商务舱",
    About_Us_txt6: "30+年机票B2B资源累积经验,提供超过40个国家的境内机票、国际机票，包括全服务航司与廉价航空。",
    About_Us_txt9: "想获取线下才能采购到的特殊机票政策吗？这是你在大型OTA中无法得到的优待！",
    Fare: "票价",
    the_price_difference_generated_1: "改签航班的差价由您负担。改签费按每人、每次变更收取。",
    NoMatchingFlightsFound: "未找到相应航班。更改搜索条件再试试看？",
    MalePlaceholder: "男性",
    E_Wallet: "电子钱包",
    the_price_difference_generated_2: "如您的航班因外部因素发生航变（非自愿航变），我们将根据航司答复为您提供航变解决方案。",
    price_per: "每名乘客",
    Select: "选择",
    Submit: "提交",
    Back_to_select: "返回添加",
    to: "到",
    noEnLastNmaecheck: "请用英文输入姓氏，不得包含特殊字符",
    Add: "添加",
    Email: "电子邮件",
    unpaid_booking_for_same_route: "同航线未支付订单",
    Pay: "支付",
    questionsContactUs: "如果您有任何问题，请与我们的客服团队联系。",
    pleaseLocation: "请输入城市或机场",
    premiumEconomy: "超经舱",
    WhyBookSt: "为何通过 Sky-tours 预订？",
    buy_refundable: "是的，使我的预订可退款",
    FeedbackCounts: "您的反馈很重要！",
    Restassured: "我们拥有安全的支付系统和强大的风险控制措施，优先保护您的个人信息和付款。",
    About_Us: "关于我们",
    letDoThis: "现在订阅",
    Aug: "8月",
    fistClass: "头等舱",
    Search: "搜索",
    LastUpdated: "*最近更新时间",
    SeparateSelection: "单独选择",
    OurPartners: "我们的伙伴",
    myBooking: "我的订单",
    search_similar_flights: "搜索类似航班",
    Airports: "机场",
    SecurityReliability: "安全可靠",
    kg_per_person: "千克每人",
    ShowFlights: "显示航班",
    About: "关于我们",
    province_require_select: "请输入州/省",
    firstName: "名字及中间名",
    flightsAlerts: "航班提醒",
    Nov: "11月",
    each_piece_cannot_exceed: "每件尺寸不得超过{num}厘米",
    piece: "件",
    nationalityCheck: "请选择国籍",
    please_retry: "系统内部异常，请重试！",
    General: "常见筛选",
    Class: "舱等",
    Adults: "成人",
    BookingInstructions: "儿童/婴儿预订须知",
    peace_of_mind: "安心预订航班",
    bookingNo: "订单号",
    FAQ_Q5: "我是否可以修改联系人信息？",
    Good_scenery: "视野更佳",
    FAQ_Q4: "我的机票可以退票或改期吗？",
    delete_all_records: "确定想要清除全部记录吗？",
    FAQ_Q1: "如何查询我的订单？",
    FAQ_Q3: "如何购买行李？",
    FAQ_Q2: "如何确认机票是否出票成功？",
    CancellationFee: "取消费用",
    privacy: "我们尊重您的隐私",
    Time: "时间",
    buy_bags: "好的，请追踪我的行李",
    State_Province: "* 州/省",
    Continue: "继续",
    alter_prices: "航空公司已更改该航班的价格。",
    travelDreamsRunWild: "立即注册，让旅行梦想尽情驰骋。",
    Checked_baggage_included: "包含托运行李",
    CheckIn2: "简化您的航班登机流程，无需在机场排队等候。",
    expiryDate: "有效期",
    FAQ_A5: "如果乘客在预订行程时提供了错误的邮箱地址或电话号码，最晚可以在起飞前48小时申请更改信息。乘客需要发送邮件到support{'@'}sky-tours.com，并提供正确的信息。",
    duration: "耗时",
    CheckIn1: "登机牌将在起飞前 24 小时内发送给您。",
    FAQ_A4: "每张客票的退改规则根据不同的航司政策和舱等而各不相同。在您购买机票时，预定详情页右侧会展示具体的退改规则。在您预定完成后，也可以在“我的订单”中查看您所购买机票的退改规则。",
    LeaveFeedback: "留下反馈",
    CheckIn3: "避免在柜台支付昂贵的值机费用。",
    FAQ_A1: "当您在Sky-tours成功下单后，系统会自动向您的预留邮箱发送包含订单号的邮件。您点击Sky-tours的网站首页右上角的“我的订单”，输入订单号和预留的邮箱后，即可查询您的订单。",
    Language: "语言",
    FAQ_A3: "Sky-tours为您提供绝大多数航司的托运行李额购买服务。根据航司的规定，不同的航线会配置不同的行李重量以及价格，您可在购买机票时根据提示随订单购买。如果您想在下单后购买额外的行李，请通过邮件联系Sky-tours的客服人员告知您的需求，客服人员会回复您相应的费用。您如果同意，我们会通过邮件给您发送支付链接，在您支付后我们会尽快为您办理，并通过邮件将结果反馈给您。\n请注意：客服人员仅通过support{'@'}sky-tours.com 邮箱与您联系，为了您的通讯与资金安全，切勿相信此外任何邮箱的支付通知。",
    InfantsTicket: "婴儿票（无座）",
    FAQ_A2: "如果您收到来自tickets{'@'}sky-tours.com的电子邮件，告知您的订单“已出票”并附上机票票号，即表明出票成功。\n如果您在订单支付72小时后仍未收到出票邮件，请先检查垃圾邮件。如果您确定未收到出票确认邮件或需要其他任何帮助，请随时联系客服。",
    Policies_Baggage: "政策和行李",
    recommendedCheapFlights: "廉价航班推荐",
    Children: "儿童",
    non_refundable: "不可退款",
    lowestPricedTips: "未来一个月内起飞的低价航班！",
    fistNamePrompt: "名字及中间名",
    Return: "回程",
    payment_failed: "支付失败！",
    ticket: "票",
    MobilePhoneTips: "请提供电话号码",
    AddSeat: "预订后添加座位通常会花费更多！",
    stop1: "1 次中转",
    riskInfo: "我们需要您提供以下信息以通过付款验证。",
    INNumCheck: "请输入证件号码",
    About_Us_txt20: "保证您个人信息的安全。",
    BusinessClass: "商务舱",
    futureAdventures: "精心策划的旅行内容来激发未来的出行灵感。",
    cardholder: "持卡人姓名",
    Mon: "周一",
    Checked: "托运行李",
    About_Us_txt19: "安全支付",
    TermsConditions: "条款及细则",
    About_Us_txt18: "航线覆盖 200 多个国家，价格极具竞争力",
    TickeTpricesTips: "正在为您搜索航班",
    notIncluded: "不包含",
    Asia: "亚洲",
    FAQ: "常见问题",
    Within: "在出发前{num}小时内",
    priceRise: "价格变动",
    About_Us_txt11: "凡是航司不收费的非自愿退票与改期项目，我们无条件免费服务。",
    About_Us_txt10: "每位客户都将获得温暖优质的一对一服务,拒绝自动答复，给您针对性的解决方案。",
    stop2: "2+次中转",
    About_Us_txt13: "伴您遨游梦想之地",
    About_Us_txt12: "希望Sky-tours.com能成为您的私人在线旅行企划伙伴，伴您遨游梦想之地。",
    Fri: "周五",
    About_Us_txt15: "联系信息",
    noLastNamecheck: "请输入姓氏",
    About_Us_txt14: "更全面、更灵活、更优惠",
    About_Us_txt17: "丰富的航线",
    About_Us_txt16: "如果您有任何问题，请随时联系我们的客户服务团队，我们将全天候为您服务。",
    PriceDetails: "价格详情",
    birthPlaceholder: "选择出生日期",
    book_now: "建议在价格飙升之前立即预订。",
    Oct: "10月",
    copyright: "{'@'} 2024 Sky-tours.com 版权所有",
    StopoverCity: "中途停留城市",
    Policies: "政策",
    Address: "* 地址",
    IDexpirationDateCheck: "请选择证件有效期",
    offeringHighly: "我们的航班网络遍布 200 +个国家，为您的出行便利提供极具竞争力的价格。",
    PleaseCompletePayment: "请在规定时间内完成支付",
    NameGuidelines: "姓名规则",
    oneWay: "单程",
    required: "必填项",
    PaymentMethods: "支付方式",
    after_departure: "起飞后",
    WishingpleasantJourney: "祝你旅途愉快！",
    PaymentProgress: "安全支付",
    info_safe: "Sky-tours将保护您的旅行并确保您的信息安全！",
    lastNamePlaceholder: "例如 ZHANG",
    ContactInfo: "联系方式",
    Sameselection: "为{num}名乘客进行相同选择",
    SittingTogether: "相邻座位 ",
    ID: "证件",
    enter: "输入",
    ServicesAdded: "已选服务",
    PaymentSuccessful: "支付成功！",
    Child: "儿童",
    Added: "已添加",
    Recommended: "推荐",
    post_ZIP_Code_require_select: "请输入编码",
    seatCompletedTxt: "名乘客尚未选座，您想返回预定座位吗？",
    enterEmailAdress: "输入你的邮箱",
    Carry_on_baggage: "手提行李",
    baggageAllowanceAndPolicies: "行李限额及政策",
    risk_control_rejected: "风控异常",
    all_airports: "所有机场",
    price_rise: "价格上涨",
    Wed: "周三",
    Country: "* 国家",
    pay_fail_txt: "如有任何问题，",
    enterNameExactly: "请确保您输入的姓名与办理值机时证件上的姓名完全一致",
    Mar: "3月",
    Hide: "隐藏",
    lastName: "姓氏",
    StayInspired: "接收旅行灵感",
    unknow: "详情",
    May: "5月",
    Cancel: "取消",
    add_insurance: "添加保险",
    privacy3: "隐私政策",
    Confirm: "确认",
    privacy2: "请阅读隐私政策，查看我们关于 cookie 的更多信息",
    privacy1: "我们使用技术、分析和营销 cookie 来帮助您完成登录和从上次中断的位置继续搜索等操作。 ",
    completeSubmission: "请在",
    About_Us_txt: "本网站由以下公司共同经营管理：",
    privacy4: "关闭或忽略横幅通知意味着您同意在您的设备或浏览器上使用基本 cookie。",
    Hide_2_transfers: "隐藏转机超过 2 次的航班",
    Economy: "经济舱",
    Airlines: "航空公司",
    check34: "名字和中间名已超过 34 个字符，请修改或联系客服协助处理",
    NonstopOnly: "仅限直达",
    CheckIn: "值机",
    roundTrip: "往返",
    pieces_per_person: "件每人",
    Feb: "2月",
    kg_per_piece: "千克每件",
    reminder: "提示",
    more: "详情",
    CurrentLanguage: "当前语言",
    gotit: "确认",
    SeatSelectionTips: "选择您喜欢的座位，享受舒适旅程。",
    bookingEmail: "接收预订确认邮件",
    AddBaggage: "添加行李",
    totallyBaggagePrice: "共计{num}件 {weight} 千克",
    AdditionalServices: "额外服务",
    check29: "姓氏超过 29 个字符，请修改或联系客服协助",
    SeatSelectionTipss: "我们将竭力根据您的选择预定座位。如果没有符合条件的座位，我们将会立即与您协商或退款。(\n请确保您的联系人电子邮件地址和电话号码填写正确。)",
    offer_time: "工作时间:9:00-18:00 (GMT+08)，周一至周日",
    CustomerSupport: "客户支持",
    AddPassengers: "添加乘客",
    contactEmailEnter: "请输入联系人邮箱",
    BaggageAllowance: "行李额",
    SelectFare: "选择票价",
    None: "无",
    IDTypePromptCheck: "请选择证件类型",
    Tips: "提示",
    change_to_airport: "{num}换到不同机场",
    GenderPrompt: "性别",
    CustomerService: "全球客服支持",
    Done: "确认",
    FemalePlaceholder: "女性",
    ChildrenTips: "旅行时2-11岁",
    firstNamePlaceholder: "例如 XIAOMING",
    IDTypePrompt: "证件类型",
    Infants: "婴儿",
    system_processing: "系统错误，请重试",
    MobilePhone: "手机号",
    noEncheck: "请用英文输入名字和中间名，不得包含特殊字符",
    Childticket: "儿童票",
    please_enter_ID_info: "请输入证件信息",
    Filters: "筛选",
    Random: "随机座位",
    Cancellation_Fee: "取消费用",
    continue_booking: "继续预订",
    numSelected: " {passegersnum} 位已选",
    backToSelect: "返回重新选座",
    from: "从 {num}起",
    credit: "信用卡/借记卡",
    Reset: "重置",
    Baggage: "行李",
    INNumCheckDigits: "证件号码为5至15位数字或字母",
    payNow: "立即支付",
    Accept: "接受",
    Europe: "欧洲",
    NoThanks: "不，谢谢",
    avoid_price_change: "内完成提交信息，以免价格变动。",
    birthCheck: "请选择出生日期",
    City: "* 城市",
    Personal_item: "随身物品",
    IDexpirationDatePlaceholder: "选择证件有效期",
    birthPrompt: "出生日期",
    Refer_to_the_regulations_of_airline: "参考航空公司规定",
    Change_Fee: "更改费用",
    Cancellation_fee: "退票费用",
    PremiumEconomy: "超经舱",
    Price: "价格",
    person: "/人",
    CustomerCentricSupport: "客户至上的服务",
    ShowMore: "展开",
    ChangeFee: "改签费用",
    IDexpirationDatePrompt: "证件有效日期",
    Save: "保存",
    transfer_in: "在{num}自行中转",
    professionalmanner: "我们的全球本地化客户服务团队可以以友好和专业的方式帮助您满足您的所有要求。",
    at_least: "至少提前{num}小时",
    passegers: "名乘客",
    select_date: "选择日期",
    Checked_baggage: "托运行李",
    PopularCities: "热门城市",
    ChangeFlight: "更改航班",
    Sat: "周六",
    PassengersInfo: "乘客信息",
    carry_on_baggage_included: "包含随身行李",
    Any: "任何",
    SelectClassPrice: "选择舱位和价格",
    Clear: "清除",
    AddBaggageTips: "添加足够的行李额。 现在你可以带上一切去环游世界了！",
    total: "总计",
    hour: "h",
    Feedback: "分享您的反馈",
    pay_fail_txt1: "请联系我们的客服团队。",
    Depart: "去程",
    ok: "好的",
    ExtensiveRoutes: "广泛的航线覆盖",
    included: "包含",
    NorthAmerica: "北美",
    Easy_Access: "方便出入",
    agreedTerms: "我已阅读并接受Sky-tours的条款及细则与隐私条款。",
    Dec: "12月",
    Tue: "周二",
    Change: "修改",
    Farefees: "税费及附加费",
    insureCopywry: "明智的选择：85% 旅行者的偏好！",
    not_buy_hint: "您未选择任何保险。您需要返回添加吗？",
    PassengersAddTips: "儿童和婴儿在飞行期间必须由成人陪同。",
    SelectClassPriceTips: "所有乘客的费用（包括税费&手续费）",
    Jan: "1月",
    non_fefundable: "不允许退票",
    Partial_included: "部分包含",
    RefundableBooking: "100%可退款预订",
    not_buy: "不，我愿意自行承担风险",
    ServiceChat: "客服咨询",
    cityAirport: "城市或机场",
    SelectFareTips: "升级您的票价套餐，以便您在决定更改计划时可以重新预订或获得退款。",
    non_changeable: "不可更改",
};
