export default {
    cancel: "取消",
    BookingDate: "預訂日期",
    nationalityPlaceholder: "選擇國籍",
    Apr: "4月",
    INNum: "輸入證件號碼",
    onlineCheckIn: "在線辦理登機手續",
    NoFistNamecheck: "請輸入名字和中間名",
    FlightsInfo: "航班資訊",
    Reject: "拒絕",
    Month: "m",
    protected: "已投保",
    DelayedBaggageService: "行李遺失保障",
    About_Us_txt22: "為更好地滿足您的需求，我們提供多種形式的客戶服務。",
    IDNotice: "證件通知 • 姓名必須與證件一致 •  6 個月以上效期",
    About_Us_txt21: "貼心服務",
    addres_require_select: "請輸入地址",
    FlightDelayedCanceled: "有想法要分享嗎？",
    excluding_baggage_allowance: "不包括行李額",
    AllLanguages: "所有語言",
    riskManagement: "風控驗證",
    Aisle: "靠走道座位",
    ShareThoughts: "您可以在我們的網站上回饋，分享您的想法并幫助我們提升您的體驗。",
    No_thanks: "不了，謝謝",
    recentSearchesCities: "最近的搜索評論家",
    partially_used_ticket: "部分使用的機票",
    Sun: "週日",
    defaultKey: "時間（當地時間）",
    seat: "座位 ",
    InfantsTips: "旅行時未滿2 歲",
    Details: "詳情",
    Passengers: "乘客",
    OtherServices: "其他服務",
    all_unused_tickets: "所有未使用的機票",
    Post_ZIP_Code: "* 郵編",
    NationalityPrompt: "國籍",
    cardNumber: "卡號",
    city_require_select: "請輸入城市",
    Sep: "9月",
    ViewCurrentBaggagePolicy: "查看當前行李政策",
    before_departure: "起飛前",
    lowest_price: "最低價",
    country_require_select: "請選擇國家",
    selected_passegers: "已選：{num} 位乘客",
    policy_detail: "*改期和取消費用依照航空公司官網上所列的政策收取。",
    SeatSelection: "座位選擇",
    ContactUs: "聯絡我們",
    Part_included: "部分包含",
    Passport: "護照",
    PassengersContactInfo: "乘客及聯絡人訊息",
    SecurePayment: "100%付款安全",
    Adult: "成人",
    Stops: "轉機",
    Changes_not_permitted: "不允許改期",
    free: "免費",
    IDNumber: "證件編號",
    Window: "靠窗座位",
    Thu: "週四",
    Jul: "7月",
    About_Us_txt3: "Debodia International Limited,地址:香港黃竹坑黃竹坑道38號2樓,公司註冊號: 2585004;",
    About_Us_txt4: "BIGSKY Grup S.A.U.,地址:Avda. Sant Antoni 38, AD400 La Massana, Andorra,公司註冊號: L-7085322-S。",
    numBaggageChecked: "為 {num}位乘客添加托運行李",
    cvv: "CVV",
    CallUs: "致電我們",
    Jun: "6月",
    About_Us_txt1: "IWOFLY PTE LTD,地址:6 RAFFLES QUAY #16-01, SINGAPORE (048580),公司註冊號: 202338315R;",
    About_Us_txt2: "IWOFLY S.L.,地址:Paseo de las Delicias 30, 7a planta de la localidad de Madrid, 28045,公司註冊號: B88532528；",
    Adultticket: "成人票",
    About_Us_txt7: "10+年機票B2C經驗，我們擁有跨國客戶服務經驗，提供中文、英語、法語服務。",
    updatesFlightTips: "登入查看航班動態",
    About_Us_txt8: "深知機票行業銷售鏈層層加價的痛點，去掉中間商，我們致力於提供給您最低層的價格。",
    About_Us_txt5: "為什麼選擇Sky-tours.com?",
    businessClass: "商務艙",
    About_Us_txt6: "30+年機票B2B資源累積經驗，提供超過40個國家的境內機票、國際機票,包括全服務航司與廉價航空。",
    About_Us_txt9: "想獲取線下才能採購到的特殊機票政策嗎？這是你在大型OTA中無法得到的優待！",
    Fare: "票價",
    the_price_difference_generated_1: "變更航班的差價由您負擔。 變更費按每人、每次變更收取。",
    NoMatchingFlightsFound: "未找到相應航班。更改搜尋條件再試試看？",
    MalePlaceholder: "男性",
    E_Wallet: "電子錢包",
    the_price_difference_generated_2: "如您的航班因外部因素而發生航變（非自願航變），我們將根據航司答覆為您提供航變解決方案。",
    price_per: "每位乘客",
    Select: "選擇",
    Submit: "提交",
    Back_to_select: "返回添加",
    to: "到",
    noEnLastNmaecheck: "請用英文輸入姓氏，不得包含特殊字符",
    Add: "新增",
    Email: "電子郵件",
    unpaid_booking_for_same_route: "同航線未支付訂單",
    Pay: "付款",
    questionsContactUs: "如果您有任何問題，請與我們的客服團隊聯系。",
    pleaseLocation: "請輸入城市或機場",
    premiumEconomy: "豪經艙",
    WhyBookSt: "為何透過 Sky-tours 預訂？",
    buy_refundable: "是的，使我的預訂可退款",
    FeedbackCounts: "您的回饋對我們很重要！",
    Restassured: "我們擁有安全的支付系統和強大的風險控制措施，優先保護您的個人資訊和付款。",
    About_Us: "關於我們",
    letDoThis: "現在訂閱",
    Aug: "8月",
    fistClass: "頭等艙",
    Search: "搜尋",
    LastUpdated: "*最近更新時間",
    SeparateSelection: "單獨選擇",
    OurPartners: "我們的夥伴",
    myBooking: "我的訂單",
    search_similar_flights: "搜索類似航班",
    Airports: "機場",
    SecurityReliability: "安全可靠",
    kg_per_person: "千克每人",
    ShowFlights: "顯示航班",
    province_require_select: "請選擇州/省",
    firstName: "名字及中間名",
    flightsAlerts: "航班提醒",
    Nov: "11月",
    each_piece_cannot_exceed: "每件尺寸不得超過{num}厘米",
    piece: "件",
    nationalityCheck: "請選擇國籍",
    please_retry: "系統內部異常，請重試！",
    General: "常見篩選",
    Class: "艙等",
    Adults: "成人",
    BookingInstructions: "兒童/嬰兒預訂須知",
    peace_of_mind: "安心預訂航班",
    bookingNo: "訂單編號",
    FAQ_Q5: "我是否可以修改聯絡人資訊？",
    Good_scenery: "視野更佳",
    FAQ_Q4: "我的機票可以退票或改期嗎？",
    delete_all_records: "確定想要清除全部記錄嗎？",
    FAQ_Q1: "如何查詢我的訂單？",
    FAQ_Q3: "如何購買行李？",
    FAQ_Q2: "如何確認機票是否出票成功？",
    CancellationFee: "取消費用",
    Time: "時間",
    buy_bags: "好的，請追蹤我的行李",
    State_Province: "* 州/省",
    Continue: "繼續",
    alter_prices: "航空公司已更改該航班的價格。",
    travelDreamsRunWild: "立即註冊，讓旅行夢想盡情馳騁。",
    Checked_baggage_included: "包含托運行李",
    CheckIn2: "簡化您的航班登機流程，無需在機場排隊等候。",
    expiryDate: "有效期",
    FAQ_A5: "如果乘客在預訂行程時提供了錯誤的郵箱地址或電話號碼，最晚可以在起飛前48小時申請更改信息。乘客需要發送郵件到support{'@'}sky-tours.com，並提供正確的信息。",
    duration: "耗時",
    CheckIn1: "登機證將在起飛前 24 小時內發送給您。",
    FAQ_A4: "每張客票的退改規則根據不同的航司政策和艙等而各不相同。在您購買機票時，預定詳情頁右側會展示具體的退改規則。在您預定完成後，也可以在“我的訂單”中查看您所購買機票的退改規則。",
    LeaveFeedback: "留下反饋",
    CheckIn3: "避免在櫃檯支付昂貴的報到費用。",
    FAQ_A1: "當您在Sky-tours成功下單後，系統會自動向您的預留郵箱發送包含訂單號的郵件。您點擊Sky-tours的網站首頁右上角的“我的訂單”，輸入訂單號和預留的郵箱後，即可查詢您的訂單。\n如果您未收到該郵件，請先檢查垃圾郵件。如果垃圾郵件裡也沒有，有可能是您輸錯了預留郵箱，這種情況下請及時聯繫客服協助您修改。",
    Language: "語言",
    FAQ_A3: "Sky-tours為您提供絕大多數航司的托運行李額購買服務。根據航司的規定，不同的航線會配置不同的行李重量以及價格，您可在購買機票時根據提示隨訂單購買。如果您想在下單後購買額外的行李，請通過郵件聯繫Sky-tours的客服人員告知您的需求，客服人員會回复您相應的費用。您如果同意，我們會通過郵件給您發送支付鏈接，在您支付後我們會盡快為您辦理，並通過郵件將結果反饋給您。\n請注意：客服人員僅透過support{'@'}sky-tours.com 信箱與您聯繫，為了您的通訊與資金安全，切勿相信此外任何信箱的支付通知。",
    InfantsTicket: "嬰兒票（無座）",
    FAQ_A2: "如果您收到來自tickets{'@'}sky-tours.com的電子郵件，告知您的訂單“已出票”並附上機票票號，即表明出票成功。\n如果您在訂單支付72小時後仍未收到出票郵件，請先檢查垃圾郵件。如果您確定未收到出票確認郵件或需要其他任何幫助，請隨時聯繫客服。",
    Policies_Baggage: "政策和行李",
    recommendedCheapFlights: "廉價航班推薦",
    Children: "兒童",
    non_refundable: "不可退款",
    lowestPricedTips: "未來一個月內起飛的低價航班！",
    fistNamePrompt: "名字及中間名",
    Return: "回程",
    payment_failed: "支付失敗！",
    ticket: "票",
    MobilePhoneTips: "請提供電話號碼",
    AddSeat: "完成預訂後選擇座位通常會花費更多！",
    stop1: "1 次中轉",
    riskInfo: "我們需要您提供以下信息以通過付款驗證。",
    INNumCheck: "請輸入證件號碼",
    About_Us_txt20: "保證您個人信息的安全。",
    BusinessClass: "商務艙",
    futureAdventures: "精心策劃的旅行內容，激動未來的出遊靈感。",
    cardholder: "持卡人姓名",
    Mon: "週一",
    Checked: "托運行李",
    About_Us_txt19: "安全支付",
    TermsConditions: "條款及細則",
    About_Us_txt18: "航線覆蓋 200 多個國家，價格極具競爭力",
    TickeTpricesTips: "正在為您搜索航班",
    notIncluded: "不包含",
    Asia: "亚洲",
    FAQ: "常見問題",
    Within: "在出發前{num}小時內",
    priceRise: "價格變動",
    About_Us_txt11: "凡是航司不收費的非自願退票與改期項目，我們無條件免費服務。",
    About_Us_txt10: "每位客戶都將獲得溫暖優質的一對一服務，拒絕自動答复,給您針對性的解決方案。",
    stop2: "2+次中轉",
    About_Us_txt13: "伴您遨遊夢想之地",
    About_Us_txt12: "希望Sky-tours.com能成為您的私人線上旅遊企劃夥伴，伴您遨遊夢想之地。",
    Fri: "週五",
    About_Us_txt15: "聯繫信息",
    noLastNamecheck: "請輸入姓氏",
    About_Us_txt14: "更全面、更靈活、更優惠",
    About_Us_txt17: "豐富的航線",
    About_Us_txt16: "如果您有任何問題，請隨時聯系我們的客戶服務團隊，我們將全天候為您服務。",
    PriceDetails: "價格詳情",
    birthPlaceholder: "選擇出生日期",
    book_now: "建議在價格飆升之前立即預訂。",
    Oct: "10月",
    copyright: "{'@'} 2024 Sky-tours.com 版權所有",
    StopoverCity: "中途停留城市",
    Policies: "政策",
    Address: "* 地址",
    IDexpirationDateCheck: "請選擇證件有效期",
    offeringHighly: "我們的航班網絡遍佈 200 多個國家，為您提供極具競爭力的價格。",
    PleaseCompletePayment: "請在規定時間內完成支付",
    NameGuidelines: "姓名規則",
    oneWay: "單程",
    required: "必填項",
    PaymentMethods: "付款方式",
    after_departure: "起飛後",
    WishingpleasantJourney: "祝你旅途愉快！",
    PaymentProgress: "安全支付",
    info_safe: "Sky-tours將保護您的旅行並確保您的信息安全！",
    lastNamePlaceholder: "例如 ZHANG",
    ContactInfo: "聯絡方式",
    SittingTogether: "相鄰座位",
    ID: "證件",
    enter: "輸入",
    ServicesAdded: "已選服務",
    PaymentSuccessful: "付款成功！",
    Child: "兒童",
    Added: "已新增",
    Recommended: "推薦",
    post_ZIP_Code_require_select: "請輸入編碼",
    seatCompletedTxt: "名乘客尚未選座，您想返回預定座位嗎？",
    enterEmailAdress: "輸入你的電郵",
    Carry_on_baggage: "手提行李",
    baggageAllowanceAndPolicies: "行李限額及政策",
    risk_control_rejected: "風控異常",
    all_airports: "所有機場",
    price_rise: "价格上漲",
    Wed: "週三",
    Country: "* 國家",
    pay_fail_txt: "如有任何問題，",
    enterNameExactly: "請確保您輸入的姓名與辦理報到時證件上的姓名完全一致",
    Mar: "3月",
    Hide: "隱藏",
    lastName: "姓氏",
    StayInspired: "保持靈感",
    unknow: "詳情",
    May: "5月",
    Cancel: "取消",
    add_insurance: "添加保險",
    privacy3: "隱私政策",
    Confirm: "確認",
    privacy2: "請閱讀隱私政策，查看我們關於 cookie 的更多信息",
    privacy1: "我們使用技術、分析和營銷 cookie 來幫助您完成登錄和從上次中斷的位置繼續搜索等操作。 ",
    completeSubmission: "請在",
    About_Us_txt: "本網站由以下公司共同經營管理：",
    privacy4: "關閉或忽略橫幅通知意味著您同意在您的設備或瀏覽器上使用基本 cookie。",
    Hide_2_transfers: "隱藏轉機超過 2 次的航班",
    Economy: "經濟艙",
    Airlines: "航空公司",
    check34: "名字和中間名已超過 34 個字符，請修改或聯絡客服協助處理",
    NonstopOnly: "限直達",
    CheckIn: "報到",
    roundTrip: "來回",
    pieces_per_person: "件每人",
    Feb: "2月",
    kg_per_piece: "千克每件",
    reminder: "提示",
    CurrentLanguage: "目前語言",
    gotit: "確認",
    SeatSelectionTips: "選擇您喜歡的座位，享受舒適旅程。",
    bookingEmail: "接收預訂確認郵件",
    AddBaggage: "添加行李",
    totallyBaggagePrice: "共計{num}件 {weight} 千克",
    AdditionalServices: "額外服務",
    check29: "姓氏超過 29 個字，請修改或聯絡客服協助",
    SeatSelectionTipss: "我們將竭力根據您的選擇預定座位。如果沒有符合條件的座位，我們將會立即與您協商或退款。(請確保您的聯系人電子郵件地址和電話號碼填寫正確。)",
    offer_time: "工作時間:9:00-18:00 (GMT+08)，週一至週日",
    CustomerSupport: "客戶支援",
    AddPassengers: "增加乘客",
    contactEmailEnter: "請輸入聯絡人信箱",
    BaggageAllowance: "行李額",
    SelectFare: "選擇票價",
    None: "無",
    IDTypePromptCheck: "請選擇證件類型",
    Tips: "提醒",
    change_to_airport: "{num}換到不同機場",
    GenderPrompt: "性別",
    CustomerService: "全球客服支持",
    Done: "确认",
    FemalePlaceholder: "女性",
    ChildrenTips: "旅行時2-11歲",
    firstNamePlaceholder: "例如 XIAOMING",
    IDTypePrompt: "證件類型",
    Infants: "嬰兒",
    system_processing: "系統錯誤，請重試",
    MobilePhone: "手機號碼",
    noEncheck: "请用英文输入名字和中间名，不得包含特殊字符",
    Childticket: "兒童票",
    please_enter_ID_info: "請輸入證件信息",
    Filters: "篩選",
    Random: "隨機座位",
    Cancellation_Fee: "取消費用",
    continue_booking: "繼續預訂",
    numSelected: " {passegersnum} 位已選",
    backToSelect: "返回重新選座",
    from: "從 {num}起",
    credit: "信用卡/金融卡",
    Reset: "重置",
    Baggage: "行李",
    INNumCheckDigits: "證件號碼為5至15位數字或字母",
    payNow: "立即付款",
    Accept: "接受",
    Europe: "欧洲",
    NoThanks: "不，謝謝",
    avoid_price_change: "內完成提交信息，以免價格變動。",
    birthCheck: "請選擇出生日期",
    City: "* 城市",
    Personal_item: "隨身物品",
    IDexpirationDatePlaceholder: "選擇證件有效期",
    birthPrompt: "出生日期",
    Refer_to_the_regulations_of_airline: "參考航空公司規定",
    Change_Fee: "更改費用",
    Cancellation_fee: "退票費用",
    PremiumEconomy: "豪經艙",
    Price: "價格",
    person: "/人",
    CustomerCentricSupport: "客戶至上的服務",
    ShowMore: "展開",
    ChangeFee: "更改費用",
    IDexpirationDatePrompt: "證件有效日期",
    Save: "儲存",
    transfer_in: "在{num}自行中轉",
    professionalmanner: "我們的航班網絡遍佈 200 +個國家，為您的旅遊提供極具競爭力的價格。",
    at_least: "至少提前{num}小時",
    passegers: "名乘客",
    select_date: "選擇日期",
    Checked_baggage: "托運行李",
    PopularCities: "热门城市",
    ChangeFlight: "更改航班",
    Sat: "週六",
    PassengersInfo: "乘客資訊",
    carry_on_baggage_included: "包含隨身行李",
    Any: "任何",
    SelectClassPrice: "選擇艙等和價格",
    Clear: "清除",
    AddBaggageTips: "增加足夠的行李。 現在你可以帶上一切去環遊世界了！",
    total: "總計",
    hour: "h",
    Feedback: "分享您的回饋",
    pay_fail_txt1: "請聯繫我們的客服團隊。",
    Depart: "去程",
    ok: "好的",
    ExtensiveRoutes: "廣泛的航線覆蓋",
    included: "包含",
    NorthAmerica: "北美",
    Easy_Access: "方便出入",
    agreedTerms: "我已閱讀並接受Sky-tours的條款及細則與隱私條款。",
    Dec: "12月",
    Tue: "週二",
    Change: "修改",
    Farefees: "稅費及附加費",
    insureCopywry: "明智的選擇：85% 旅行者的偏好！",
    not_buy_hint: "您未選擇任何保險。您需要返回添加嗎？",
    PassengersAddTips: "兒童和嬰兒在飛行期間必須由成人陪同。",
    SelectClassPriceTips: "所有乘客的費用（包括稅金&手續費）",
    Jan: "1月",
    non_fefundable: "不允許退票",
    Partial_included: "部分包含",
    RefundableBooking: "100%可全額退款",
    not_buy: "不，我願意自行承擔風險",
    ServiceChat: "客服諮詢",
    cityAirport: "城市或機場",
    SelectFareTips: "升級您的票價套餐，以便您在決定更改計劃時可以重新預訂或退款。",
    non_changeable: "不可更改",
};
